[[automotive_manufacturers]]

== Automotive Manufacturers


.Contacting Your Automotive Manufacturer
****
If you have a problem with a car purchased from a local dealer, first try to work it out with the dealer. If the problem is not resolved, contact the manufacturer&rsquo;s regional or national office. Ask for the Consumer Affairs Office.


If you are still unsuccessful, consider contacting the automotive dispute resolution resources listed at the end of this section. The method used to resolve your dispute may be mediation, arbitration, or conciliation. Decisions of arbitrators are usually binding and must be accepted by both the customer and the business. Ask for a copy of the rules of the program before you file your case. See page 55 for an overview of dispute resolution programs. 

A local or state consumer agency (p. 112) could also be a useful resource in resolving problems with your vehicle. If you have a new vehicle, be sure to ask whether you have any protection under a state &ldquo;lemon&rdquo; law (p. 10). 


****


*Acura* 

1919 Torrance Blvd. Mail Stop 500-2N7E Torrance, CA 90501-2746 Toll free: 1-800-382-2238 

link:$$http://www.acura.com$$[www.acura.com] 

*American Honda Motor Company, Inc.* 

1919 Torrance Blvd. Mail Stop 500-2N-7A Torrance, CA 90501-2746 Toll free: 1-800-999-1009 

link:$$http://www.honda.com$$[www.honda.com] 

*American Suzuki Motor Corporation* 

PO Box 1100 Brea, CA 92822-1100  714-572-1490 (Motorcycle/ATV/Marine)  Toll free: 1-800-934-0934 (Automotive) 

link:$$http://www.suzuki.com$$[www.suzuki.com] 

*Audi of America, Inc.* 

3800 W. Hamlin Rd. Auburns Hills, MI 48326 Toll free: 1-800-822-2834 

pass:[<email>auditalk@audi.com</email>] 

link:$$http://www.audiusa.com$$[www.audiusa.com] 

*BMW of North America, LLC* 

300 Chestnut Ridge Rd. Woodcliff Lake, NJ 07677-7731 201-307-4000 Toll free: 1-800-831-1117 

pass:[<email>customerrelations@bmwusa.com</email>] 

link:$$http://www.bmwusa.com$$[www.bmwusa.com] 

*Buick* 

PO Box 33136 Detroit, MI 48232-5136 Toll free: 1-800-521-7300 TTY: 1-800-735-2900 

link:$$http://www.buick.com$$[www.buick.com] 

*Cadillac* 

PO Box 33169 Detroit, MI 48232-5169 Toll free: 1-800-458-8006 TTY: 1-800-255-2683 

link:$$http://www.cadillac.com$$[www.cadillac.com] 

*Chevrolet* 

PO Box 33170 Detroit, MI 48232-5170 Toll free: 1-800-222-1020 TTY: 1-800-735-2988 

link:$$http://www.chevrolet.com$$[www.chevrolet.com] 

*Chrysler Group, LLC* 

PO Box 21-8004 Auburn Hills, MI 48321-8004 Toll free: 1-800-247-9753 

link:$$http://www.chrysler.com$$[www.chrysler.com] 

*Dodge* 

PO Box 21-8007 Auburn Hills, MI 48321-8007 Toll free: 1-800-423-6343 

link:$$http://www.dodge.com$$[www.dodge.com] 

*Ferrari North America, Inc.* 

250 Sylvan Ave. Englewood Cliffs, NJ 07632 201-816-2600 Toll free: 1-866-551-2828 

*Ford Motor Company* 

PO Box 6248 Dearborn, MI 48126 Toll free: 1-800-392-3673 TTY: 1-800-232-5952 

link:$$http://www.ford.com$$[www.ford.com] 

*GMC* 

PO Box 33172 Detroit, MI 48232-5172 Toll free: 1-800-462-8782 TTY: 1-800-735-2988 

link:$$http://www.gmc.com$$[www.gmc.com] 

*Harley-Davidson* 

3700 W. Juneau Ave. Milwaukee, WI 53208 Toll free: 1-800-258-2464 

link:$$http://www.harley-davidson.com$$[www.harley-davidson.com] 

*Hyundai Motor America* 

PO Box 20850 Fountain Valley, CA 92728-0850 714-965-3000 Toll free: 1-800-633-5151 

pass:[<email>consumeraffairs@hmausa.com</email>] 

link:$$http://www.hyundaiusa.com$$[www.hyundaiusa.com] 

*Infiniti* 

See: Nissan North America, Inc. Toll free: 1-800-662-6200 

link:$$http://www.infiniti.com$$[www.infiniti.com] 

*Isuzu Motors America, Inc.* 

1400 S. Douglass Rd., Suite 100 Anaheim, CA 92806 714-935-9300 Toll free: 1-800-255-6727 

link:$$http://www.isuzu.com$$[www.isuzu.com] 

*Jaguar Cars* 

Customer Relationship Center 555 MacArthur Blvd. Mahwah, NJ 07430-2327 Toll free: 1-855-524-8278 

link:$$http://www.jaguarusa.com$$[www.jaguarusa.com] 

*Jeep* 

See: Chrysler Group, LLC Toll free: 1-877-426-5337 

link:$$http://www.jeep.com/en$$[www.jeep.com/en] 

*Kia Motors America, Inc.* 

PO Box 52410 Irvine, CA 92619-2410 Toll free: 1-800-333-4542 

link:$$http://www.kia.com$$[www.kia.com] 

*Land Rover* 

Customer Relationship Center 555 MacArthur Blvd. Mahwah, NJ 07430 Toll free: 1-800-637-6837 

link:$$http://www.landroverusa.com$$[www.landroverusa.com] 

*Lexus* 

PO Box 2991 Mail Drop L201 Torrance, CA 90509-2991 Toll free: 1-800-255-3987 

*Lincoln* 

See: Ford Motor Company Toll free: 1-800-521-4140 

link:$$http://www.lincoln.com$$[www.lincoln.com] 

*Mazda North American Operations* 

PO Box 19734 Irvine, CA 92623-9734 Toll free: 1-800-222-5500 

link:$$http://www.mazdausa.com$$[www.mazdausa.com] 

*Mercedes Benz, USA, LLC* 

Three Mercedes Dr. Montvale, NJ 07645 Toll free: 1-800-367-6372 

link:$$http://www.mbusa.com$$[www.mbusa.com] 

*Mercury* 

PO Box 6128 Dearborn, MI 48121 Toll free: 1-800-521-4140 

link:$$http://www.mercuryvehicles.com$$[www.mercuryvehicles.com] 

*Mitsubishi Motors North America, Inc.* 

PO Box 6400 Cypress, CA 90630-998 Toll free: 1-888-648-7820 

link:$$http://www.mitsubishicars.com$$[www.mitsubishicars.com] 

*Nissan North America, Inc.* 

PO Box 685003 Franklin, TN 37068-5003 Toll free: 1-800-647-7261 

link:$$http://www.nissanusa.com$$[www.nissanusa.com] 

*Oldsmobile* 

PO Box 33171 Detroit, MI 48232-5171 Toll free: 1-800-442-6537 TTY: 1-800-833-9935 

pass:[<email>cac@oldsmobile.com</email>] 

link:$$http://www.oldsmobile.com$$[www.oldsmobile.com] 

*Peugeot Motors of America, Inc.* 

Overlook at Great Notch 150 Clove Rd. Little Falls, NJ 07424 973-812-4444 

pass:[<email>customerservice@peugeotusa.net</email>] 

link:$$http://www.peugeot.com$$[www.peugeot.com] 

*Pontiac* 

See: GMC Toll free: 1-800-762-2737 TTY: 1-800-833-9935 

link:$$http://www.pontiac.com$$[www.pontiac.com] 

*Porsche Cars North America, Inc.* 

Owner Relations 980 Hammond Dr., Suite 1000 Atlanta, GA 30328 Toll free: 1-800-767-7243 

link:$$http://www.porsche.com/usa$$[www.porsche.com/usa] 

*Saab Automobile USA* 

Toll free: 1-800-955-9007 

link:$$http://www.saabusa.com$$[www.saabusa.com] 

*Saturn* 

Customer Service Center PO Box 33173 Detroit, MI 48232-5173 Toll free: 1-800-553-6000 


pass:[<email>cac@saturn.com</email>] 

link:$$http://www.saturn.com$$[www.saturn.com] 

*Smart USA* 

See: Mercedes Benz, USA, LLC Toll free: 1-800-762-7887 

link:$$http://www.smartusa.com$$[www.smartusa.com] 

*Subaru of America, Inc.* 

Subaru Plaza PO Box 6000 Cherry Hill, NJ 08034-6000 Toll free: 1-800-782-2783 

link:$$http://www.subaru.com$$[www.subaru.com] 

*Toyota Motor Sales U.S.A., Inc.* 

Department WC 11 19001 S. Western Ave. Torrance, CA 90501 310-468-4000 Toll free: 1-800-331-4331 

link:$$http://www.toyota.com$$[www.toyota.com] 

*Volkswagen Group of America, Inc.* 

3800 Hamlin Rd. Auburn Hills, MI 48326 Toll free: 1-800-822-8987 

link:$$http://www.vw.com$$[www.vw.com] 

*Volvo Cars of North America* 

One Volvo Dr. PO Box 914 Rockleigh, NJ 07647 Toll free: 1-800-458-1552 

link:$$http://www.volvocars.com$$[www.volvocars.com] 


=== Automotive Dispute Resolution Programs

*BBB AUTO LINE* 

Council of Better Business Bureaus, Inc. 3033 Wilson Blvd., Suite 600 Arlington, VA 22201-3863 703-276-0100 Toll free: 1-800-955-5100 

pass:[<email>info@cbbb.bbb.org</email>] 

link:$$http://www.bbb.org$$[www.bbb.org] 

Third-party dispute resolution program for automobile manufacturers. 

*Consumer Financial Protection Bureau* 

PO Box 4503 Iowa City, IA 52244 Toll free: 1-855-411-2372 TTY: 1-855-729-2372 

pass:[<email>info@consumerfinance.gov</email>] 

link:$$http://www.consumerfinance.gov$$[www.consumerfinance.gov] 

The CFPB supervises and accepts complaints related to your vehicle loans and financing problems. Contact this agency if you encountered problems while shopping for or managing your vehicle loan. 

*DOT Auto Safety Hotline* 

1200 New Jersey Ave., SE., West Bldg. Washington, DC 20590 Toll free: 1-888-327-4236 TTY: 1-800-424-9153 

link:$$http://www.nhtsa.gov/Contact$$[www.nhtsa.gov/Contact] 

Consumers can contact the DOT Auto Safety Hotline to report safety defects in vehicles, tires, and child safety seats. Information is available about air bags, child safety seats, seat belts, and general highway safety. Consumers who experience a safety defect in their vehicle are encouraged to report the defect to the Hotline in addition to the dealer or manufacturer. 

*Motorist Assurance Program (MAP)* 

201 Park Washington Ct. Falls Church, VA 22046 703-538-3557 

pass:[<email>map@motorist.org</email>] 

link:$$http://www.motorist.org$$[www.motorist.org] 

MAP accredits those auto repair shops that apply and follow industry developed standards for inspecting vehicles as well as meet other requirements. MAP handles inquiries and disputes between accredited shops and customers. MAP also offers information to consumers about how to locate a repair shop, talk to a technician, and work successfully with auto repair shops. 

*National Center for Dispute Settlement (NCDS)* 

43230 Garfield Rd., Suite 130 Clinton Township, MI 48038 586-226-2470 

pass:[<email>info@ncdsusa.org</email>] 

link:$$http://www.ncdsusa.org$$[www.ncdsusa.org] 

NCDS is a neutral administrator of the dispute resolution process. NCDS facilitates the process under their rules, but is not the decision maker, rather the decision is made by an independent arbitrator. 


.Contacting Automotive Dispute Resolution Programs
****
An automotive dispute resolution program is another  resource to consult if you need to solve a problem with  your car&rsquo;s manufacturer or dealership. 

If you have been unable to reach an agreement with your  manufacturer, consider contacting the automotive dispute  resolution resources listed here. 

The method used to resolve your dispute may be mediation,  arbitration, or conciliation. Decisions of arbitrators are  usually binding and must be accepted by both the customer  and the business. Ask for a copy of the rules of the program  before you file your case. 

Read the contract that you signed when you purchased your car.  Manufacturers and dealers may have included a clause that  requires you to agree to mandatory arbitration, waiving  your right to sue or settle a disagreement in a court of law. 


****


