[[better_business_bureaus]]

== Better Business Bureaus


.Contacting Your Local Better Business Bureau
****
Better Business Bureaus (BBBs) are non-profit organizations  that encourage honest advertising and selling practices, and  are supported primarily by local businesses. BBBs offer a  variety of consumer services, including consumer education  materials; business reports, particularly unanswered or  unsettled complaints or other problems; mediation and arbitration  services; and information about charities and other organizations  that are seeking public donations. They also provide ratings (A,  B, C, D, or F) of local companies to express the BBB&rsquo;s confidence  that the company operates in a trustworthy manner and demonstrates  a willingness to resolve customer concerns. 

Complaints should be submitted in writing so that an accurate  record exists of the dispute. The BBB will then present the  complaint to the company involved. If the complaint is not  resolved, the BBB may offer an alternative dispute settlement  process. BBBs do not judge or rate individual products or brands,  handle employer/employee wage disputes, or give legal advice. 

If you need help with a consumer question or complaint, call  your local BBB or visit its website. 

BBBOnLine (link:$$http://www.bbb.org/online$$[]) provides  Internet users an easy way to verify the legitimacy of online  businesses. Companies carrying the BBBOnLine seal have been  checked out by the BBB and agree to resolve customer concerns. 

The Council of Better Business Bureaus, the umbrella organization  for the BBBs, can assist with complaints about the truthfulness  and accuracy of national advertising claims, including children&rsquo;s  advertising; provide reports on national soliciting charities; and  help to settle disputes with automobile manufacturers through the  BBB Auto Line program (p. 66). 


****



=== Council

_Arlington_ 

3033 Wilson Blvd., Suite 600 Arlington, VA 22201 703-276-0100 


=== Alabama

_Birmingham_ 

1210 S. 20th St. Birmingham, AL 35205 205-558-2222 

_Cullman_ 

202 1st Ave., SE, Suite I Cullman, AL 35055 256-775-2917 

_Dothan_ 

1971 S. Brannon Stand Rd., Suite 1 Dothan, AL 36305 334-794-0492 

_Huntsville_ 

210A Exchange Pl. Huntsville, AL 35806 256-533-1640 

_Mobile_ 

960 S. Schillinger Rd., Suite I Mobile, AL 36695 251-433-5494 

_Montgomery_ 

4750 Woodmere Blvd., Suite D Montgomery, AL 36107 334-273-5530 


=== Alaska

_Anchorage_ 

341 W. Tudor Rd., Suite 209 Anchorage, AK 99503 907-562-0704 


=== Arizona

_Phoenix_ 

4428 N. 12th St. Phoenix, AZ 85014-4585 602-264-1721 

_Prescott_ 

1569 W. Gurley St. Prescott, AZ 86305 928-772-3410 

_Tucson_ 

5151 E. Broadway Blvd., Suite 100 Tucson, AZ 85711 520-888-5353 


=== Arkansas

_Little Rock_ 

510-844-2000 12521 Kanis Rd. 

Little Rock, AR 72211 550 W. Orangethorpe Ave. 


=== California

_Bakersfield_ 

1601 H St., Suite 101 Bakersfield, CA 93301 661-322-2074 

_Culver City_ 

6125 Washington Blvd., 3rd Floor Culver City, CA 90232 310-945-3166 

_Fresno_ 

4201 W. Shaw Ave., Suite 107 Fresno, CA 93722 559-222-8111 

_Long Beach_ 

3363 Linden Ave., Suite A Long Beach, CA 90807 562-216-9242 

_Los Angeles_ 

315 N. La Cadena Dr. Colton, CA 92324 909-825-7280 

_Oakland_ 

1000 Broadway, Suite 625 Oakland, CA 94607 

_Placentia_ 

501-664-7274 Placentia, CA 92870 714-985-8922 

_Sacramento_ 

3075 Beacon Blvd. West Sacramento, CA 95691 916-443-6843 

_San Diego_ 

5050 Murphy Canyon Rd., Suite 110 San Diego, CA 92123 858-496-2131 

_San Jose_ 

1112 S. Bascom Ave. San Jose, CA 95128 408-278-7400 

_Santa Barbara_ 

PO Box 129 Santa Barbara, CA 93101 805-963-8657 

_Stockton_ 

11 S. San Joaquin St., 8th Floor Stockton, CA 95202 209-948-4880 


=== Colorado

_Colorado Springs_ 

25 N. Wahsatch Ave. Colorado Springs, CO 80903 719-636-1155 

_Denver_ 

1020 Cherokee St. Denver, CO 80204-4039 303-758-2100 

_Fort Collins_ 

8020 S. County Rd. 5, #100 Fort Collins, CO 80528 970-484-1348 


=== Connecticut

_Wallingford_ 

706-210-7676 94 S. Turnpike Rd. Wallingford, CT 06492-4322 500 12th St. 


=== Delaware

_Wilmington_ 

60 Reads Way New Castle, DE 19720 302-221-5255 


=== District Of Columbia

_Washington_ 

1411 K St., NW, Suite 1000 Washington, DC 20005-3404 202-393-8000


=== Florida

_Clearwater_ 

2655 McCormick Dr. Clearwater, FL 33759 727-535-5522 

_Jacksonville_ 

4417 Beach Blvd., Suite 202 Jacksonville, FL 32207 904-721-2288 

_Miami_ 

14750 N.W. 77 Ct., Suite 317 Miami Lakes, FL 33016 305-827-5363 

_Orlando_ 

1600 S. Grant St. Longwood, FL 32750 407-621-3300 

_Pensacola_ 

912 E. Gadsden St. Pensacola, FL 32501 850-429-0002 

_Stuart_ 

101 E. Ocean Blvd., Suite 202 Stuart, FL 34994 772-223-1492 

_West Palm Beach_ 

4411 Beacon Circle, Suite 4 West Palm Beach, FL 33407 561-842-1918 


=== Georgia

_Atlanta_ 

503 Oak Pl., Suite 590 Atlanta, GA 30349 404-766-0875 

_Augusta_ 

1227 Augusta West Pkwy., Suite 15 Augusta, GA 30909 

_Columbus_ 

203-269-2700 Columbus, GA 31901 706-324-0712 

_Macon_ 

277 Martin Luther King, Jr. Blvd. Suite 102 Macon, GA 31201-3495 478-742-7999 

_Savannah_ 

6555 Abercorn St., Suite 120 Savannah, GA 31405-5817 912-354-7521 


=== Hawaii

_Honolulu_ 

1132 Bishop St., Suite 615 Honolulu, HI 96813 808-536-6956 


=== Idaho

_Boise_ 

1200 N. Curtis Rd. Boise, ID 83706 208-342-4649 

_Idaho Falls_ 

453 River Pkwy. Idaho Falls, ID 83402 208-523-9754 


=== Illinois

_Chicago_ 

330 N. Wabash Ave., Suite 3120 Chicago, IL 60611-7621 312-832-0500 

_Peoria_ 

112 Harrison St. Peoria, IL 61602 309-688-3741 

_Rockford_ 

401 W. State St., Suite 500 Rockford, IL 61101 815-963-2222 


=== Indiana

_Evansville_ 

3101 N. Green River Rd., Suite 410 Evansville, IN 47715 812-473-0202 

_Fort Wayne_ 

4011 Parnell Ave. Fort Wayne, IN 46805 260-423-4433 

_Indianapolis_ 

151 N. Delaware St., Suite 2020 Indianapolis, IN 46204-2599 317-488-2222 

_Merriville_ 

7863 Broadway, Suite 124 Merriville, IN 46410 219-227-8400 

_Osceola_ 

10775 McKinley Hwy., Suite B Osceola, IN 46561 574-675-9315 


=== Iowa

_Bettendorf_ 

2435 Kimberly Rd., Suite 260 N Bettendorf, IA 52722-4100 563-355-6344 

_Des Moines_ 

505 5th Ave., Suite 950 Des Moines, IA 50309 515-243-8137 


=== Kansas

_Wichita_ 

345 N. Riverview St., Suite 720 Wichita, KS 67203 316-263-3146 


=== Kentucky

_Lexington_ 

1390 Olivia Ln., Suite 100 Lexington, KY 40511 859-259-1008 

_Louisville_ 

844 S. 4th St. Louisville, KY 40203 502-583-6546 


=== Louisiana

_Alexandria_ 

5220-C Rue Verdun Alexandria, LA 71303 318-473-4494 

_Baton Rouge_ 

748 Main St. Baton Rouge, LA 70802 225-346-5222 

_Houma_ 

801 Barrow St., Suite 400 Houma, LA 70360 985-868-3456 

_Lafayette_ 

4007 W. Congress St., Suite B Lafayette, LA 70506 337-981-3497 

_Lake Charles_ 

2309 E. Prien Lake Rd. Lake Charles, LA 70601 337-478-6253 

_Monroe_ 

1900 N. 18th St., Suite 411 Monroe, LA 71201 318-387-4600 

_New Orleans_ 

710 Baronne St., Suite C New Orleans, LA 70113 504-581-6222 

_Shreveport_ 

2006 E. 70th St. Shreveport, LA 71105 318-797-1337 


=== Maryland

_Baltimore_ 

502 S. Sharp St., Suite 1200 Baltimore, MD 21201 410-347-3990 


=== Massachusetts

_Marlborough_ 

290 Donald Lynch Blvd., Suite 102 Marlborough, MA 01752 508-652-4800 

_Worcester_ 

340 Main St., Suite 802 Worcester, MA 01608 508-755-2548 


=== Michigan

_Detroit_ 

26777 Central Park Blvd., Suite 100 Southfield, MI 48076-4163 248-223-9400 

_Grand Rapids_ 

40 Pearl St., NW, Suite 354 Grand Rapids, MI 49503 616-774-8236 


=== Minnesota

_Minneapolis/ St. Paul_ 

220 S. River Ridge Circle Burnsville, MN 55337 651-699-1111 


=== Mississippi

_Jackson_ 

505 Avalon Way, Suite B Jackson, MS 39047 601-398-1700 


=== Missouri

_Kansas City_ 

8080 Ward Pkwy., Suite 401 Kansas City, MO 64114 816-421-7800 

_Springfield_ 

430 S. Glenstone Ave., Suite A Springfield, MO 65802 417-862-4222 

_St. Louis_ 

211 N. Broadway, Suite 2060 St. Louis, MO 63102 314-645-3300 


=== Nebraska

_Lincoln_ 

3633 O St., Suite 1 Lincoln, NE 68510 402-436-2345 

_Omaha_ 

11811 P St. Omaha, NE 68137 402-391-7612 


=== Nevada

_Las Vegas_ 

6040 S. Jones Blvd.Las Vegas, NV 89118702-320-4500 

_Reno_ 

4834 Sparks Blvd., Suite 102Sparks, NV 89436775-322-0657 


=== New Hampshire

_Concord_ 

48 Pleasant St.Concord, NH 03301603-224-1991 


=== New Jersey

_Trenton_ 

1700 Whitehorse-Hamilton Square Rd. Suite D-5 Trenton, NJ 08690-3596 609-588-0808 


=== New Mexico

_Albuquerque_ 

2625 Pennsylvania St., NE, Suite 2050 Albuquerque, NM 87110-3658 505-346-0110 

_Farmington_ 

308 N. Locke Ave. Farmington, NM 87401-5855 505-326-6501 


=== New York

_Buffalo_ 

100 Bryant Woods S Amherst, NY 14228 716-881-5222 

_Farmingdale_ 

399 Conklin St., Suite 300 Farmingdale, NY 11735 212-533-6200 

_New York_ 

30 E. 33rd St., 12th Floor New York, NY 10016 212-533-6200 

_Tarrytown_ 

150 White Plains Rd., Suite 107 Tarrytown, NY 10591-5521 212-533-6200 


=== North Carolina

_Asheville_ 

112 Executive Park Asheville, NC 28801 828-253-2392 

_Charlotte_ 

13860 Ballantyne Corporate Place Suite 225 Charlotte, NC 28277 704-927-8611 

_Greensboro_ 

3608 W. Friendly Ave. Suite 212 Greensboro, NC 27410-4895 336-852-4240 

_Raleigh_ 

5540 Munford Rd., Suite 130 Raleigh, NC 27612-2655 919-277-4222 

_Winston-Salem_ 

500 W. 5th St., Suite 202 Winston-Salem, NC 27101-2728 336-725-8348 


=== Ohio

_Akron_ 

222 W. Market St. Akron, OH 44303 330-253-4590 

_Canton_ 

1434 Cleveland Ave., NW Canton, OH 44703 330-454-9401 

_Cincinnati_ 

Seven W. 7th St., Suite 1600 Cincinnati, OH 45202 513-421-3015 

_Cleveland_ 

2800 Euclid Ave., 4th Floor Cleveland, OH 44115 216-241-7678 

_Columbus_ 

1169 Dublin Rd. Columbus, OH 43215-1005 614-486-6336 

_Dayton_ 

15 W. 4th St., Suite 300 Dayton, OH 45402-1830 937-222-5825 

_Lima_ 

219 N. McDonel St. Lima, OH 45801 419-223-7010 

_Toledo_ 

Integrity Place 7668 King's Pointe Rd. Toledo, OH 43617 419-531-3116 

_Youngstown_ 

International Towers 25 Market St. Youngstown, OH 44503 330-744-3111 


=== Oklahoma

_Oklahoma City_ 

17 S. Dewey St. Oklahoma City, OK 73102-2400 405-239-6081 

_Tulsa_ 

1722 S. Carson Ave., Suite 3200 Tulsa, OK 74119 918-492-1266 


=== Oregon

_Lake Oswego_ 

4004 S.W. Kruse Way Place, Suite 375 Lake Oswego, OR 97035 503-212-3022 


=== Pennsylvania

_Bethlehem_ 

50 W. North St. Bethlehem, PA 18018-3907 610-866-8780 

_Harrisburg_ 

1337 N. Front St. Harrisburg, PA 17102 717-364-3250 

_Philadelphia_ 

1880 John F. Kennedy Blvd., Suite 1330 Philadelphia, PA 19103 215-985-9313 

_Pittsburgh_ 

400 Holiday Dr., Suite 220 Pittsburgh, PA 15220 412-456-2700 

_Scranton/Wilkes-Barre_ 

4099 Birney Ave. Moosic, PA 18507 570-342-5100 


=== Puerto Rico

_San Juan_ 

530 Avenida De La Constitucion, #206 San Juan, PR 00901 787-289-8710 


=== South Carolina

_Columbia_ 

2442 Devine St. Columbia, SC 29205 803-254-2525 

_Conway_ 

1121 3rd Ave. Conway, SC 29526 843-488-2227 

_Greenville_ 

408 N. Church St., Suite C Greenville, SC 29601-2164 864-242-5052 


=== South Dakota

_Sioux Falls_ 

300 N. Phillips Ave., #100 Sioux Falls, SD 57104 605-271-2066 


=== Tennessee

_Chattanooga_ 

1010 Market St., Suite 200 Chattanooga, TN 37402 423-266-6144 

_Clarksville_ 

214 Main St. Clarksville, TN 37040 931-503-2222 

_Columbia_ 

502 N. Garden St., Suite 201 Columbia, TN 38401 931-388-9222 

_Cookeville_ 

18 N. Jefferson St. Cookeville, TN 38501 931-520-0008 

_Franklin_ 

367 Riverside Dr., Suite 110 Franklin, TN 37064 615-242-4222 

_Knoxville_ 

255 N. Peters Rd., Suite A Knoxville, TN 37923 865-692-1600 

_Memphis_ 

3693 Tyndale Dr. Memphis, TN 38125 901-759-1300 

_Murfreesboro_ 

530 Uptown Square Murfreesboro, TN 37129 615-242-4222 

_Nashville_ 

201 4th Ave. N., Suite 100 Nashville, TN 37219 615-242-4222 


=== Texas

_Abilene_ 

3300 S. 14th St., Suite 307 Abilene, TX 79605-5052 325-691-1533 

_Amarillo_ 

720 S. Tyler St., Suite B112 Amarillo, TX 79101 806-379-6222 

_Austin_ 

1005 La Posada Dr. Austin, TX 78752 512-445-2911 

_Beaumont_ 

550 Fannin St., Suite 100 Beaumont, TX 77701-2011 409-835-5348 

_College Station_ 

418 Tarrow St. College Station, TX 77840-1822 979-260-2222 

_Corpus Christi_ 

719 S. Shoreline, Suite 304 Corpus Christi, TX 78401 361-852-4949 

_Dallas_ 

1601 Elm St., Suite 3838 Dallas, TX 75201-3093 214-220-2000 

_El Paso_ 

720 Arizona Ave. El Paso, TX 79902 915-577-0191 

_Fort Worth_ 

101 Summit Ave., Suite 707 Fort Worth, TX 76102-5978 817-332-7585 

_Harker Heights_ 

445 E. Central Texas Expy., Suite 1 Harker Heights, TX 76548 254-699-0694 

_Houston_ 

1333 W. Loop South, Suite 1200 Houston, TX 77027 713-868-9500 

_Longview_ 

2401 Judson Rd., #102 Longview, TX 75605 903-758-3222 

_Lubbock_ 

3333 66th St. Lubbock, TX 79413-5711 806-763-0459 

_Midland_ 

10100 Liberator Ln. Midland, TX 79711 432-563-1880 

_San Angelo_ 

3134 Executive Dr., Suite A San Angelo, TX 76904 325-949-2989 

_San Antonio_ 

425 Soledad St., Suite 500 San Antonio, TX 78205 210-828-9441 

_Tyler_ 

3600 Old Bullard Rd. Building 1, Suite 101 Tyler, TX 75701 903-581-5704 

_Weslaco_ 

502 E. Expressway 83, Suite C Weslaco, TX 78596 956-968-3678 

_Wichita Falls_ 

4245 Kemp Blvd., Suite 1012 Wichita Falls, TX 76308 940-691-1172 


=== Utah

_Salt Lake City_ 

5673 S. Redwood Rd., Suite 22 Salt Lake City, UT 84123-5322 801-892-6009 


=== Virginia

_Norfolk_ 

586 Virginian Dr. Norfolk, VA 23505 757-531-1300 

_Richmond_ 

720 Moorefield Park Dr., Suite 300 Richmond, VA 23236 804-648-0016 

_Roanoke_ 

5115 Bernard Dr., Suite 202 Roanoke, VA 24018 540-342-3455 


=== Washington

_DuPont_ 

1000 Station Dr., Suite 222 DuPont, WA 98327 206-431-2222 

_Spokane_ 

152 S. Jefferson St., Suite 200 Spokane, WA 99201 509-455-4200 


=== West Virginia

_Charleston_ 

1018 Kanawha Blvd. E, Suite 301 Charleston, WV 25301 304-345-7502 


=== Wisconsin

_Milwaukee_ 

10101 W. Greenfield Ave., Suite 125 West Allis, WI 53214 414-847-6000 

