[[corporate_consumer_contacts]]

== Corporate Consumer Contacts


.Contacting Corporate Consumer Affairs Departments
****
 The following directory lists the addresses and phone  numbers for hundreds of corporations. Many companies  have a consumer affairs department that handles consumer  questions and concerns. Consumer affairs offices are set  up within companies because they want to hear from you.  If you do not find the company you are looking for, try  checking your public libraries for the following resources: 


*  _The Standard and Poor&rsquo;s Register of Corporations, Directors and Executives_ 


*  _Trade Names Directory_ 


*  _Standard Directory of Advertisers_ 


*  _Dun and Bradstreet Directory_ 

To identify the name of a company that manufactures a  specific product, check the product label and other documents  given to you at the time of your purchase. The Thomas Register  of American Manufacturers, another resource available at many  public libraries, might also be helpful. It lists the  manufacturers of thousands of products.

 If you have a complaint about an item or service, it is  usually best to go back to the seller BEFORE you contact  the companies in this directory. Follow up with a letter,  phone call, or e-mail message to the consumer affairs  department of the company to let it know about your  complaint and whether the seller was able to resolve your  problem. You may express your complaint on a company&rsquo;s  social media profile to get quick attention to your problem. 


****



=== A

 AAMCO Transmissions, Inc. 

 Consumer Affairs 201 Gibraltar Rd. Horsham, PA 19044 Toll free: 1-800-523-0401 

 link:$$http://www.aamco.com$$[www.aamco.com] 

 Abbott Nutrition Products Division 

 Consumer Relations 625 Cleveland Ave. Columbus, OH 43215-1754 Toll free: 1-800-227-5767 

 link:$$http://www.abbottnutrition.com$$[www.abbottnutrition.com] 

 ABC, Inc. 

 Audience Relations Dept. 500 S. Buena Vista St. Burbank, CA 91521-4551 818-460-7477 

 link:$$http://www.abc.com$$[www.abc.com] 

 Abercrombie &amp; Fitch 

 Customer Service 200 Abercrombie Way New Albany, OH 43054 614-219-5380 Toll free: 1-866-681-3115 

 pass:[<email>abercrombie@abercrombie.com</email>] 

 link:$$http://www.abercrombie.com$$[www.abercrombie.com] 

 Accor North America 

 PO Box 326 Worthington, OH 43085 Toll free: 1-800-557-3435 

 link:$$http://www.accor-na.com$$[www.accor-na.com] 

 Adidas USA 

 Customer Service 5055 N. Greeley Ave. Portland, OR 97217 Toll free: 1-800-448-1796 

 pass:[<email>consumer.relations@adidas.com</email>] 

 link:$$http://www.adidas.com$$[www.adidas.com] 

 Adobe Systems, Inc. 

 345 Park Ave. San Jose, CA 95110-2704 408-536-6000 Toll free: 1-800-833-6687 (Customer and Technical Support) 

 link:$$http://www.adobe.com$$[www.adobe.com] 

 Aetna, Inc. 

 151 Farmington Ave. Hartford, CT 06156 860-273-0123 

 link:$$http://www.aetna.com$$[www.aetna.com] 

 Aflac 

 1932 Wynnton Rd. Columbus, GA 31999 Toll free: 1-800-992-3522 

 link:$$http://www.aflac.com$$[www.aflac.com] 

 AirTran Airways 

 Customer Relations 1800 Phoenix Blvd., Suite 104 Atlanta, GA 30349 Toll free: 1-866-247-2428 Toll free: 1-800-965-2107 ext. 8900 (Baggage) 

 link:$$http://www.airtran.com$$[www.airtran.com] 

 Alamo Rent A Car 

 Customer Care 8420 St. John Industrial Dr. Saint Louis, MO 63114 Toll free: 1-800-445-5664 TTY: 1-800-522-9292 

 link:$$http://www.alamo.com$$[www.alamo.com] 

 Alaska Airlines 

 Customer Care PO Box 24948-SEAGT Seattle, WA 98124-0948 Toll free: 1-800-654-5669 Toll free: 1-877-815-8253 (Baggage) TTY: 1-800-682-2221 

 link:$$http://www.alaskaair.com$$[www.alaskaair.com] 

 Alberto Culver Company 

 See: Unilever 

 link:$$http://www.alberto.com$$[www.alberto.com] 

 Albertsons, Inc. 

 Customer Service 157 S. Howard St. Spokane, WA 99201 208-395-6200 Toll free: 1-877-932-7948 (Customer Service) 

 link:$$http://www.albertsons.com$$[www.albertsons.com] 

 Alcon Laboratories, Inc. 

 Technical Consumer Affairs 6201 South Fwy. Fort Worth, TX 76134 Toll free: 1-800-862-5266 

 pass:[<email>consumeraffairs.ft.worth@alconlabs.com</email>] 

 link:$$http://www.alconlabs.com$$[www.alconlabs.com] 

 Allied Van Lines, Inc. 

 Customer Service 700 Oakmont Ln. Westmont, IL 60559 Toll free: 1-800-470-2851 

 pass:[<email>custsvc@alliedvan.com</email>] 

 link:$$http://www.allied.com$$[www.allied.com] 

 Allstate Insurance Company 

 PO Box 12055 1819 Electric Rd., SW Roanoke, IL 24018 847-402-5000 Toll free: 1-800-255-7828 (Claims) 

 link:$$http://www.allstate.com$$[www.allstate.com] 

 Amana Appliances 

 Customer Service 553 Benson Rd. Benton Harbor, MI 49022 Toll free: 1-866-616-2664 

 link:$$http://www.amana.com$$[www.amana.com] 

 Amazon.com, Inc. 

 Customer Service PO Box 81226 Seattle, WA 98108-1226 Toll free: 1-866-216-1072 

 link:$$http://www.amazon.com$$[www.amazon.com] 

 AMC Entertainment, Inc. 

 PO Box 725489 Atlanta, GA 31139-9923 

 link:$$http://www.amctheatres.com$$[www.amctheatres.com] 

 America Online, Inc. 

 Member Services 22000 AOL Way Dulles, VA 20166 Toll free: 1-800-827-6364 TTY: 1-800-759-3323 

 link:$$http://www.aol.com$$[www.aol.com] 

 American Airlines, Inc. 

 Customer Relations PO Box 619612 Mail Drop 2400 Dallas/Fort Worth Airport, TX 75261-9612 817-967-2000 Toll free: 1-800-535-5225 (Baggage) 

 link:$$http://www.aa.com$$[www.aa.com] 

 American Automobile Association (AAA) 

 Member Relations 1000 AAA Dr., Mail Space 61 Heathrow, FL 32746 407-444-8402 Toll free: 1-866-636-2377 

 link:$$http://www.aaa.com$$[www.aaa.com] 

 American Eagle Outfitters 

 Customer Service 150 Thorn Hill Dr. Warrendale, PA 15086 Toll free: 1-888-232-4535 

 pass:[<email>custserv@ae.com</email>] 

 link:$$http://www.ae.com$$[www.ae.com] 

 American Express Company 

 Customer Service PO Box 981540 El Paso, TX 79998-1540 Toll free: 1-800-528-4800 Toll free: 1-877-297-4438 (Gift Cards) TTY: 1-800-221-9950 

 link:$$http://www.americanexpress.com$$[www.americanexpress.com] 

 American Girl 

 PO Box 620497 Middleton, WI 53562-0497 Toll free: 1-800-360-1861 

 pass:[<email>im_cs@americangirl.com</email>] 

 link:$$http://www.americangirl.com$$[www.americangirl.com] 

 American Greetings Corporation 

 Consumer Relations One American Rd. Cleveland, OH 44144 Toll free: 1-800-777-4891 

 pass:[<email>consumer.relations@amgreetings.com</email>] 

 link:$$http://www.americangreetings.com$$[www.americangreetings.com] 

 American Tourister 

 See: Samsonite Corporation Toll free: 1-800-765-2247 Toll free: 1-800-262-8282 (Warranty and Repair) 

 pass:[<email>Questions@AmericanTourister.com</email>] 

 link:$$http://www.americantourister.com$$[www.americantourister.com] 

 Amtrak 

 Customer Relations 60 Massachusetts Ave., NE Washington, DC 20002 Toll free: 1-800-872-7245 TTY: 1-800-523-6590 

 link:$$http://www.amtrak.com$$[www.amtrak.com] 

 Amway Corporation 

 Customer Service - North American Business Region 7575 Fulton St., E Ada, MI 49355-0001 Toll free: 1-800-253-6500 Toll free: 1-800-529-8772 (Personalized Health) TTY: 1-800-548-3878 

 link:$$http://www.amway.com$$[www.amway.com] 

 Andersen Windows, Inc. 

 Window Care Call Center 100 4th Ave., N Bayport, MN 55003-1096 Toll free: 1-888-888-7020 (Service) 

 link:$$http://www.andersenwindows.com$$[www.andersenwindows.com] 

 Angie&rsquo;s List 

 1030 E. Washington St. Indianapolis, IN 46202 Toll free: 1-888-888-5478 

 link:$$http://www.angieslist.com$$[www.angieslist.com] 

 Anheuser-Busch, Inc. 

 Customer Relationship Group One Busch Pl. St. Louis, MO 63118 Toll free: 1-800-342-5283 

 link:$$http://www.anheuser-busch.com$$[www.anheuser-busch.com] 

 Anthem 

 2015 Staples Mills Rd. Richmond, VA 23230 804-354-7000 

 link:$$http://www.anthem.com$$[www.anthem.com] 

 Apple Computer, Inc. 

 One Infinite Loop Cupertino, CA 95014 408-996-1010 Toll free: 1-800-676-2775 (Customer Service) Toll free: 1-800-275-2273 (Technical Support) TTY: 1-877-204-3930 

 link:$$http://www.apple.com$$[www.apple.com] 

 Applebee&rsquo;s 

 8140 Ward Pkwy. Kansas City, MO 64114 Toll free: 1-888-592-7753 

 link:$$http://www.applebees.com$$[www.applebees.com] 

 Arby&rsquo;s Restaurant Group, Inc. 

 1155 Perimeter Center W, 12th Floor Atlanta, GA 30338 678-514-4100 

 pass:[<email>customerfeedback@arbys.com</email>] 

 link:$$http://www.arbys.com$$[www.arbys.com] 

 Atlas World Group, Inc. 

 Customer Service 1212 Saint George Rd. Evansville, IN 47711-2364 Toll free: 1-800-638-9797 

 link:$$http://www.atlasvanlines.com$$[www.atlasvanlines.com] 

 AT&amp;T, Inc. 

 Customer Relations 175 E. Houston St. San Antonio, TX 78205 210-821-4105 Toll free: 1-800-464-7928 (Wireless Customer Service) 

 link:$$http://www.att.com$$[www.att.com] 

 Avis Rent-A-Car System 

 Toll free: 1-800-352-7900 TTY: 1-800-331-2323 

 pass:[<email>custserv@avis.com</email>] 

 link:$$http://www.avis.com$$[www.avis.com] 

 Avon Products, Inc. 

 Customer Service 1345 Avenue of the Americas New York, NY 10105 212-282-7000 Toll free: 1-800-367-2866 Toll free: 1-800-445-2866 (Product Information) 

 link:$$http://www.avon.com$$[www.avon.com] 


=== B

 Bacardi USA, Inc. 

 Consumer Affairs 2701 S. Le Jeune Rd. Coral Gables, FL 33134 Toll free: 1-800-222-2734 

 link:$$http://www.bacardi.com$$[www.bacardi.com] 

 Bally Total Fitness Corporation 

 Member Services PO Box 96241 Washington, DC 20090-6241 Toll free: 1-866-402-2559 

 link:$$http://www.ballyfitness.com$$[www.ballyfitness.com] 

 Banana Republic 

 Customer Services 5900 N. Meadows Dr. Grove City, OH 43123 Toll free: 1-888-277-8953 TTY: 1-888-906-1345 

 pass:[<email>custserv@bananarepublic.com</email>] 

 link:$$http://www.bananarepublic.com$$[www.bananarepublic.com] 

 Bank of America Corporation 

 PO Box 25118 Tampa, FL 33622-5118 Toll free: 1-800-432-1000 TTY: 1-800-288-4408 

 link:$$http://www.bankofamerica.com$$[www.bankofamerica.com] 

 Barnes &amp; Noble 

 Toll free: 1-800-843-2665 

 link:$$http://www.bn.com$$[www.bn.com] 

 Baskin-Robbins 

 Toll free: 1-800-859-5339 

 pass:[<email>support@baskinrobbins.com</email>] 

 link:$$http://www.baskinrobbins.com$$[www.baskinrobbins.com] 

 Bassett Furniture 

 3525 Fairystone Park Hwy. PO Box 626 Bassett, VA 24055 Toll free: 1-877-308-7485 (Baby Furniture) Toll free: 1-800-525-7070 

 pass:[<email>juvenile@bassettfurniture.com</email>] 

 link:$$http://www.bassettfurniture.com$$[www.bassettfurniture.com] 

 Bayer HealthCare, LLC 

 Consumer Care 36 Columbia Rd. PO Box 1910 Morristown, NJ 07962-1910 Toll free: 1-800-331-4536 

 link:$$http://www.bayercare.com$$[www.bayercare.com] 

 Becton, Dickinson and Company 

 Customer Service One Becton Dr., Mail Code 376 Franklin Lakes, NJ 07417 201-847-6800 Toll free: 1-888-237-2762 

 link:$$http://www.bd.com$$[www.bd.com] 

 Beech-Nut Nutrition Corporation 

 Consumer Affairs 100 Hero Dr. Amsterdam, NY 12010 314-436-7667 Toll free: 1-800-233-2468 

 pass:[<email>beech-nut@beech-nut.com</email>] 

 link:$$http://www.beechnut.com$$[www.beechnut.com] 

 Beiersdorf, Inc. 

 Consumer Relations 45 Danbury Rd. Wilton, CT 06897 Toll free: 1-800-227-4703 

 link:$$http://www.beiersdorf.us$$[www.beiersdorf.us] 

 Bellisio Foods, Inc. 

 Consumer Affairs PO Box 16630 Duluth, MN 55816 

 pass:[<email>info@bellisiofoods.com</email>] 

 link:$$http://www.bellisiofoods.com$$[www.bellisiofoods.com] 

 Ben &amp; Jerrys Homemade, Inc. 

 Consumer Services 30 Community Dr. South Burlington, VT 05403-6828 802-846-1500 

 link:$$http://www.benjerry.com$$[www.benjerry.com] 

 Benihana, Inc. 

 Customer Relations 8750 N.W. 36th St., Suite 300 Miami, FL 33178 Toll free: 1-800-327-3369 

 pass:[<email>CustomerService@benihana.com</email>] 

 link:$$http://www.benihana.com$$[www.benihana.com] 

 Best Buy Company, Inc. 

 Customer Care PO Box 9312 Minneapolis, MN 55440-9312 Toll free: 1-888-237-8289 

 link:$$http://www.bestbuy.com$$[www.bestbuy.com] 

 Best Western International, Inc. 

 Customer Service PO Box 10203 Phoenix, AZ 85064 Toll free: 1-800-528-1238 TTY: 1-800-528-2222 

 pass:[<email>customerservice@bestwestern.com</email>] 

 link:$$http://www.bestwestern.com$$[www.bestwestern.com] 

 BIC Corporation 

 Consumer Affairs One Bic Way, Suite 1 Shelton, CT 06484-6299 Toll free: 1-800-546-1111 

 link:$$http://www.bicworld.com$$[www.bicworld.com] 

 Big Lot Stores, Inc. 

 Customer Service 300 Phillipi Rd. Columbus, OH 43228-5311 Toll free: 1-800-877-1253 

 pass:[<email>talk2us@biglots.com</email>] 

 link:$$http://www.biglots.com$$[www.biglots.com] 

 Birds Eye Foods, Inc. 

 Consumer Relations See: Pinnacle Foods Group, LLC Toll free: 1-800-563-1786 (Birds Eye, Freshlike, Nalley or Bersteins Products) Toll free: 1-800-270-2743 (Other Brands) 

 pass:[<email>consumerinsights@pinnacle.speedymail.com</email>] 

 link:$$http://www.birdseyefoods.com$$[www.birdseyefoods.com] 

 Bissell Homecare, Inc. 

 Customer Service PO Box 3606 Grand Rapids, MI 49501 Toll free: 1-800-237-7691 

 link:$$http://www.bissell.com$$[www.bissell.com] 

 BJ&rsquo;s Wholesale Club, Inc. 

 Member Care 25 Research Dr. Westborough, MA 01581 Toll free: 1-800-257-2582 

 link:$$http://www.bjs.com$$[www.bjs.com] 

 Black &amp; Decker, Inc. 

 Customer Service 701 E. Joppa Rd. Joppa, MD 21286 410-716-3900 Toll free: 1-800-544-6986 

 link:$$http://www.blackanddecker.com$$[www.blackanddecker.com] 

 Blockbuster Entertainment Corporation 

 Customer Care 3000 Redbud Blvd. McKinney, TX 75270 Toll free: 1-866-692-2789 (Blockbuster Online) Toll free: 1-800-406-6843 (In-Store) 

 pass:[<email>online.consumerrelations@blockbuster.com</email>] 

 link:$$http://www.blockbuster.com$$[www.blockbuster.com] 

 Bloomingdales, Inc. 

 Customer Service PO Box 8215 Mason, OH 45040 Toll free: 1-800-777-0000 

 link:$$http://www.bloomingdales.com$$[www.bloomingdales.com] 

 Blue Cross and Blue Shield Association (BCBSA) 

 Consumer Affairs 1310 G St., NW Washington, DC 20005 202-626-4780 

 link:$$http://www.bcbs.com$$[www.bcbs.com] 

 Bob Evans Farms, Inc. 

 Consumer Relations 3776 S. High St. Columbus, OH 43207 Toll free: 1-800-939-2338 

 link:$$http://www.bobevans.com$$[www.bobevans.com] 

 Bojangles Restaurants, Inc. 

 Customer Relations 9432 Southern Pine Blvd. Charlotte, NC 28273 Toll free: 1-888-300-4265 

 link:$$http://www.bojangles.com$$[www.bojangles.com] 

 BP Corporation 

 Consumer Relations 28301 Ferry Rd. Warrenville, IL 60555 Toll free: 1-800-333-3991 

 pass:[<email>bpconsum@bp.com</email>] 

 link:$$http://www.bp.com$$[www.bp.com] 

 Bridgestone Retail Operations, LLC 

 Consumer Affairs PO Box 6397 Bloomingdale, IL 60108 Toll free: 1-800-367-3872 

 pass:[<email>firestone_consumer_affairs@inspyresolutions.com</email>] 

 link:$$http://www.firestonecompleteautocare.com$$[www.firestonecompleteautocare.]com 

 Brinker International 

 6820 LBJ Freeway Dallas, TX 75240 972-980-9917 

 link:$$http://www.brinker.com$$[www.brinker.com] 

 Brio Tuscan Grill 

 Guest Feedback 777 Goodale Blvd., Suite 100 Columbus, OH 43212 Toll free: 1-888-452-7286 

 link:$$http://www.brioitalian.com$$[www.brioitalian.com] 

 Bristol-Myers Squibb Company 

 Customer Relations 345 Park Ave. New York, NY 10154 Toll free: 1-800-332-2056 

 pass:[<email>drug.information@bms.com</email>] 

 link:$$http://www.bms.com$$[www.bms.com] 

 British Airways 

 Customer Relations PO Box 300686 Jamaica, NY 11430-0686 Toll free: 1-800-247-9297 Toll free: 1-800-828-8144 (Baggage Claims) Toll free: 1-800-403-0882 (Online Support) TTY: 1-866-393-0961 

 link:$$http://www.britishairways.com$$[www.britishairways.com] 

 Brown Shoe Company, Inc. 

 Consumer Care 8300 Maryland Ave. St. Louis, MO 63105 Toll free: 1-800-766-6465 

 pass:[<email>info@brownshoe.com</email>] 

 link:$$http://www.brownshoe.com$$[www.brownshoe.com] 

 Brown-Forman Beverages Worldwide 

 Consumer Support 850 Dixie Hwy. Louisville, KY 40210 Toll free: 1-800-753-4567 

 link:$$http://www.brown-forman.com$$[www.brown-forman.com] 

 Buca di Beppo 

 Guest Services 4700 Millenia Blvd., Suite 400 Orlando, FL 32839 

 pass:[<email>famiglia@bucainc.com</email>] 

 link:$$http://www.bucadibeppo.com$$[www.bucadibeppo.com] 

 Budget Rent A Car System, Inc. 

 Customer Service Six Sylvan Way Parsippany, NJ 07054 Toll free: 1-800-214-6094 TTY: 1-800-826-5510 

 link:$$http://www.budget.com$$[www.budget.com] 

 Bulova Corporation 

 Customer Relations One Bulova Ave. Woodside, NY 11377 Toll free: 1-800-228-5682 

 pass:[<email>service@bulova.com</email>] 

 link:$$http://www.bulova.com$$[www.bulova.com] 

 Burger King Corporation 

 Consumer Relations Department 5505 Blue Lagoon Dr. Miami, FL 33126 Toll free: 1-866-394-2493 

 link:$$http://www.bk.com$$[www.bk.com] 

 Burlington Coat Factory Direct Corporation 

 Customer Relations Department 1830 Route 130 N Burlington, NJ 08016 Toll free: 1-888-223-2628 

 link:$$http://www.burlingtoncoatfactory.com$$[www.burlingtoncoatfactory.com] 

 Bush Brothers Company 

 Consumer Relations PO Box 52330 Knoxville, TN 37950-2330 Toll free: 1-800-590-3797 

 pass:[<email>letters@bushbros.com</email>] 

 link:$$http://www.bushbeans.com$$[www.bushbeans.com] 


=== C

 Calvin Klein 

 See: Phillips-Van Heusen Toll free: 1-866-214-6694 Toll free: 1-866-513-0513 (Website) 

 link:$$http://www.calvinklein.com$$[www.calvinklein.com] 

 Campbell Soup Company 

 Consumer Affairs One Campbell Pl. Camden, NJ 08103-1701 Toll free: 1-800-257-8443 

 link:$$http://www.campbellsoup.com$$[www.campbellsoup.com] 

 Canon USA, Inc. 

 One Canon Plaza Lake Success, NY 11042-1198 Toll free: 1-800-652-2666 TTY: 1-866-251-3752 

 link:$$http://www.usa.canon.com$$[www.usa.canon.com] 

 Capital One 

 General Correspondence PO Box 30285 Salt Lake City, UT 84130-0285 1-800-955-7070 TTY: 1-800-206-7986 

 pass:[<email>webinfo@capitalone.com</email>] 

 link:$$http://www.capitalone.com$$[www.capitalone.com] 

 Captain D&rsquo;s Seafood 

 1717 Elm Hill Pike, Suite A-1 Nashville, TN 37210 Toll free: 1-800-314-4819 

 link:$$http://www.captainds.com$$[www.captainds.com] 

 Carfax, Inc. 

 Consumer Affairs 5860 Trinity Pkwy., Suite 600 Centerville, VA 20120 703-218-0340 

 pass:[<email>carfaxwebsupport@carfax.com</email>] 

 link:$$http://www.carfax.com/help$$[www.carfax.com/help] 

 Carnival Cruise Lines 

 Guest Relations 3655 N.W. 87th Ave. Miami, FL 33178-2428 Toll free: 1-800-929-6400 

 pass:[<email>guestcare@carnival.com</email>] 

 link:$$http://www.carnival.com$$[www.carnival.com] 

 Carrier Air Conditioning Company 

 Customer Relations PO Box 4808, Carrier Pkwy. Syracuse, NY 13221-4808 Toll free: 1-800-227-7437 

 link:$$http://www.residential.carrier.com$$[www.residential.carrier.com] 

 Carvel Corporation 

 Retail Stores/Food Service 301 Congress Ave., Suite 1100 Austin, TX 78701 Toll free: 1-800-322-4848 

 link:$$http://www.carvel.com$$[www.carvel.com] 

 Casio, Inc. 

 570 Mt. Pleasant Ave. Dover, NJ 07801 973-361-5400 Toll free: 1-800-706-2534 (Repairs) Toll free: 1-800-435-7732 (Technical Support) 

 pass:[<email>memberservices@casio.com</email>] 

 link:$$http://www.casio.com$$[www.casio.com] 

 Casual Male Retail Group 

 Customer Service 555 Turnpike St. Canton, MA 02021 Toll free: 1-855-746-7395 

 pass:[<email>info@casualmale.com</email>] 

 link:$$http://www.casual-male-big-and-tall.destinationxl.com/mens-big-and-tall-store/$$[www.casual-male-big-and-tall.destinationxl.com] 

 The CBS Television Network 

 Audience Services 524 W. 52nd St. New York, NY 10019-6198 212-975-3247 

 pass:[<email>audsvcs@cbs.com</email>] 

 link:$$http://www.cbs.com$$[www.cbs.com] 

 Chanel, Inc. 

 Consumer Relations Nine W. 57th St., 44th Floor New York, NY 10019 Toll free: 1-800-550-0005 

 pass:[<email>consumerrelations@chanelusa.com</email>] 

 link:$$http://www.chanel.com$$[www.chanel.com] 

 Chase Bank 

 (J.P. Morgan Chase Bank) 

 PO Box 36520 Louisville, KY 40233-6520 212-270-6000 (Corporate) Toll free: 1-800-935-9935 (Checking and Savings) TTY: 1-800-242-7383 

 link:$$http://www.chase.com$$[www.chase.com] 

 Chattem, Inc. 

 Consumer Affairs PO Box 22219 Chattanooga, TN 37409 Toll free: 1-888-442-4464 

 link:$$http://www.chattem.com$$[www.chattem.com] 

 Check ‘n Go 

 7755 Montgomery Rd., Suite 400 Cincinnati, OH 45236 Toll free: 1-888-372-9329 

 pass:[<email>comments@checkngo.com</email>] 

 link:$$http://www.checkngo.com$$[www.checkngo.com] 

 The Cheesecake Factory 

 26901 Malibu Hills Rd. Calabasas Hills, CA 91301 818-871-3000 

 link:$$http://www.thecheesecakefactory.com$$[www.thecheesecakefactory.com] 

 Chevron Corporation 

 Consumer Connection Center PO Box 4000 Bellaire, TX 77402-4000 

 link:$$http://www.chevron.com$$[www.chevron.com] 

 Chick-fil-A, Inc. 

 Customer Feedback PO Box 500367 Atlanta, GA 31150 404-765-8000 Toll free: 1-866-232-2040 

 link:$$http://www.chick-fil-a.com$$[www.chick-fil-a.com] 

 Children&rsquo;s Place 

 Customer Service 500 Plaza Dr. Secaucus, NJ 07094 Toll free: 1-877-752-2387 

 link:$$http://www.childrensplace.com$$[www.childrensplace.com] 

 Chili&rsquo;s Grill and Bar 

 See: Brinker International Toll free: 1-800-983-4637 (Guest Relations) 

 link:$$http://www.chilis.com$$[www.chilis.com] 

 Chipotle Mexican Grill, Inc. 

 1401 Wynkoop St., Suite 500 Denver, CO 80202 303-595-4000 

 pass:[<email>customerservice@chipotle.com</email>] 

 link:$$http://www.chipotle.com$$[www.chipotle.com] 

 Choice Hotels 

 Guest Relations 6811 E. Mayo Blvd., Suite 100 Phoenix, AZ 85054 Toll free: 1-800-300-8800 

 link:$$http://www.choicehotels.com$$[www.choicehotels.com] 

 Church &amp; Dwight Company, Inc. 

 Consumer and Professional Relations 469 N. Harrison St. Princeton, NJ 08540 609-683-5900 Toll free: 1-800-524-1328 

 link:$$http://www.churchdwight.com$$[www.churchdwight.com] 

 Citibank, Inc. 

 Client Services 100 Citibank Dr. San Antonio, TX 78245-9004 Toll free: 1-800-627-3999 (Banking) Toll free: 1-800-950-5114 (Credit cards) TTY: 1-800-788-0002 

 link:$$http://www.citibank.com$$[www.citibank.com] 

 The Clorox Company 

 Consumer Services Mail Stop 2334 1221 Broadway Oakland, CA 94612-1888 Toll free: 1-800-835-4523 (GLAD) Toll free: 1-800-227-1860 (Household Cleaners) Toll free: 1-800-292-2200 (Laundry Brands) Toll free: 1-800-426-6228 (Insecticides) 

 link:$$http://www.thecloroxcompany.com$$[www.thecloroxcompany.com] 

 The Coca-Cola Company 

 Industry and Consumer Affairs PO Box 1734 Atlanta, GA 30301 Toll free: 1-800-438-2653 

 link:$$http://www.thecocacolacompany.com$$[www.thecocacolacompany.com] 

 Coldwell Banker Real Estate Corporation 

 Customer Service One Campus Dr. Parsippany, NJ 07054 Toll free: 1-877-373-3829 

 link:$$http://www.coldwellbanker.com$$[www.coldwellbanker.com] 

 The Colgate-Palmolive Company 

 Consumer Affairs 300 Park Ave. New York, NY 10022 Toll free: 1-800-468-6502 

 pass:[<email>colgate-palmolive_consumer_affairs@colpal.com</email>] 

 link:$$http://www.colgate.com$$[www.colgate.com] 

 Colonial Penn Life Insurance 

 Customer Service 399 Market St. Philadelphia, PA 19181 Toll free: 1-877-877-8052 (General Questions) Toll free: 1-800-523-9100 (Customer Service and Claims) 

 link:$$http://www.colonialpenn.com$$[www.colonialpenn.com] 

 Combe, Inc. 

 Consumer Resources 1101 Westchester Ave. White Plains, NY 10604-3597 Toll free: 1-800-431-2610 

 link:$$http://www.combe.com$$[www.combe.com] 

 Comcast Corporation 

 One Comcast Center Philadelphia, PA 19103 Toll free: 1-800-266-2278 Toll free: 1-800-934-6489 (Xfinity) 

 link:$$http://www.comcast.com$$[www.comcast.com] 

 ConAgra Foods 

 Consumer Affairs One ConAgra Dr. Omaha, NE 68102 Toll free: 1-800-722-1344 

 pass:[<email>consumeraffairs@conagrafoods.com</email>] 

 link:$$http://www.conagrafoods.com$$[www.conagrafoods.com] 

 Conair Cuisinart Corporation 

 Consumer Affairs 150 Milford Rd. East Windsor, NJ 08520 203-351-9000 Toll free: 1-800-326-6247 (Personal Care) Toll free: 1-800-334-4031 (Oral Care) Toll free: 1-800-726-0190 

 pass:[<email>feedback@conair.com</email>] 

 link:$$http://www.conair.com$$[www.conair.com] 

 Costco Wholesale Corporation 

 Member Service PO Box 34331 Seattle, WA 98124 Toll free: 1-800-774-2678 Toll free: 1-800-955-2292 (Online Members) 

 link:$$http://www.costco.com$$[www.costco.com] 

 Coty Inc. 

 Consumer Affairs 118 American Rd. Morris Plains, NJ 10016 Toll free: 1-800-715-4023  Toll free: 1-800-953-5080 (Sally Hansen, N.Y.C., and LaCross brands) 

 link:$$http://www.coty.com$$[www.coty.com] 

 Cox Communications 

 1550 W. Deer Valley Rd. Phoenix, AZ 85027 

 link:$$http:ww2.cox.com$$[ww2.cox.com] 

 craigslist, Inc. 

 222 Sutter St. San Francisco, CA 94108 

 link:$$http://www.craigslist.org$$[www.craigslist.org] 

 Crate and Barrel 

 Customer Service Department 1860 W. Jefferson Ave. Naperville, IL 60540-3918 Toll free: 1-800-967-6696 

 pass:[<email>customer_service@crateandbarrel.com</email>] 

 link:$$http://www.crateandbarrel.com$$[www.crateandbarrel.com] 

 Crayola, LLC 

 Consumer Affairs PO Box 431 Easton, PA 18044-0431 Toll free: 1-800-272-9652 

 link:$$http://www.crayola.com$$[www.crayola.com] 

 Cricket Wireless 

 See: Leap Wireless International Toll free: 1-800-274-2538 

 link:$$http://www.mycricket.com$$[www.mycricket.com] 

 Crowne Plaza 

 See: InterContinental Hotels Group, PLC Toll free: 1-800-465-2680 

 link:$$http://www.crowneplaza.com$$[www.crowneplaza.com] 

 Curves International 

 100 Ritchie Rd. Waco, TX 76712 Toll free: 1-800-848-1096 

 link:$$http://www.curves.com$$[www.curves.com] 

 CVS Corporation 

 Customer Relations Department One CVS Dr. Woonsocket, RI 02895 401-765-1500 Toll free: 1-800-746-7287 Toll free: 1-888-607-4287 (Website) 

 pass:[<email>customercare@cvs.com</email>] 

 link:$$http://www.cvs.com$$[www.cvs.com] 


=== D

 Dairy Queen Corporation 

 Customer Relations 7505 Metro Blvd. Minneapolis, MN 55439 952-830-0200 

 link:$$http://www.dairyqueen.com$$[www.dairyqueen.com] 

 The Dannon Company, Inc. 

 Consumer Response Center PO Box 90296 Allentown, PA 18109-0296 Toll free: 1-877-326-6668 

 link:$$http://www.dannon.com$$[www.dannon.com] 

 Darden Restaurants 

 PO Box 695011 Orlando, FL 32859-5011 407-245-4000 

 pass:[<email>dardeninfo@darden.com</email>] 

 link:$$http://www.darden.com$$[www.darden.com] 

 Days Inns Worldwide, Inc. 

 PO Box 4090 Aberdeen, SD 57401 Toll free: 1-800-441-1618 

 link:$$http://www.daysinn.com$$[www.daysinn.com] 

 Dean &amp; DeLuca 

 Customer Care 4115 E. Harry St. Wichita, KS 67218 316-821-3200 Toll free: 1-800-221-7714 

 pass:[<email>customercare@deandeluca.com</email>] 

 link:$$http://www.deandeluca.com$$[www.deandeluca.com] 

 Del Monte Foods Company 

 Consumer Affairs PO Box 80 Pittsburgh, PA 15230-0080 415-247-3000 Toll free: 1-800-543-3090 

 link:$$http://www.delmonte.com$$[www.delmonte.com] 

 Dell, Inc. 

 Customer Service One Dell Way Round Rock, TX 78682 Toll free: 1-800-624-9897 (Customer Service) Toll free: 1-866-243-9297 (Technical Support) TTY: 1-877-335-5889 

 link:$$http://www.dell.com$$[www.dell.com] 

 Delta Air Lines, Inc. 

 Customer Care PO Box 20980 Department 980 Atlanta, GA 30320-2980 404-773-0305 404-209-3434 (Disability assistance) Toll free: 1-800-325-8224 (Baggage) 

 link:$$http://www.delta.com$$[www.delta.com] 

 Delta Faucets Company 

 55 E. 111th St. Indianapolis, IN 46280 317-848-1812 Toll free: 1-800-345-3358 

 pass:[<email>customerservice@deltafaucet.com</email>] 

 link:$$http://www.deltafaucet.com$$[www.deltafaucet.com] 

 Denny&rsquo;s Corporation 

 Call Center 203 E. Main St. P-8-6 Spartanburg, SC 29319 Toll free: 1-800-733-6697 (Customer Service) 

 link:$$http://www.dennys.com$$[www.dennys.com] 

 Dial Corporation 

 See: The Henkel Corporation Toll free: 1-800-258-3425 

 link:$$http://www.dialsoap.com$$[www.dialsoap.com] 

 Diamond Foods, Inc. 

 Consumer Affairs 1050 S. Diamond St. Stockton, CA 95205-7087 209-467-6000 

 link:$$http://www.diamondfoods.com$$[www.diamondfoods.com] 

 Dick&rsquo;s Sporting Goods 

 345 Court St. Coraopolis, PA 15108 Toll free: 1-877-846-9997 

 pass:[<email>customersupport@dickssportinggoods.com</email>] 

 link:$$http://www.dickssportinggoods.com$$[www.dickssportinggoods.com] 

 Dillard&rsquo;s, Inc. 

 Customer Service Department PO Box 486 Little Rock, AR 72203 501-376-5200 Toll free: 1-800-345-5273 TTY: 1-800-444-1732 

 pass:[<email>questions@dillards.com</email>] 

 link:$$http://www.dillards.com$$[www.dillards.com] 

 Diners Club International 

 Customer Service PO Box 6101 Carol Stream, IL 60197-6101 Toll free: 1-800-234-6377 

 link:$$http://www.dinersclubus.com$$[www.dinersclubus.com] 

 DIRECTV Enterprises, Inc. 

 PO Box 6550 Greenwood Village, CO 80155-6550 Toll free: 1-800-531-5000 TTY: 1-800-779-4388 

 link:$$http://www.DIRECTV.com$$[www.DIRECTV.com] 

 Discover Financial Services, Inc. 

 Card Customer Service PO Box 30943 Salt Lake City, UT 84130-0943 224-405-0900 (Headquarters) 801-902-3100 Toll free: 1-800-347-2683 TTY: 1-800-347-7449 

 link:$$http://www.discoverfinancial.com$$[www.discoverfinancial.com] 

 Dish Network 

 Toll free: 1-888-333-3474 

 pass:[<email>feedback@customermail.dishnetwork.com</email>] 

 link:$$http://www.dishnetwork.com$$[www.dishnetwork.com] 

 Dole Food Company, Inc. 

 Consumer Center PO Box 5700 Thousand Oaks, CA 91359-5700 Toll free: 1-800-356-3111 

 pass:[<email>Dole.Consumer.Center@dole.com</email>] 

 link:$$http://www.dole.com$$[www.dole.com] 

 Dollar Rent A Car, Inc. 

 Customer Service 2W2 PO Box 33167 Tulsa, OK 74153-1167 918-669-3000 Toll free: 1-800-800-5252 (Customer Service) 

 pass:[<email>rhelpdesk@dollar.com</email>] 

 link:$$http://www.dollar.com$$[www.dollar.com] 

 Domino&rsquo;s Pizza, Inc. 

 Customer Service 30 Frank Lloyd Wright Dr. PO Box 997 Ann Arbor, MI 48106 734-930-3030 Toll free: 1-888-366-4667 

 link:$$http://www.dominos.com$$[www.dominos.com] 

 Doubletree 

 See: Hilton Hospitality, Inc. Toll free: 1-800-222-8733 TTY: 1-800-368-1133 

 link:$$http://www.doubletree.com$$[www.doubletree.com] 

 Dr. Pepper/Snapple Group, Inc. 

 Consumer Relations PO Box 869077 Plano, TX 75086-9077 972-673-7000 Toll free: 1-800-696-5891 

 link:$$http://www.drpeppersnapplegroup.com$$[www.drpeppersnapplegroup.com] 

 DSW 

 Customer Service 810 DSW Dr. Columbus, OH 43219 Toll free: 1-866-379-7463 

 link:$$http://www.dsw.com$$[www.dsw.com] 

 Dunkin Donuts 

 Consumer Care 130 Royall St. Canton, MA 02021 Toll free: 1-800-859-5339 

 link:$$http://www.dunkindonuts.com$$[www.dunkindonuts.com] 

 DuPont Company 

 Corporate Information Center Chestnut Run Plaza 705/GS38 PO Box 80705 Wilmington, DE 19880-0705 Toll free: 1-800-441-7515 

 pass:[<email>info@dupont.com</email>] 

 link:$$http://www.dupont.com$$[www.dupont.com] 

 Duracell North America 

 Consumer Relations Berkshire Corporate Park Bethel, CT 06801 Toll free: 1-800-551-2355 

 link:$$http://www.duracell.com$$[www.duracell.com] 


=== E

E. &amp; J. Gallo Winery 

 Consumer Relations 600 Yosemite Blvd. Modesto, CA 95354-2760 Toll free: 1-877-687-9463 

 pass:[<email>consumerrelations@ejgallo.com</email>] 

 link:$$http://www.gallo.com$$[www.gallo.com] 

 Eagle Family Foods 

 Consumer Response One Strawberry Ln. Orrville, OH 44667 Toll free: 1-888-656-3245 

 link:$$http://www.eaglebrand.com$$[www.eaglebrand.com] 

 Eastman Kodak Company 

 Kodak Information Center/Consumer Contact Center  343 State St.  Rochester, NY 14650  Toll free: 1-800-235-6325  (Digital Cameras, Printer Docks, Photo Printers)  Toll free: 1-800-242-2424 

 link:$$http://www.kodak.com$$[www.kodak.com] 

 e-Bay, Inc. 

 2065 Hamilton Ave. San Jose, CA 95125 Toll free: 1-800-322-9266 

 link:$$http://www.eBay.com$$[www.eBay.com] 

 Eddie Bauer, Inc. 

 Customer Satisfaction Center PO Box 7001 Groveport, OH 43125 Toll free: 1-800-426-8020 TTY: 1-800-462-6757 

 pass:[<email>CustomerCare@csc.eddiebauer.com</email>] 

 link:$$http://www.eddiebauer.com$$[www.eddiebauer.com] 

 eHarmony 

 Customer Care PO Box 3640 Santa Monica, CA 90408 Toll free: 1-800-951-2023 

 link:$$http://www.eharmony.com$$[www.eharmony.com] 

 The Electrolux Group 

 Consumer Assistance Center 2715 Washington Rd. Augusta, GA 30909 Toll free: 1-877-435-3287 

 link:$$http://www.electrolux.com$$[www.electrolux.com] 

 Eli Lilly &amp; Company 

 Consumer Communications Lilly Corporate Center Indianapolis, IN 46285 317-276-2000 Toll free: 1-800-545-5979 

 link:$$http://www.lilly.com$$[www.lilly.com] 

 Elizabeth Arden, Inc. 

 Consumer Affairs 309 South St. New Providence, NJ 07974 Toll free: 1-800-326-7337 

 pass:[<email>consumer@elizabetharden.com</email>] 

 link:$$http://www.elizabetharden.com$$[www.elizabetharden.com] 

 Embassy Suites 

 See: Hilton Hospitality, Inc. Toll free: 1-800-362-2779 

 link:$$http://www.embassysuites.com$$[www.embassysuites.com] 

 Enterprise Rent-a-Car 

 600 Corporate Park Dr. Saint Louis, MO 63105-4211 Toll free: 1-800-264-6350 

 pass:[<email>customerservice@enterprise.com</email>] 

 link:$$http://www.enterprise.com$$[www.enterprise.com] 

 Equifax 

 Office of Consumer Affairs PO Box 740241 Atlanta, GA 30374 Toll free: 1-800-685-1111 

 link:$$http://www.equifax.com$$[www.equifax.com] 

 The Estee Lauder Companies, Inc. 

 Consumer Care 767 5th Ave. New York, NY 10153 212-572-4200 Toll free: 1-888-378-3359 

 pass:[<email>consumercare-us@gcc.elc.estee.com</email>] 

 link:$$http://www.elcompanies.com$$[www.elcompanies.com] 

 Ethan Allen, Inc. 

 PO Box 1966 Danbury, CT 06813 Toll free: 1-888-324-3571 

 pass:[<email>orders@ethanallen.com</email>] 

 link:$$http://www.ethanallen.com$$[www.ethanallen.com] 

 The Eureka Company 

 Consumer Service Department PO Box 3900 Peoria, IL 61701 Toll free: 1-800-282-2886 

 link:$$http://www.eureka.com$$[www.eureka.com] 

 Expedia, Inc. 

 Customer Support 333 108th Ave., NE Bellevue, WA 98004 Toll free: 1-800-787-7186 

 link:$$http://www.expedia.com$$[www.expedia.com] 

 Experian 

 National Consumer Assistance Center PO Box 2002 Allen, TX 75013 Toll free: 1-888-397-3742 

 pass:[<email>support@experiandirect.com</email>] 

 link:$$http://www.experian.com$$[www.experian.com] 

 Express Scripts 

 Toll free: 1-800-631-7780 

 link:$$http://www.express-scripts.com$$[www.express-scripts.com] 

 Exxon Mobil 

 Customer Relations PO Box 1049 Buffalo, NY 14240-1049 Toll free: 1-800-243-9966 

 link:$$http://www.exxonmobil.com$$[www.exxonmobil.com] 


=== F

 Facebook, Inc. 

 1601 S. California Ave. Palo Alto, CA 94304 650-543-4800 

 pass:[<email>info@facebook.com</email>] 

 link:$$http://www.facebook.com$$[www.facebook.com] 

 Fairfield Inn 

 See: Marriott International, Inc. Toll free: 1-800-721-7033 

 link:$$http://www.fairfieldinn.com$$[www.fairfieldinn.com] 

 Farmers Insurance 

 4680 Wilshire Blvd. Los Angeles, CA 90010 Toll free: 1-800-435-7764 TTY: 1-888-891-1660 

 link:$$http://www.farmers.com$$[www.farmers.com] 

 FedEx Corporation 

 Customer Relations 3875 Airways Blvd. Module H3 Department 4634 Memphis, TN 38116 Toll free: 1-800-463-3339 

 link:$$http://www.fedex.com$$[www.fedex.com] 

 Fingerhut Direct Marketing, Inc. 

 Customer Service 6250 Ridgewood Rd. St. Cloud, MN 56303 Toll free: 1-800-208-2500 

 pass:[<email>customerservice@fingerhut.com</email>] 

 link:$$http://www.fingerhut.com$$[www.fingerhut.com] 

 Fisher-Price 

 Consumer Affairs 636 Girard Ave. East Aurora, NY 14052 716-687-3000 Toll free: 1-800-432-5437 TTY: 1-800-382-7470 

 pass:[<email>fpconaff@fisher-price.com</email>] 

 link:$$http://www.fisher-price.com$$[www.fisher-price.com] 

 Florsheim, Inc. 

 Customer Service 333 W. Estabrook Blvd. Glendale, WI 53212 Toll free: 1-866-454-0449 

 pass:[<email>us.consumers@florsheim.com</email>] 

 link:$$http://www.florsheim.com$$[www.florsheim.com] 

 Flowers Foods, Inc. 

 1919 Flowers Circle Thomasville, GA 31757 229-226-9110 

 link:$$http://www.flowersfoods.com$$[www.flowersfoods.com] 

 Food Lion, Inc. 

 Customer Relations PO Box 1330 Salisbury, NC 28145-1330 Toll free: 1-800-210-9569 

 link:$$http://www.foodlion.com$$[www.foodlion.com] 

 Forever 21 

 Customer Service 3880 N. Mission Rd. Los Angeles, CA 90031 213-741-5100 Toll free: 1-888-494-3837 

 link:$$http://www.forever21.com$$[www.forever21.com] 

 Fortune Brands 

 Corporate Affairs Department 520 Lake Cook Rd. Deerfield, IL 60015 847-484-4400 

 pass:[<email>mail@fortunebrands.com</email>] 

 link:$$http://www.fortunebrands.com$$[www.fortunebrands.com] 

 Frigidaire Home Products 

 2715 Washington Rd. Augusta, GA 30909 Toll free: 1-800-374-4432 

 link:$$http://www.frigidaire.com$$[www.frigidaire.com] 

 Frito-Lay 

 Consumer Affairs PO Box 660634 Dallas, TX 75266-6234 972-334-7000 Toll free: 1-800-352-4477 

 link:$$http://www.fritolay.com$$[www.fritolay.com] 

 Frontier Airlines, Inc. 

 Customer Relations 7001 Tower Rd. Denver, CO 80249-7312 Toll free: 1-800-432-1359 TTY: 1-800-872-3608 

 link:$$http://www.frontierairlines.com$$[www.frontierairlines.com] 

 FTD, Inc. 

 Customer Service 3113 Woodcreek Dr. Downers Grove, IL 60515 630-719-7756 Toll free: 1-800-736-3383 

 link:$$http://www.ftd.com$$[www.ftd.com] 

 Fuji Photo Film USA, Inc. 

 Consumer Information Service Center 1100 King George Post Edison, NJ 08837 Toll free: 1-800-800-3854 

 link:$$http://www.fujifilm.com$$[www.fujifilm.com] 


=== G

 Gap, Inc. 

 Customer Relations 100 Gap Online Dr. Grove City, OH 43123-8605 Toll free: 1-800-427-7895 TTY: 1-888-906-1104 

 pass:[<email>custserv@gap.com</email>] 

 link:$$http://www.gap.com$$[www.gap.com] 

 Gateway, Inc. 

 Customer Service PO Box 6137 Temple, TX 76503 

 link:$$http://www.gateway.com$$[www.gateway.com] 

 GEICO 

 One GEICO Plaza  Washington, DC 20076  Toll free: 1-877-418-1312 (Car)  Toll free: 1-888-395-1200 (Home)  Toll free: 1-888-532-5433 (Life)  TTY: 1-800-833-8255 

 link:$$http://www.geico.com$$[www.geico.com] 

 General Electric Company 

 3135 Easton Turnpike Fairfield, CT 06828 203-373-2211 Toll free: 1-800-626-2005 

 link:$$http://www.ge.com$$[www.ge.com] 

 General Mills, Inc. 

 Consumer Services PO Box 9452 Minneapolis, MN 55440 Toll free: 1-800-248-7310 

 link:$$http://www.generalmills.com$$[www.generalmills.com] 

 Georgia-Pacific Corporation 

 Consumer Affairs 133 Peachtree St., NE Atlanta, GA 30303 Toll free: 1-800-283-5547 (Consumer Products) TTY: 1-800-283-5547 ext. 5 

 link:$$http://www.gp.com$$[www.gp.com] 

 Gerber Products Company 

 Consumer Affairs 445 State St. Fremont, MI 49413-0001 Toll free: 1-800-284-9488 

 link:$$http://www.gerber.com$$[www.gerber.com] 

 Giant Food, Inc. 

 8301 Professional Pl., Suite 115 Landover, MD 20785 301-341-4322 Toll free: 1-888-469-4426 TTY: 301-200-8995 

 link:$$http://www.giantfood.com$$[www.giantfood.com] 

 GlaxoSmithKline Consumer Healthcare 

 Consumer Information PO Box 13398 Five Moore Dr. Research Triangle Park, NC 27709 412-200-4000 Toll free: 1-888-825-5249 (Prescription Drugs) Toll free: 1-800-245-1040 (Non-Prescription) 

 pass:[<email>consumer.communications@gsk.com</email>] 

 link:$$http://www.gsk.com$$[www.gsk.com] 

 The Golden Grain Company 

 PO Box 049003 Chicago, IL 60604-9003 Toll free: 1-800-421-2444 

 link:$$http://www.ricearoni.com$$[www.ricearoni.com] 

 Gold&rsquo;s Gym International 

 Customer Care Department 125 E. John Carpenter Fwy., Suite 1300 Irving, TX 75062 214-574-4653 

 link:$$http://www.goldsgym.com$$[www.goldsgym.com] 

 Goodrich Corporation 

 Consumer Relations Department PO Box 19001 Greenville, SC 29602-9001 Toll free: 1-877-788-8899 

 link:$$http://www.bfgoodrichtires.com$$[www.bfgoodrichtires.com] 

 The Goodyear Tire Rubber Company 

 Department 728 1144 E. Market St. Akron, OH 44316-0001 330-769-2121 Toll free: 1-800-321-2136 

 pass:[<email>consumer_relations@goodyear.com</email>] 

 link:$$http://www.goodyear.com$$[www.goodyear.com] 

 Google.com 

 1600 Amphitheatre Pkwy. Mountain View, CA 94043 650-253-0000 

 link:$$http://www.google.com$$[www.google.com] 

 Graco Children&rsquo;s Products, Inc. 

 Consumer Services 150 Oaklands Blvd. Exton, PA 19341 Toll free: 1-800-345-4109 

 link:$$http://www.gracobaby.com$$[www.gracobaby.com] 

 Greyhound Lines, Inc. 

 PO Box 660362 Dallas, TX 75266-0362 214-849-8000 214-849-6246 (Baggage) Toll free: 1-800-231-2222 (Fares/Schedules) TTY: 1-800- 345-3109 

 link:$$http://www.greyhound.com$$[www.greyhound.com] 

 Guess? Inc. 

 Customer Service 1444 S. Alameda St. Los Angeles, CA 90021 213-765-3100 Toll free: 1-877-444-8377 

 link:$$http://www.guess.com$$[www.guess.com] 

 Guinness Company 

 801 Main Ave. Norwalk, CT 06851 203-229-2100 Toll free: 1-800-521-1591 

 pass:[<email>guinness@consumer-care.net</email>] 

 link:$$http://www.guinness.com$$[www.guinness.com] 


=== H

 H &amp; R Block, Inc. 

 Customer Support One H &amp; R Block Way Kansas City, MO 64105 Toll free: 1-800-472-5625 

 link:$$http://www.hrblock.com$$[www.hrblock.com] 

 Hallmark Cards, Inc. 

 Consumer Affairs PO Box 419034 Mail Drop #216 Kansas City, MO 64141 Toll free: 1-800-425-5627 

 link:$$http://www.hallmark.com$$[www.hallmark.com] 

 Hampton Inn &amp; Suites 

 See: Hilton Hospitality, Inc. Toll free: 1-800-426-7866 

 link:$$http://www.hamptoninn.com$$[www.hamptoninn.com] 

 Hanes Hosiery 

 Consumer Relations PO Box 3013 Winston-Salem, NC 27102 Toll free: 1-800-225-4872 

 link:$$http://www.haneshosiery.com$$[www.haneshosiery.com] 

 Harry &amp; David 

 Customer Service 2500 South Pacific Hwy. Medford, OR 97501-2675 541-864-2121 Toll free: 1-877-322-1200 

 pass:[<email>service@harryanddavid.com</email>] 

 link:$$http://www.harryanddavid.com$$[www.harryanddavid.com] 

 Hartz Mountain Corporation 

 Consumer Affairs 400 Plaza Dr. Secaucus, NJ 07094 Toll free: 1-800-275-1414 

 link:$$http://www.hartz.com$$[www.hartz.com] 

 Hasbro, Inc. 

 Consumer Affairs PO Box 200 Dept. C-847 Pawtucket, RI 02862-0200 401-727-6899 Toll free: 1-800-255-5516 

 pass:[<email>customersupport@hasbro.com</email>] 

 link:$$http://www.hasbro.com$$[www.hasbro.com] 

 Heinz North America 

 Consumer Resource Center/ Consumer Affairs PO Box 57 Pittsburgh, PA 15230 Toll free: 1-800-255-5750 

 pass:[<email>heinzconsumeraffairs@us.hjheinz.com</email>] 

 link:$$http://www.heinz.com$$[www.heinz.com] 

 Henkel Consumer Goods 

 19001 N. Scottsdale Rd. Scottsdale, AZ 85255 480-754-3425 Toll free: 1-800-258-3425 

 link:$$http://www.henkelna.com$$[www.henkelna.com] 

 Hershey Food Corporation 

 Consumer Relations 100 Crystal A Dr. Hershey, PA 17033 Toll free: 1-800-468-1714 

 link:$$http://www.hersheys.com$$[www.hersheys.com] 

 Hertz Corporation 

 Customer Relations PO Box 26120 Oklahoma City, OK 73126 Toll free: 1-800-654-4173 TTY: 1-800-654-2280 

 link:$$http://www.hertz.com$$[www.hertz.com] 

 Hewlett-Packard Company 

 3000 Hanover St. Bldg. 6A. Mail Stop 1247 Palo Alto, CA 94304 650-857-1501 Toll free: 1-800-474-6836 

 link:$$http://www.hp.com$$[www.hp.com] 

 Hillshire Brands 

 Consumer Affairs PO Box 3901 Neenah, WI 61612 Toll free: 1-800-323-7117 (Desserts) Toll free: 1-800-925-3326 (Meats) 

 link:$$http://www.hillshirebrands.com$$[www.hillshirebrands.com] 

 Hilton Garden Inn 

 See: Hilton Hospitality, Inc. Toll free: 1-877-782-9444 

 link:$$http://www.hiltongardeninn.com$$[www.hiltongardeninn.com] 

 Hilton Hospitality, Inc. 

 Guest Assistance 755 Crossover Ln. Memphis, TN 38117 901-374-5000 Toll free: 1-800-445-8667 TTY: 1-800-368-1133 

 link:$$http://www.hilton.com$$[www.hilton.com] 

 Hitachi America Ltd. 

 Customer Services PO Box 99652 Troy, MI 48099 

 pass:[<email>customerservice.ce@hal.hitachi.com</email>]  Toll free: 1-800-448-2244 

 Holiday Inn/Holiday Inn Express 

 See: InterContinental Hotels Group Toll free: 1-800-465-4329 

 link:$$http://www.holiday-inn.com$$[www.holiday-inn.com] 

 Home Depot, Inc. 

 Customer Care 2455 Paces Ferry Rd. Atlanta, GA 30339-4024 Toll free: 1-800-466-3337 Toll free: 1-800-430-3376 (Website Questions) 

 pass:[<email>customercare@homedepot.com</email>] 

 link:$$http://www.homedepot.com$$[www.homedepot.com] 

 Home Goods 

 See: TJX Companies, Inc. Toll free: 1-800-888-0776 

 link:$$http://www.homegoods.com$$[www.homegoods.com] 

 Home Shopping Network 

 Customer Service PO Box 9090 Clearwater, FL 33758 Toll free: 1-800-284-3900 (Phone Orders) Toll free: 1-800-933-2887 (Online Orders) 

 link:$$http://www.hsn.com$$[www.hsn.com] 

 Homewood Suites 

 See: Hilton Hospitality Inc. Toll free: 1-800-225-5466 

 link:$$http://www.homewoodsuites.com$$[www.homewoodsuites.com] 

 Hoover Company 

 TTI Floor Care North America 7005 Cochran Rd. Glenwillow, OH 44139 Toll free: 1-800-944-9200 

 link:$$http://www.hoover.com$$[www.hoover.com] 

 Hormel Foods Company 

 Consumer Affairs One Hormel Pl. Austin, MN 55912 Toll free: 1-800-523-4635 

 link:$$http://www.hormel.com$$[www.hormel.com] 

 Howard Johnson, Inc. 

 PO Box 4090 Aberdeen, SD 57401 Toll free: 1-800-544-9881 

 link:$$http://www.hojo.com$$[www.hojo.com] 

 Humana, Inc. 

 PO Box 14601 Lexington, KY 40512-4601 502-580-1000 Toll free: 1-800-448-6262 

 link:$$http://www.humana.com$$[www.humana.com] 

 Hyatt Hotels &amp; Resorts 

 Consumer Affairs 9805 Q St. Omaha, NE 68127 402-592-6465 Toll free: 1-800-323-7249 

 link:$$http://www.hyatt.com$$[www.hyatt.com] 


=== I

 IBM Corporation 

 One New Orchard Rd. Armonk, NY 10504-1722 914-499-1900 Toll free: 1-800-426-4968 (Customer Service) TTY: 1-800-426-3383 

 pass:[<email>askibm@vnet.ibm.com</email>] 

 link:$$http://www.ibm.com$$[www.ibm.com] 

 Ikea 

 Customer Relations 420 Alan Wood Rd. Conshohocken, PA 19428 Toll free: 1-800-434-4532 

 link:$$http://www.ikea.com$$[www.ikea.com] 

 Intel 

 Consumer Relations 2200 Mission College Blvd. Santa Clara, CA 95054 408-765-8080 (Headquarters) 

 link:$$http://www.intel.com$$[www.intel.com] 

 InterContinental Hotels Group PLC 

 Guest Relations PO Box 30321 Salt Lake City, UT 84130-321 Toll free: 1-800 621-0555 

 link:$$http://www.ihgplc.com$$[www.ihgplc.com] 


=== J

 Jack In The Box 

 Guest Relations 9330 Balboa Ave. San Diego, CA 92123-1516 858-571-2121 Toll free: 1-800-955-5225 

 link:$$http://www.jackinthebox.com$$[www.jackinthebox.com] 

 Jackson Hewitt Tax Service, Inc. 

 Three Sylvan Way, Suite 301 Parsippany, NJ 07054 Toll free: 1-800-234-1040 

 link:$$http://www.jacksonhewitt.com$$[www.jacksonhewitt.com] 

 JanSport, Inc. 

 2601 Harbor Bay Pkwy. Alameda, CA 94577 501-614-4000 Toll free: 1-800-558-3600 

 link:$$http://www.jansport.com$$[www.jansport.com] 

 Janssen Pharmaceuticals, Inc. 

 PO Box 200 Titusville, NJ 08560 Toll free: 1-800-526-7736 

 link:$$http://www.ortho-mcneil.com$$[www.ortho-mcneil.com] 

 Jarden Consumer Solutions, Inc. 

 Consumer Affairs 2381 Executive Center Dr. Boca Raton, FL 34331 Toll free: 1-800-458-8407 

 link:$$http://www.jardencs.com$$[www.jardencs.com] 

 JCPenney Company, Inc. 

 Corporate Customer Relations PO Box 10001 Dallas, TX 75301-7311 Toll free: 1-800-322-1189 

 link:$$http://www.jcpenney.com$$[www.jcpenney.com] 

 J. Crew 

 Customer Relations One Ivy Crescent Lynchburg, VA 24513-1001 Toll free: 1-800-562-0258 

 pass:[<email>contactus@jcrew.com</email>] 

 link:$$http://www.jcrew.com$$[www.jcrew.com] 

 Jenny Craig, Inc. 

 Customer Care 5770 Fleet St. Carlsbad, CA 92008 760-696-4000 (Headquarters) Toll free: 1-800-536-6922 

 pass:[<email>WebCustomerService@jennycraig.com</email>] 

 link:$$http://www.jennycraig.com$$[www.jennycraig.com] 

 JetBlue Airways Corporation 

 Customer Relations PO Box 17435 Salt Lake City, UT 84117-7435 Toll free: 1-800-538-2583 TTY: 1-800-336-5530 

 pass:[<email>promise@jetblue.com</email>] 

 link:$$http://www.jetblue.com$$[www.jetblue.com] 

 Jiffy Lube International, Inc. 

 Customer Service PO Box 4427 Houston, TX 77210-4458 Toll free: 1-800-344-6933 

 link:$$http://www.jiffylube.com$$[www.jiffylube.com] 

 John Hancock Financial Services, Inc. 

 601 Congress St. Boston, MA 02210-2805 617-572-6000 Toll free: 1-800-732-5543 TTY: 1-800-832-5282 

 link:$$http://www.johnhancock.com$$[www.johnhancock.com] 

 Johnson &amp; Johnson Consumer Products, Inc. 

 PO Box 726 Langhorne, PA 19047-0726 732-524-0400 Toll free: 1-800-526-3967 

 link:$$http://www.jnj.com$$[www.jnj.com] 

 Johnson Publishing Company, Inc. 

 820 S. Michigan Ave. Chicago, IL 60605 312-322-9200 

 link:$$http://www.johnsonpublishing.com$$[www.johnsonpublishing.com] 

 Just Born, Inc 

 Consumer Relations 1300 Stefko Blvd. Bethlehem, PA 18017 610-867-7568 Toll free: 1-888-645-3453 

 pass:[<email>consumerrelations@justborn.com</email>] 

 link:$$http://www.justborn.com$$[www.justborn.com] 

 JVC Company of America 

 Customer Care 1700 Valley Rd. Wayne, NJ 07470 Toll free: 1-800-252-5722 

 link:$$http://www.jvcservice.com$$[www.jvcservice.com] 


=== K

 Kao Brands Company 

 Consumer Relations Department 2535 Spring Grove Ave. Cincinnati, OH 45214 

 link:$$http://www.kaobrands.com$$[www.kaobrands.com] 

 Kawasaki Motor Corporation, USA 

 Consumer Services PO Box 25252 Santa Ana, CA 92799-5252 949-460-5688 

 link:$$http://www.kawasaki.com$$[www.kawasaki.com] 

 Kellogg Company 

 Consumer Affairs PO Box CAMB Battle Creek, MI 49016 Toll free: 1-800-962-1413 

 link:$$http://www.kelloggcompany.com$$[www.kelloggcompany.com] 

 KFC 

 PO Box 725489 Atlanta, GA 31139 Toll free: 1-800-225-5532 

 link:$$http://www.kfc.com$$[www.kfc.com] 

 Kimberly-Clark Corporation 

 Consumer Services Dept. INT PO Box 2020 Neenah, WI 54957-2020 Toll free: 1-888-525-8388 

 link:$$http://www.kimberly-clark.com$$[www.kimberly-clark.com] 

 The Kirby Company 

 Customer Relations 1920 W. 114th St. Cleveland, OH 44102 Toll free: 1-800-494-8586 

 pass:[<email>consumer@kirbywhq.com</email>] 

 link:$$http://www.kirby.com$$[www.kirby.com] 

 KitchenAid 

 See: Whirlpool Corporation Toll free: 1-800-422-1230 (Large Appliances) Toll free: 1-800-541-6390 (Small Appliances) 

 link:$$http://www.kitchenaid.com$$[www.kitchenaid.com] 

 Kmart Corporation 

 Customer Service Toll free: 1-866-562-7848 

 pass:[<email>help@customerservice.kmart.com</email>] 

 link:$$http://www.kmart.com$$[www.kmart.com] 

 Kohler Company 

 444 Highland Dr. Kohler, WI 53044 920-457-4441 Toll free: 1-800-456-4537 

 link:$$http://www.kohler.com$$[www.kohler.com] 

 Kohls Corporation 

 Customer Service N56 W. 17000 Ridgewood Dr. Menomonee Falls, WI 53051 262-703-7000 Toll free: 1-866-887-8884 Toll free: 1-800-564-5740 (Credit) 

 pass:[<email>customer.service@kohls.com</email>] 

 link:$$http://www.kohls.com$$[www.kohls.com] 

 Kona Grill, Inc. 

 7150 E. Camelback Rd., #220 Scottsdale, AZ 85251 480-922-8100 

 link:$$http://www.konagrill.com$$[www.konagrill.com] 

 Kraft Foods, Inc. 

 Consumer Relations One Kraft Court Glenview, IL 60025 Toll free: 1-877-535-5666 

 link:$$http://www.kraftfoods.com$$[www.kraftfoods.com] 

 Kroger Company 

 1014 Vine St. Cincinnati, OH 45202-1100 Toll free: 1-800-576-4377 

 link:$$http://www.kroger.com$$[www.kroger.com] 


=== L

 LA Fitness International, LLC 

 Member Services PO Box 54170 Irvine, CA 92619-1300 

 link:$$http://www.lafitness.com$$[www.lafitness.com] 

 Land O&rsquo;Lakes, Inc. 

 Consumer Affairs PO Box 64050 St. Paul, MN 55164-9784 Toll free: 1-800-328-4155 Toll free: 1-800-328-9680 (Corporate) 

 link:$$http://www.landolakes.com$$[www.landolakes.com] 

 Lands End, Inc. 

 Customer Service One Lands End Ln. Dodgeville, WI 53595 Toll free: 1-800-963-4816 TTY: 1-800-541-3459 

 pass:[<email>landsend@landsend.com</email>] 

 link:$$http://www.landsend.com$$[www.landsend.com] 

 Lane Bryant 

 777 S. State Rd. 7 Margate, FL 33068 Toll free: 1-866-886-4731 

 link:$$http://www.lanebryant.com$$[www.lanebryant.com] 

 Lane Furniture 

 Consumer Services PO Box 1627 Hwy. 145 South Tupelo, MS 38802 Toll free: 1-877-405-3745 

 pass:[<email>service@lanefurniture.com</email>] 

 link:$$http://www.lanefurniture.com$$[www.lanefurniture.com] 

 La-Z-Boy, Inc. 

 Consumer Services 1284 N. Telegraph Rd. Monroe, MI 48162-3309 Toll free: 1-800-375-6890 

 pass:[<email>cservice@la-z-boy.com</email>] 

 link:$$http://www.la-z-boy.com$$[www.la-z-boy.com] 

 LeapFrog Enterprises, Inc. 

 Customer Support 6401 Hollis St., Suite 100 Emeryville, CA 94608-1071 Toll free: 1-800-701-5327 Toll free: 1-866-334-5327 (Online Support) 

 pass:[<email>support@leapfrog.com</email>] 

 link:$$http://www.leapfrog.com$$[www.leapfrog.com] 

 Leap Wireless International, Inc. 

 5887 Copley Dr. San Diego, CA 92111 858-882-6000 Toll free: 1-800-274-2538 

 link:$$http://www.leapwireless.com$$[www.leapwireless.com] 

 Lee Jeans 

 Consumer Services 9001 W. 67th St. Merriam, KS 66202 Toll free: 1-800-453-3348 

 link:$$http://www.lee.com$$[www.lee.com] 

 L&rsquo;eggs Products 

 Consumer Services PO Box 3013 Winston-Salem, NC 27102 Toll free: 1-800-925-4872 

 link:$$http://www.leggs.com$$[www.leggs.com] 

 LEGO Systems Inc 

 Consumer Affairs 555 Taylor Rd. PO Box 1138 Enfield, CT 06083-1138 Toll free: 1-800-838-9647 Toll free: 1-877-518-5346 (Shop at Home) 

 link:$$http://www.lego.com$$[www.lego.com] 

 Lennox Industries, Inc. 

 Consumer Affairs PO Box 799900 Dallas, TX 75379 Toll free: 1-800-953-6669 

 link:$$http://www.lennox.com$$[www.lennox.com] 

 LensCrafters 

 4000 Luxottica Pl. Mason, OH 45040 Toll free: 1-877-753-6727 

 link:$$http://www.lenscrafters.com$$[www.lenscrafters.com] 

 Levi Strauss &amp; Company 

 1155 Battery St. San Francisco, CA 94111 Toll free: 1-866-860-8907 

 pass:[<email>customerservice@levisstore.com</email>] 

 link:$$http://www.levi.com$$[www.levi.com] 

 Lexmark International, Inc. 

 740 W. New Circle Rd. Lexington, KY 40550 Toll free: 1-800-539-6275 

 link:$$http://www.lexmark.com$$[www.lexmark.com] 

 LG Electronics, Inc 

 Customer Service PO Box 240007 201 James Record Rd. Huntsville, AL 35813 Toll free: 1-800-243-0000 (Appliances) 

 link:$$http://www.lge.com$$[www.lge.com] 

 Liberty Mutual Insurance Group 

 Customer Service 100 Liberty Way Dover, NH 03820 Toll free: 1-800-398-8924 

 pass:[<email>Liberty.Service@libertymutual.com</email>] 

 link:$$http://www.libertymutual.com$$[www.libertymutual.com] 

 Lillian Vernon Corporation 

 Customer Service PO Box 35980 Colorado Springs, CO 80935-5980 Toll free: 1-800-901-9291 

 pass:[<email>custservice@lillianvernon.com</email>] 

 link:$$http://www.lillianvernon.com$$[www.lillianvernon.com] 

 Limited Brands, Inc. 

 Customer Service Three Limited Pkwy. Columbus, OH 43230 614-415-7000 Toll free: 1-800-945-5088 

 link:$$http://www.limitedbrands.com$$[www.limitedbrands.com] 

 LinkedIn Corporation 

 2029 Stierlin Ct. Mountain View, CA 94043 

 link:$$http://www.linkedin.com$$[www.linkedin.com] 

 Little Tikes 

 Consumer Services 2180 Barlow Rd. Hudson, OH 44236 Toll free: 1-800-321-0183 

 pass:[<email>littletikes.cares@littletikescare.com</email>] 

 link:$$http://www.littletikes.com$$[www.littletikes.com] 

 L.L. Bean, Inc. 

 Dept. CFM Freeport, ME 04033-0001 207-552-3028 Toll free: 1-800-441-5713 TTY: 1-800-545-0090 

 link:$$http://www.llbean.com$$[www.llbean.com] 

 Loehmann&rsquo;s 

 Customer Service 2500 Halsey St. Bronx, NY 10461 1-855-563-4626 

 pass:[<email>customerservice@loehmanns.com</email>] 

 link:$$http://www.loehmanns.com$$[www.loehmanns.com] 

 Longhorn Steakhouse 

 See: Darden Restaurants 407-245-4000 

 link:$$http://www.longhornsteakhouse.com$$[www.longhornsteakhouse.com] 

 Long John Silver&rsquo;s Restaurants, Inc. 

 pass:[<email>LJScares@LJSilvers.com</email>] 

 link:$$http://www.ljsilvers.com$$[www.ljsilvers.com] 

 L&rsquo;Oreal USA 

 575 5th Ave. New York, NY 10017  212-818-1500 (Headquarters)  Toll free: 1-800-322-2036 

 link:$$http://www.lorealusa.com$$[www.lorealusa.com] 

 Lowe&rsquo;s 

 Customer Care PO Box 1111 North Wilkesboro, NC 28656 Toll free: 1-800-445-6937 

 pass:[<email>customercare@lowes.com</email>] 

 link:$$http://www.lowes.com$$[www.lowes.com] 


=== M

 MAACO Enterprises, Inc. 

 610 Freedom Business Center Suite 200 King of Prussia, PA 19406 610-265-6606 Toll free: 1-800-523-1180 

 link:$$http://www.maaco.com$$[www.maaco.com] 

 Macy&rsquo;s 

 Customer Service PO Box 8113 Mason, OH 45040 Toll free: 1-800-526-1202 Toll free: 1-877-493-9207 (Credit) 

 link:$$http://www.macys.com$$[www.macys.com] 

 Magic Chef 

 Customer Service 777 Mark St. Wood Dale, IL 49022 Toll free: 1-888-775-0202 

 link:$$http://www.magicchef.com$$[www.magicchef.com] 

 Magnavox 

 Toll free: 1-800-705-2000 

 link:$$http://www.magnavox.com$$[www.magnavox.com] 

 Marriott International, Inc. 

 Guest Relations 1818 N. 90th St. Omaha, NE 68114-1315 Toll free: 1-800-535-4028 

 pass:[<email>customer.care@marriott.com</email>] 

 link:$$http://www.marriott.com$$[www.marriott.com] 

 Mars Chocolate North America 

 800 High St. Hackettstown, NJ 07840 908-852-1000 

 pass:[<email>askus@masterfoodsusa.com</email>] 

 link:$$http://www.masterfoods.com$$[www.masterfoods.com] 

 Marshalls, Inc. 

 See: TJX Companies, Inc. Toll free: 1-888-627-7425 

 link:$$http://www.marshallsonline.com$$[www.marshallsonline.com] 

 Massachusetts Mutual Insurance Company (Mass Mutual) 

 Customer Relations 1295 State St. Springfield, MA 01111-0001 Toll free: 1-800-272-2216 (Life Insurance) Toll free: 1-800-505-8952 (Long Term Insurance) 

 link:$$http://www.massmutual.com$$[www.massmutual.com] 

 MasterCard Worldwide 

 Consumer Inquiries (Contact your issuing bank first) 2000 Purchase St. Purchase, NY 10577 Toll free: 1-800-307-7309 

 pass:[<email>Consumer_Inquiries@mastercard.com</email>] 

 link:$$http://www.mastercard.com$$[www.mastercard.com] 

 Match.com, LLC 

 PO Box 25472 Dallas, TX 75225 

 link:$$http://www.match.com$$[www.match.com] 

 Mattel, Inc. 

 Worldwide Consumer Affairs 333 Continental Blvd. El Segundo, CA 90245-5012 310-252-2000 Toll free: 1-800-524-8697 TTY: 1-800-382-7470 

 link:$$http://www.mattel.com$$[www.mattel.com] 

 Maybelline, Inc. 

 Consumer Affairs PO Box 1010 Clark, NJ 07066 Toll free: 1-800-944-0730 

 link:$$http://www.maybelline.com$$[www.maybelline.com] 

 Mayflower Transit, LLC 

 One Mayflower Dr. St. Louis, MO 63026 636-305-4000 Toll free: 1-800-241-1321 Toll free: 1-800-325-9970 (Claims) 

 link:$$http://www.mayflower.com$$[www.mayflower.com] 

 Maytag 

 Customer Service 553 Benson Rd. Benton Harbor, MI 49022 Toll free: 1-800-344-1274 

 link:$$http://www.maytag.com$$[www.maytag.com] 

 McCormick &amp; Company, Inc. 

 Consumer Affairs 211 Schilling Circle Hunt Valley, MD 21031 410-527-6000 Toll free: 1-800-632-5847 

 link:$$http://www.mccormick.com$$[www.mccormick.com] 

 McCormick &amp; Schmicks Seafood Restaurants 

 1510 W. Loop South Houston, TX 77027 713-850-1010 Toll free: 1-800-552-6379 

 link:$$http://www.mccormickandschmicks.com$$[www.mccormickandschmicks.com] 

 McDonald&rsquo;s Corporation 

 Customer Satisfaction Dept.  2111 McDonalds Dr.  Oak Brook, IL 60523  Toll free: 1-800-244-6227 

 link:$$http://www.mcdonalds.com$$[www.mcdonalds.com] 

 McKee Foods Corporation 

 PO Box 750 Collegedale, TN 37315 Toll free: 1-800-522-4499 

 link:$$http://www.mckeefoods.com$$[www.mckeefoods.com] 

 Meineke Car Care Centers, Inc. 

 Customer Service 128 S. Tryon St., Suite 900 Charlotte, NC 28202 704-377-8855 Toll free: 1-800-447-3070 

 link:$$http://www.meineke.com$$[www.meineke.com] 

 The Mentholatum Company, Inc. 

 Consumer Affairs 707 Sterling Dr. Orchard Park, NY 14127 716-677-2500 Toll free: 1-800-688-9046 

 link:$$http://www.mentholatum.com$$[www.mentholatum.com] 

 Merck &amp; Co., Inc. 

 One Merck Dr. PO Box 100 Whitehouse Station, NJ 08889-0100 908-423-1000 Toll free: 1-800-444-2080 Toll free: 1-800-727-5400 (Patient Assistance) 

 link:$$http://www.merck.com$$[www.merck.com] 

 Merrill Lynch Company, Inc. 

 (Contact local branch manager first) 4 World Financial Center 250 Vesey St. New York, NY 10080 Toll free: 1-800-637-7455 TTY: 1-800-657-3323 

 pass:[<email>general_askml@ml.com</email>] 

 link:$$http://www.merrilllynch.com$$[www.merrilllynch.com] 

 Merry Maids 

 See: Service Master Company Toll free: 1-800-637-7962 

 pass:[<email>info@merrymaids.com</email>] 

 link:$$http://www.merrymaids.com$$[www.merrymaids.com] 

 MetLife, Inc. 

 1095 Avenue of the Americas New York, NY 10036 Toll free: 1-800-638-5433 

 link:$$http://www.metlife.com$$[www.metlife.com] 

 Michelinas 

 See: Bellisio Foods, Inc. 218-723-5555 

 pass:[<email>michelinas@bellisiofoods.com</email>] 

 link:$$http://www.michelinas.com$$[www.michelinas.com] 

 Michelin North America, Inc. 

 Consumer Care Department PO Box 19001 Greenville, SC 29602-9001 Toll free: 1-866-866-6605 

 link:$$http://www.michelinman.com$$[www.michelinman.com] 

 Microsoft Corporation 

 Customer Service 1 Microsoft Way Redmond, WA 98052-6399 425-882-8080 Toll free: 1-800-642-7676 TTY: 1-800-892-5234 

 link:$$http://www.microsoft.com$$[www.microsoft.com] 

 Midas, Inc. 

 Consumer Relations 823 Donald Ross Rd. Juno Beach, FL 33408 Toll free: 1-800-621-8545 

 link:$$http://www.midas.com$$[www.midas.com] 

 MillerCoors 

 Consumer Affairs 250 S. Wacker Dr. Chicago, IL 60606-5888 Toll free: 1-800-645-5376 

 pass:[<email>contact@millercoors.com</email>] 

 link:$$http://www.millercoors.com$$[www.millercoors.com] 

 Mitsubishi Digital Electronics America, Inc. 

 Consumer Relations Department 9351 Jeronimo Rd. Irvine, CA 92618 Toll free: 1-800-332-2119 

 pass:[<email>tvsupport@mevsa.com</email>] 

 link:$$http://www.mitsubishi-tv.com$$[www.mitsubishi-tv.com] 

 Money Management International • 

 14141 Southwest Fwy. Suite 1000 Sugar Land, TX 77478-3494 Toll free: 1-866-889-9347 

 link:$$http://www.moneymanagement.org$$[www.moneymanagement.org] 

 Morgan Stanley 

 Client Advocate 1585 Broadway New York, NY 10036 Toll free: 1-800-869-3326 

 pass:[<email>clientadvocate@morganstanley.com</email>] 

 link:$$http://www.morganstanley.com$$[www.morganstanley.com] 

 Motel 6 

 Guest Relations PO Box 326 Worthington, OH 43085 614-601-4089 Toll free: 1-800-557-3435 

 link:$$http://www.motel6.com$$[www.motel6.com] 

 Motorola, Inc. 

 Corporate Communications 600 N. US Highway 45 Libertyville, IL 60048 847-523-5000 Toll free: 1-800-734-5870 TTY: 1-888-390-6456 

 link:$$http://www.motorola.com$$[www.motorola.com] 

 Motts, Inc. 

 Consumer Relations PO Box 869077 Plano, TX 75086-9077 Toll free: 1-800-426-4891 

 link:$$http://www.motts.com$$[www.motts.com] 

 Movado Group, Inc. 

 650 From Rd., Suite 375 Paramus, NJ 07652-3556 201-267-8000 Toll free: 1-800-810-2311 

 link:$$http://www.movadogroupinc.com$$[www.movadogroupinc.com] 

 Mutual of Omaha Insurance Company 

 Customer Service Mutual of Omaha Plaza Omaha, NE 68175 402-342-7600 Toll free: 1-800-228-7104 Toll free: 1-800-775-1000 (Claims) 

 pass:[<email>individualclaims@mutualofomaha.com</email>] 

 link:$$http://www.mutualofomaha.com$$[www.mutualofomaha.com] 

 Myspace.com 

 8391 Beverly Blvd., #349 Los Angeles, CA 90048 

 pass:[<email>info@myspace.com</email>] 

 link:$$http://www.myspace.com$$[www.myspace.com] 


=== N

 Nabisco Foods Group 

 See: Kraft Foods, Inc. Toll free: 1-800-622-4726 

 link:$$http://www.nabiscoworld.com$$[www.nabiscoworld.com] 

 National Amusements, Inc. 

 Customer Service PO Box 9108 846 University Ave. Dedham, MA 02062-9108 

 pass:[<email>customer_service@national-amusements.com</email>] 

 link:$$http://www.showcasecinemas.com$$[www.showcasecinemas.com] 

 National Car Rental System, Inc. 

 Customer Service 8420 St. John Industrial Dr. St. Louis, MO 63114 Toll free: 1-800-468-3334 TTY: 1-800-328-6323 

 link:$$http://www.nationalcar.com$$[www.nationalcar.com] 

 Nationwide Mutual Insurance Company 

 Customer Advocacy One Nationwide Plaza Columbus, OH 43215-0220 Toll free: 1-877-669-6877 (Auto and Property Insurance) Toll free: 1-800-882-2822 (General Inquiries) Toll free: 1-800-848-6331 (Investments) 

 link:$$http://www.nationwide.com$$[www.nationwide.com] 

 NaturaLawn of America 

 One E. Church St. Fredrick, MD 21701 301-694-5440 Toll free: 1-800-989-5444 

 pass:[<email>natural@nl-amer.com</email>] 

 link:$$http://www.nl-amer.com$$[www.nl-amer.com] 

 Nautica Enterprises, Inc. 

 Consumer Relations 40 W. 57th St. New York, NY 10019 Toll free: 1-866-376-4184 

 link:$$http://www.nautica.com$$[www.nautica.com] 

 NBC Universal, Inc. 

 Viewer Relations 30 Rockefeller Plaza New York, NY 10112 212-664-2333 

 pass:[<email>nbcshows@nbcuni.com</email>] 

 link:$$http://www.nbc.com$$[www.nbc.com] 

 The Neiman-Marcus Group, Inc. 

 Customer Relations PO Box 650589 Dallas, TX 75265-0589 214-761-2660 Toll free: 1-888-888-4757 

 link:$$http://www.neimanmarcus.com$$[www.neimanmarcus.com] 

 Nestle Purina PetCare Company 

 Office of Consumer Affairs Checkerboard Square St. Louis, MO 63164 314-982-1000 Toll free: 1-800-778-7462 

 link:$$http://www.purina.com$$[www.purina.com] 

 Nestle USA 

 Consumer Services Center 800 N. Brand Blvd. Glendale, CA 91203 Toll free: 1-800-225-2270 

 link:$$http://www.nestle.com$$[www.nestle.com] 

 Nestle Waters North America, Inc. 

 900 Long Ridge Rd., Bldg. 2 Stamford, CT 06902-1138 203-531-4100 Toll free: 1-866-676-1672 

 link:$$http://www.nestle-watersna.com$$[www.nestle-watersna.com] 

 Netflix 

 Customer Service 100 Winchester Circle Los Gatos, CA 95032 Toll free: 1-866-579-7172 

 link:$$http://www.netflix.com$$[www.netflix.com] 

 Neutrogena Corporation 

 Consumer Affairs 199 Grandview Rd. Skillman, NJ 08558 Toll free: 1-800-582-4048 

 pass:[<email>ntgweb@neuus.jnj.com</email>] 

 link:$$http://www.neutrogena.com$$[www.neutrogena.com] 

 New England Financial 

 See: MetLife, Inc.  Toll free: 1-800-388-4000 

 link:$$http://www.nefn.com$$[www.nefn.com] 

 New York and Company 

 Customer Service 450 W. 33rd St., 5th Floor New York, NY 10001 Toll free: 1-800-723-5333 Toll free: 1-800-961-9906 (Website) 

 pass:[<email>service@nyandcompany.com</email>] 

 link:$$http://www.nyandcompany.com$$[www.nyandcompany.com] 

 New York Life Insurance Company 

 Corporate Compliance Department One Rockwood Rd. Sleepy Hollow, NY 10591 Toll free: 1-800-710-7945 

 link:$$http://www.newyorklife.com$$[www.newyorklife.com] 

 Nexxus Products Company 

 See: Unilever Toll free: 1-800-444-6399 

 link:$$http://www.nexxus.com$$[www.nexxus.com] 

 Nickelodeon 

 1515 Broadway New York, NY 10036 212-846-2543 

 link:$$http://www.nick.com$$[www.nick.com] 

 Nike, Inc. 

 Consumer Services One Bowerman Dr. Beaverton, OR 97005 503-671-6453 Toll free: 1-800-806-6453 

 link:$$http://www.nike.com$$[www.nike.com] 

 Nikon, Inc. 

 Consumer Affairs 1300 Walt Whitman Rd. Melville, NY 11747-3064 631-547-4200 310-414-8107 (Parts) Toll free: 1-800-645-6687 (Technical and Service Repair) 

 link:$$http://www.nikonusa.com$$[www.nikonusa.com] 

 Nine West Group, Inc. 

 Customer Relations Nine West Plaza 1129 Westchester Ave. White Plains, NY 10604 914-640-6400 Toll free: 1-800-999-1877 

 link:$$http://www.ninewest.com$$[www.ninewest.com] 

 Nintendo 

 4600 150th Ave., NE Redmond, WA 98052 Toll free: 1-800-255-3700 

 link:$$http://www.nintendo.com$$[www.nintendo.com] 

 Nokia USA 

 Customer Contact Center 6021 Connection Dr. Irving, TX 75039 Toll free: 1-888-665-4228 TTY: 1-800-246-6542 

 pass:[<email>customercare@nokia.com</email>] 

 link:$$http:nokiausa.com$$[nokiausa.com] 

 Nordstrom, Inc. 

 Customer Service 1700 7th Ave., Suite 300 Seattle, WA 98101 Toll free: 1-888-282-6060 

 link:$$http://www.nordstrom.com$$[www.nordstrom.com] 

 North American Van Lines 

 North American Claims Department PO Box 988 Ft. Wayne, IN 46801-0988 Toll free: 1-800-348-2111 

 link:$$http://www.navl.com$$[www.navl.com] 

 The North Face, Inc. 

 Customer Service 2013 Farallon Dr. San Leandro, CA 94577 Toll free: 1-800-863-1968 Toll free: 1-855-500-8639 (Warranties) 

 pass:[<email>tnfsupport@vfc.com</email>] 

 link:$$http://www.thenorthface.com$$[www.thenorthface.com] 

 Northwestern Mutual Life Insurance Company 

 Corporate Relations 720 E. Wisconsin Ave. Milwaukee, WI 53202-4797 414-271-1444 

 link:$$http://www.northwesternmutual.com$$[www.northwesternmutual.com] 

 Norwegian Cruise Lines 

 Guest Relations 7665 Corporate Center Dr. Miami, FL 33126 Toll free: 1-866-625-1164 Toll free: 1-866-584-9756 (Special Needs) 

 link:$$http://www.ncl.com$$[www.ncl.com] 

 Novartis Pharmaceuticals Corporation 

 Customer Interaction Center One Health Plaza East Hanover, NJ 07936-1080 862-778-8300 Toll free: 1-888-669-6682 

 link:$$http://www.pharma.us.novartis.com$$[www.pharma.us.novartis.com] 

 The NutraSweet Company 

 Customer Service 10 S. Wacker Dr. Chicago, IL 60606 Toll free: 1-800-323-5321 

 link:$$http://www.nutrasweet.com$$[www.nutrasweet.com] 

 NutriSystem, Inc. 

 Customer Service 600 Office Center Dr. Fort Washington, PA 19034 215-706-5300 Toll free: 1-800-585-5483 

 link:$$http://www.nutrisystem.com$$[www.nutrisystem.com] 


=== O

 Ocean Spray Cranberries, Inc. 

 Consumer Affairs Department One Ocean Spray Dr. Lakeville-Middleboro, MA 02349 Toll free: 1-800-662-3263 

 link:$$http://www.oceanspray.com$$[www.oceanspray.com] 

 Office Depot, Inc. 

 6600 N. Military Trail Boca Raton, FL 33496 Toll free: 1-800-463-3768 

 link:$$http://www.officedepot.com$$[www.officedepot.com] 

 OfficeMax, Inc. 

 Customer Service 263 Shuman Blvd. Naperville, IL 60563 630-438-7800 Toll free: 1-800-283-7674 

 pass:[<email>online@officemax.com</email>] 

 link:$$http://www.officemax.com$$[www.officemax.com] 

 Old Navy 

 Customer Relations 200 Old Navy Ln. Grove City, OH 43123-8605 Toll free: 1-800-653-6289 TTY: 1-800-449-4253 

 pass:[<email>custserv@oldnavy.com</email>] 

 link:$$http://www.oldnavy.com$$[www.oldnavy.com] 

 Olive Garden 

 PO Box 695017 Orlando, FL 32869 Toll free: 1-800-331-2729 

 link:$$http://www.olivegarden.com$$[www.olivegarden.com] 

 Olympus America 

 3500 Corporate Pkwy. PO Box 610 Center Valley, PA 18034-0610 Toll free: 1-800-622-6372 Toll free: 1-888-553-4448 (Digital Cameras) 

 link:$$http://www.olympusamerica.com$$[www.olympusamerica.com] 

 Omni Hotels 

 Guest Relations 420 Decker Dr. Irving, TX 75062 Toll free: 1-800-809-6664 

 link:$$http://www.omnihotels.com$$[www.omnihotels.com] 

 1-800-FLOWERS 

 Customer Satisfaction Department One Old Country Rd., Suite 500 Carle Place, NY 11514 Toll free: 1-800-356-9377 Toll free: 1-800-716-4851 (Customer Service) 

 link:$$http://www.1800flowers.com$$[www.1800flowers.com] 

 On the Border 

 See: Brinker International Toll free: 1-800-682-6882 

 link:$$http://www.ontheborder.com$$[www.ontheborder.com] 

 Orbitz, Inc. 

 Customer Service 500 W. Madison St., Suite 1000 Chicago, IL 60661 Toll free: 1-888-656-4546 

 link:$$http://www.orbitz.com$$[www.orbitz.com] 

 Orkin 

 Customer Care Center 2170 Piedmont Rd., NE Atlanta, GA 30324 Toll free: 1-888-675-4662 

 link:$$http://www.orkin.com$$[www.orkin.com] 

 Oster 

 See: Jarden Consumer Solutions, Inc. Toll free: 1-800-334-0759 

 link:$$http://www.oster.com$$[www.oster.com] 

 Outback Steakhouse 

 2202 N. West Shore Blvd., Suite 500 Tampa, FL 33607-5761 813-282-1225 

 pass:[<email>newsoutback@outback.com</email>] 

 link:$$http://www.outback.com$$[www.outback.com] 

 Overstock.com 

 Customer Service 6350 S. 3000 E Salt Lake City, UT 84121 Toll free: 1-800-843-2446 

 link:$$http://www.overstock.com$$[www.overstock.com] 

 Owens Corning 

 Consumer Relations One Owens Corning Pkwy. Toledo, OH 43659 Toll free: 1-800-438-7465 

 pass:[<email>answers@answers.owenscorning.com</email>] 

 link:$$http://www.owenscorning.com$$[www.owenscorning.com] 


=== P

 Panasonic Corporation of North America 

 Customer Experience Department 661 Independence Pkwy. Chesapeake, VA 23320 Toll free: 1-800-211-7262 

 link:$$http://www.panasonic.com$$[www.panasonic.com] 

 Panera Bread 

 6710 Clayton Rd. Richmond Heights, MO 63117 314-633-7100 Toll free: 1-800-301-5566 

 link:$$http://www.panerabread.com$$[www.panerabread.com] 

 Papa John&rsquo;s International, Inc. 

 PO Box 99900 Louisville, KY 40269-9990 Toll free: 1-877-547-7272 

 link:$$http://www.papajohns.com$$[www.papajohns.com] 

 Pathmark Stores, Inc. 

 Customer Relations Two Paragon Dr. Montvale, NJ 07645 Toll free: 1-866-443-7374 

 pass:[<email>customers@pathmark.com</email>] 

 link:$$http://www.pathmark.com$$[www.pathmark.com] 

 Payless ShoeSource 

 Customer Service 3231 S.E. 6th Ave. Topeka, KS 66607 Toll free: 1-877-474-6379 

 pass:[<email>CustomerService@csr.payless.com</email>] 

 link:$$http://www.payless.com$$[www.payless.com] 

 PayPal.com 

 2211 N. 1st St. San Jose, CA 95131 Toll free: 1-888-221-1161 

 link:$$http://www.paypal.com$$[www.paypal.com] 

 PearleVision 

 Customer Service 4000 Luxottica Pl. Mason, OH 45040 Toll free: 1-800-937-3937 

 link:$$http://www.pearlevision.com$$[www.pearlevision.com] 

 Pennzoil 

 See: Shell Oil Company 713-546-4000 Toll free: 1-800-237-8645 

 pass:[<email>generalpublicenquiries-us@shell.com</email>] 

 link:$$http://www.pennzoil.com$$[www.pennzoil.com] 

 Pep Boys Auto 

 3111 W. Allegheny Ave. Philadelphia, PA 19132 Toll free: 1-800-737-2697 

 pass:[<email>custserv@pepboys.com</email>] 

 link:$$http://www.pepboys.com$$[www.pepboys.com] 

 Pepperidge Farm, Inc. 

 Consumer Affairs 595 Westport Ave. Norwalk, CT 06851 Toll free: 1-888-737-7374 

 link:$$http://www.pepperidgefarm.com$$[www.pepperidgefarm.com] 

 Pepsi-Cola Company 

 Consumer Relations One Pepsi Way Somers, NY 10589 Toll free: 1-800-433-2652 

 link:$$http://www.pepsico.com$$[www.pepsico.com] 

 Perdue Farms, Inc. 

 Consumer Relations PO Box 1656 Horsham, PA 19044-6656 Toll free: 1-800-473-7383 

 link:$$http://www.perdue.com$$[www.perdue.com] 

 Petco 

 Toll free: 1-877-738-6742 

 link:$$http://www.petco.com$$[www.petco.com] 

 PetSmart, Inc. 

 Customer Service Toll free: 1-888-839-9638 

 pass:[<email>customercare@petsmart.com</email>] 

 link:$$http://www.petsmart.com$$[www.petsmart.com] 

 P.F. Chang&rsquo;s China Bistro, Inc. 

 7676 E. Pinnacle Peak Rd. Scottsdale, AZ 85255 Toll free: 1-866-732-4264 

 link:$$http://www.pfchangs.com$$[www.pfchangs.com] 

 Pfizer, Inc. 

 Consumer Affairs 235 E. 42nd St. New York, NY 10017 212-733-2323 Toll free: 1-800-879-3477 (Customer Response) Toll free: 1-800-438-1985 (Medical Questions) 

 link:$$http://www.pfizer.com$$[www.pfizer.com] 

 Pharmavite Corporation 

 Consumer Affairs PO Box 9606 Mission Hills, CA 91346-9606 818-221-6200 Toll free: 1-800-276-2878 (Nature Made) Toll free: 1-888-676-9569 (Soy Joy) 

 link:$$http://www.pharmavite.com$$[www.pharmavite.com] 

 Philip Morris USA 

 Quality Department PO Box 18583 Pittsburgh, PA 15236 804-274-2000 Toll free: 1-800-343-0975 

 link:$$http://www.philipmorrisusa.com$$[www.philipmorrisusa.com] 

 Philips Consumer Electronics North America 

 Customer Service 3000 Minuteman Rd., Mail Stop 109 Andover, MA 01810 Toll free: 1-888-744-5477 

 link:$$http://www.philips.com$$[www.philips.com] 

 Phillips-Van Heusen Corporation 

 Customer Services  1001 Frontier Rd., Mail Stop # 44  Bridgewater, NJ 08807  Toll free: 1-800-388-9122 (Van Heusen)  Toll free: 1-800-950-2277 (Bass)  Toll free: 1-800-866-7292 (Izod)  Toll free: 1-866-214-6694 (Calvin Klein) 

 link:$$http://www.pvh.com$$[www.pvh.com] 

 Pinnacle Foods Group LLC 

 Consumer Relations PO Box 3900 Peoria, IL 61612 

 link:$$http:pinnaclefoods.com$$[pinnaclefoods.com] 

 Pioneer Electronics Service, Inc. 

 Customer Service  Toll free: 1-800-228-7221 (Parts)  Toll free: 1-800-421-1404 (General Service) 

 link:$$http://www.pioneerelectronics.com$$[www.pioneerelectronics.com] 

 Pirelli Tire Corporation 

 100 Pirelli Dr. Rome, GA 30161 Toll free: 1-800-747-3554 

 link:$$http://www.us.pirelli.com$$[www.us.pirelli.com] 

 Pizza Hut 

 7100 Corporate Dr. Plano, TX 75024 972-338-7700 Toll free: 1-800-948-8488 

 link:$$http://www.pizzahut.com$$[www.pizzahut.com] 

 Playskool 

 Toll free: 1-800-752-9755 

 pass:[<email>customersupport@hasbro.com</email>] 

 link:$$http://www.hasbro.com/playskool$$[www.hasbro.com/playskool] 

 Playstation 

 See: Sony Corporation of America Toll free: 1-800-345-7669 

 link:$$http://www.us.playstation.com$$[www.us.playstation.com] 

 Playtex Products, Inc. 

 Consumer Affairs 890 Mountain Ave. New Providence, NJ 07974 Toll free: 1-888-310-4290 

 link:$$http://www.playtexproductsinc.com$$[www.playtexproductsinc.com] 

 Polaroid Corporation 

 Customer Care Center 4400 Baker Ave. Minnetonka, MN 55343 Toll free: 1-800-765-2764 (Product Support) Toll free: 1-888-312-2615 (Order Support) 

 pass:[<email>info@polaroid.com</email>] 

 link:$$http://www.polaroid.com$$[www.polaroid.com] 

 Polo/Ralph Lauren Corporation 

 Consumer Relations 625 Madison Ave., 11th Floor New York, NY 10022 Toll free: 1-888-475-7674 

 pass:[<email>customerassistance@ralphlauren.com</email>] 

 link:$$http://www.polo.com$$[www.polo.com] 

 Popeyes Louisiana Kitchen 

 Guest Hospitality PO Box 725489 Atlanta, GA 31139 Toll free: 1-877-767-3937 

 pass:[<email>popeyescommunications@popeyes.com</email>] 

 link:$$http://www.popeyes.com$$[www.popeyes.com] 

 Prestige Brands 

 Office of Consumer Affairs 90 N. Broadway Irvington, NY 10533 Toll free: 1-800-443-4908 

 link:$$http://www.prestigebrandsinc.com$$[www.prestigebrandsinc.com] 

 Price Chopper Supermarkets 

 Consumer Services 461 Nott St. Schenectady, NY 12308 518-355-5000 Toll free: 1-800-666-7667 

 link:$$http://www.pricechopper.com$$[www.pricechopper.com] 

 Priceline 

 800 Connecticut Ave. Norwalk, CT 06854 Toll free: 1-877-477-5807 

 link:$$http://www.priceline.com$$[www.priceline.com] 

 Princess Cruise Lines 

 Customer Relations 24305 Town Center Dr. Santa Clarita, CA 91355 Toll free: 1-800-774-6237 

 pass:[<email>customerrelations@princesscruises.com</email>] 

 link:$$http://www.princess.com$$[www.princess.com] 

 The Procter &amp; Gamble Company 

 Consumer Relations PO Box 599 Cincinnati, OH 45201 513-983-1100 Toll free: (Toll free numbers appear on all labels) 

 link:$$http://www.pg.com$$[www.pg.com] 

 The Progressive Corporation 

 Customer Service 6300 Wilson Mills Rd. Mayfield Village, OH 44143 440-461-5000 (Corporate) Toll free: 1-800-776-4737 

 link:$$http://www.progressive.com$$[www.progressive.com] 

 Prudential Financial, Inc. 

 Policyowner Relations Dept.  One Corporate Dr.  Shelton, CT 06484  Toll free: 1-800-778-2255 (Insurance)  Toll free: 1-888-778-2888 (Annuities)  Toll free: 1-800-732-0416 (Long-Term Care)  TTY: 1-800-526-8061 

 link:$$http://www.prudential.com$$[www.prudential.com] 

 Publishers Clearing House 

 Consumer Affairs 101 Winners Circle Port Washington, NY 11050 Toll free: 1-800-459-4724 Toll free: 1-800-392-4190 (Sweepstakes scams using PCH name) 

 pass:[<email>pchconsumeraffairs@pch.com</email>] 

 link:$$http://www.pch.com$$[www.pch.com] 

 Publix 

 Consumer Relations PO Box 407 Lakeland, FL 33802-0407 Toll free: 1-800-242-1227 

 link:$$http://www.publix.com$$[www.publix.com] 


=== Q

 Qdoba Mexican Grill 

 4865 Ward Rd., Suite 500 Wheat Ridge, CO 80033-1902 720-898-2300 Toll free: 1-888-497-3622 

 pass:[<email>info@qdoba.com</email>] 

 link:$$http://www.qdoba.com$$[www.qdoba.com] 

 The Quaker Oats Company 

 Consumer Response/QTG PO Box 049003 Chicago, IL 60604-9003 312-821-1000 Toll free: 1-800-367-6287 

 link:$$http://www.quakeroats.com$$[www.quakeroats.com] 

 QuikTrip Corporation 

 PO Box 3475 Tulsa, OK 74101 918-615-7700 Toll free: 1-800-848-1966 

 link:$$http://www.quiktrip.com$$[www.quiktrip.com] 

 Quiznos 

 1001 17th St., Suite 200 Denver, CO 80202 720-359-3300 (Headquarters) Toll free: 1-866-486-2783 (Customer Comments) 

 link:$$http://www.quiznos.com$$[www.quiznos.com] 

 QVC, Inc. 

 Customer Service 1200 Wilson Drive at Studio Park West Chester, PA 19380 Toll free: 1-800-345-5788 TTY: 1-800-544-3316 

 pass:[<email>QVCcares@QVC.com</email>] 

 link:$$http://www.qvc.com$$[www.qvc.com] 


=== R

 Radio Shack Corporation 

 Customer Care Riverfront Campus Mail Stop #CF4-216 300 Radio Shack Circle Fort Worth, TX 76102-1964 817-415-3011 Toll free: 1-800-843-7422 

 pass:[<email>RadioShack.Customer.Care@RadioShack.com</email>] 

 link:$$http://www.radioshack.com$$[www.radioshack.com] 

 Radisson Hotels Resorts 

 11340 Blondo St., Suite 100 Omaha, NE 68164 Toll free: 1-800-615-7253 

 link:$$http://www.radisson.com$$[www.radisson.com] 

 Ramada Inn 

 See: Wyndham Hotel Group Toll free: 1-800-828-6644 

 link:$$http://www.ramada.com$$[www.ramada.com] 

 Rayovac Corporation 

 Consumer Service PO Box 44960 Madison, WI 53744 Toll free: 1-800-237-7000 

 pass:[<email>consumers@rayovac.com</email>] 

 link:$$http://www.rayovac.com$$[www.rayovac.com] 

 Readers Digest Association, Inc. 

 Customer Service Readers Digest Rd. Pleasantville, NY 10570-7000 914-238-1000 Toll free: 1-800-304-2807 TTY: 1-800-735-4327 

 pass:[<email>letters@rd.com</email>] 

 link:$$http://www.readersdigest.com$$[www.readersdigest.com] 

 Reckitt Benckiser, Inc. 

 Consumer Relations PO Box 224 Parsippany, NJ 07054-0224 Toll free: 1-800-228-4722 

 pass:[<email>corpomms@reckittbenckiser.com</email>] 

 link:$$http://www.reckittbenckiser.com$$[www.reckittbenckiser.com] 

 Red Lobster 

 Guest Relations 1000 Darden Center Dr. Orlando, FL 32837 407-245-4000 Toll free: 1-800-562-7837 

 link:$$http://www.redlobster.com$$[www.redlobster.com] 

 Regal Ware, Inc. 

 Consumer Service 1675 Reigle Dr. Kewaskum, WI 53040 262-626-2121 

 pass:[<email>info@regalware.com</email>] 

 link:$$http://www.regalware.com$$[www.regalware.com] 

 Remington Products Company 

 Consumer Services PO Box 1 DeForest, WI 53532 Toll free: 1-800-392-6544 

 pass:[<email>ContactUs@ remingtonproducts.com</email>] 

 link:$$http://www.remington-products.com$$[www.remington-products.com] 

 Rent-A-Center 

 Customer Service 5501 Headquarters Dr. Plano, TX 75024 Toll free: 1-800-422-8186 

 link:$$http://www.rentacenter.com$$[www.rentacenter.com] 

 Residence Inn 

 See: Marriott International, Inc. Toll free: 1-800-228-2800 

 link:$$http://www.residenceinn.com$$[www.residenceinn.com] 

 Rich Products 

 Consumer Relations PO Box 20670 127 Airport Rd. St. Simons Island, GA 31522 912-638-5000 Toll free: 1-888-732-7251 

 pass:[<email>rsp-consumer.relations@rich.com</email>] 

 Rite Aid Corporation 

 Customer Support PO Box 3165 Harrisburg, PA 17105 717-761-2633 Toll free: 1-800-748-3243 Toll free: 1-888-213-9920 (Rebates) TTY: 1-800-821-1833 

 link:$$http://www.riteaid.com$$[www.riteaid.com] 

 Rolex Watch U.S.A., Inc. 

 665 5th Ave., 5th Floor New York, NY 10022 212-758-7700 

 link:$$http://www.rolex.com$$[www.rolex.com] 

 Roto-Rooter Corporation 

 225 E. 5th St. Cincinnati, OH 45202 513-762-6690 Toll free: 1-800-438-7686 

 link:$$http://www.roto-rooter.com$$[www.roto-rooter.com] 

 Royal Caribbean International 

 Corporate Guest Relations 1050 Caribbean Way Miami, FL 33132 Toll free: 1-800-256-6649 Toll free: 1-800-398-9819 (Website) 

 link:$$http://www.royalcaribbean.com$$[www.royalcaribbean.com] 

 Rubbermaid 

 Consumer Services 3320 W. Market St. Fairlawn, OH 44333 Toll free: 1-888-895-2110 

 link:$$http://www.rubbermaid.com$$[www.rubbermaid.com] 

 Ruths Chris Steakhouse 

 Ruths Hospitality Group, Inc. 1030 W. Canton Ave., Suite 100 Winter Park, FL 32789 407-333-7440 

 link:$$http://www.ruthschris.com$$[www.ruthschris.com] 


=== S

 Safe Auto Insurance 

 Customer Service PO Box 182109 Columbus, OH 43218-2109 Toll free: 1-800-723-3288 

 pass:[<email>csd@safeauto.com</email>] 

 Safeway, Inc. 

 Customer Service Center MS 10501 PO Box 29093 Phoenix, AZ 85038-9093 Toll free: 1-877-723-3929 

 link:$$http://www.safeway.com$$[www.safeway.com] 

 Saks Fifth Avenue 

 Customer Relations PO Box 10327 Jackson, MS 39289 212-940-5027 Toll free: 1-877-551-7257 

 pass:[<email>service@saks.com</email>] 

 link:$$http://www.saks.com$$[www.saks.com] 

 Sam&rsquo;s Club 

 Member Service 2101 S.E. Simple Savings Dr. Bentonville, AR 72716-0745 Toll free: 1-888-746-7726 

 link:$$http://www.samsclub.com$$[www.samsclub.com] 

 Samsonite Corporation 

 Customer Service 575 West St., Suite 110 Mansfield, MA 02048 Toll free: 1-800-765-2247 Toll free: 1-800-262-8282 (Warranty) 

 pass:[<email>questions@samsonite.com</email>] 

 link:$$http://www.samsonite.com$$[www.samsonite.com] 

 Samsung Electronics America 

 Customer Service and Technical Support 85 Challenger Rd. Ridgefield Park, NJ 07660 Toll free: 1-800-726-7864 Toll free: 1-888-987-4357 (Mobile Phones) TTY: 1-888-899-7608 

 link:$$http://www.samsung.com$$[www.samsung.com] 

 Sanofi-Aventis 

 55 Corporate Dr. Bridgewater, NJ 08807-2854 Toll free: 1-800-981-2491 

 link:$$http://www.sanofi-aventis.us$$[www.sanofi-aventis.us] 

 Sargento Foods Inc. 

 Consumer Affairs One Persnickety Pl. Plymouth, WI 53073 920-893-8484 (Corporate) Toll free: 1-800-243-3737 

 link:$$http://www.sargento.com$$[www.sargento.com] 

 Sara Lee Foods 

 See: Hillshire Brands 

 link:$$http:saralee.com$$[saralee.com] 

 SC Johnson and Son, Inc. 

 1525 Howe St. Racine, WI 53403 Toll free: 1-800-494-4855 

 link:$$http://www.scjohnsonwax.com$$[www.scjohnsonwax.com] 

 The Scotts Company 

 Help Center 14111 Scottslawn Rd. Marysville, OH 43041 Toll free: 1-888-270-3714 

 link:$$http://www.scotts.com$$[www.scotts.com] 

 Seabourn Cruise Line 

 Guest Relations 300 Elliott Ave., W Seattle, WA 98119 206-626-9179 Toll free: 1-866-755-5619 

 pass:[<email>guestrelations@seabourn.com</email>] 

 link:$$http://www.seabourn.com$$[www.seabourn.com] 

 Sealy Corporation 

 Consumer Support One Office Parkway at Sealy Dr. Trinity, NC 27370 Toll free: 1-800-697-3259 

 link:$$http://www.sealy.com$$[www.sealy.com] 

 Sears 

 Executive Customer Relations 3333 Beverly Rd. Mail Stop RR Hoffman Estates, IL 60179 847-286-2500 Toll free: 1-800-549-4505 (Retail) Toll free: 1-800-697-3277 (Online) TTY: 1-800-659-7017 

 link:$$http://www.sears.com$$[www.sears.com] 

 Seiko Instruments USA, Inc. 

 Customer Service 2990 Lomita Blvd. Torrance, CA 90505 Toll free: 1-800-757-1011 

 link:$$http://www.seikoinstruments.com$$[www.seikoinstruments.com] 

 Seneca Foods Corporation 

 Consumer Affairs 3736 S. Main St. Marion, NY 14505 315-926-8100 Toll free: 1-800-872-1110 

 link:$$http://www.senecafoods.com$$[www.senecafoods.com] 

 Serta, Inc. 

 Customer Service Three Golf Center #392 Hoffman Estates, IL 60169 847-645-0200 Toll free: 1-888-557-3782 

 pass:[<email>customer.service@serta.com</email>] 

 link:$$http://www.serta.com$$[www.serta.com] 

 Service Master Company 

 860 Ridge Lake Blvd. Memphis, TN 38120 

 link:$$http://www.servicemaster.com$$[www.servicemaster.com] 

 7-Eleven, Inc 

 Customer Relations Location 231 PO Box 711 Dallas, TX 75221-0711 972-828-7011 Toll free: 1-800-255-0711 

 link:$$http://www.7-Eleven.com$$[www.7-Eleven.com] 

 Sharp Electronics Corporation 

 Customer Service Sharp Plaza Mahwah, NJ 07495 Toll free: 1-800-237-4277 

 link:$$http://www.sharpusa.com$$[www.sharpusa.com] 

 Shell Oil Company 

 Customer Care PO Box 2463 Houston, TX 77252 713-241-6161 (Headquarters) Toll free: 1-888-467-4355 Toll free: 1-800-331-3703 (Shell Card) 

 pass:[<email>ShellCustomerCare@shell.com</email>] 

 link:$$http://www.shellus.com$$[www.shellus.com] 

 Sheraton Hotels 

 See: Starwood Hotels &amp; Resorts Worldwide, Inc. Toll free: 1-800-325-3535 

 link:$$http://www.sheraton.com$$[www.sheraton.com] 

 Sherwin-Williams Company 

 Midland Building 101 Prospect Ave., NW PO Box 647 Cleveland, OH 44115 Toll free: 1-800-474-3794 

 link:$$http://www.sherwin-williams.com$$[www.sherwin-williams.com] 

 Shoneys, Inc. 

 Guest Relations 1717 Elm Hill Pike, Suite B-1 Nashville, TN 37210 615-391-5395 Toll free: 1-877-377-2233 

 pass:[<email>helpdesk@shoneys.com</email>] 

 link:$$http://www.shoneys.com$$[www.shoneys.com] 

 Simmons Bedding Company 

 Consumer Service One Concourse Pkwy., Suite 800 Atlanta, GA 30328-6188 Toll free: 1-877-399-9397 

 pass:[<email>customerassistance@simmons.com</email>] 

 link:$$http://www.simmons.com$$[www.simmons.com] 

 Slim-Fast Foods Company 

 Consumer Services Dept. 920 Sylvan Ave., 2nd Floor Englewood Cliffs, NJ 07632 Toll free: 1-800-754-6327 

 pass:[<email>support@slimfast.com</email>] 

 link:$$http://www.slimfast.com$$[www.slimfast.com] 

 Sonesta International Hotels Corporation 

 255 Washington St. Newton, MA 02458 617-421-5447 Toll free: 1-800-766-3782 

 pass:[<email>info@sonesta.com</email>] 

 link:$$http://www.sonesta.com$$[www.sonesta.com] 

 Sony Corporation of America 

 Consumer Information Service Center  12451 Gateway Blvd.  Fort Myers, FL 33913  239-768-7547 (Consumer Eletronics)  Toll free: 1-800-345-7669 (Playstation) 

 link:$$http://www.sony.com$$[www.sony.com] 

 Southwest Airlines 

 Customer Relations Department PO Box 36647-1CR Dallas, TX 75235 214-932-0333 Toll free: 1-800-435-9792 TTY: 1-800-533-1305 

 link:$$http://www.southwest.com$$[www.southwest.com] 

 Spiegel Brands, Inc 

 Customer Satisfaction One Spiegel Ave. Hampton, VA 23630-5367 Toll free: 1-800-222-5680 

 pass:[<email>clientservices@spiegel.com</email>] 

 link:$$http://www.spiegel.com$$[www.spiegel.com] 

 Spirit Airlines 

 2800 Executive Way Miramar, FL 33025 Toll free: 1-800-772-7117 

 pass:[<email>customer@spirit.com</email>] 

 link:$$http://www.spiritair.com$$[www.spiritair.com] 

 Springs Global U.S., Inc. 

 Public Relations Dept. of Corporate Communication PO Box 70 Fort Mill, SC 29716 803-547-1500 Toll free: 1-888-926-7888 Toll free: 1-800-221-6352 (Window Products) 

 link:$$http://www.springs.com$$[www.springs.com] 

 Sprint Nextel 

 KSOPHT0101-Z4300 6391 Sprint Pkwy. Overland Park, KS 66251-4300 Toll free: 1-888-211-4727 (Sprint Phones) Toll free: 1-800-639-6111 (Nextel Phones) Toll free: 1-800-877-4646 (Wireline Service) 

 link:$$http://www.sprint.com/consumerinfo$$[www.sprint.com] 

 Stanley Hardware (Division of the Stanley Works) 

 Customer Service 480 Myrtle St. New Britain, CT 06053 Toll free: 1-800-622-4393 

 link:$$http://www.stanleyhardware.com$$[www.stanleyhardware.com] 

 Staples, Inc. 

 Consumer Affairs 500 Staples Dr. Framingham, MA 01702 Toll free: 1-800-378-2753 

 link:$$http://www.staples.com$$[www.staples.com] 

 Starbucks 

 Customer Relations PO Box 3717 Seattle, WA 98124-3717 Toll free: 1-800-782-7282 

 link:$$http://www.starbucks.com$$[www.starbucks.com] 

 Starwood Hotels &amp; Resorts Worldwide, Inc. 

 Customer Service PO Box 6020 Lancaster, CA 93539 Toll free: 1-800-625-5144 

 pass:[<email>customercare@starwoodhotels.com</email>] 

 link:$$http://www.starwoodhotels.com$$[www.starwoodhotels.com] 

 State Farm 

 Customer Service One State Farm Plaza Bloomington, IL 61710 309-766-2311 Toll free: 1-800-782-8332 

 pass:[<email>info@statefarm.com</email>] 

 link:$$http://www.statefarm.com$$[www.statefarm.com] 

 SteinMart 

 1200 Riverplace Blvd. Jacksonville, FL 32207 904-346-1500 Toll free: 1-888-783-4662 

 pass:[<email>e-customerservice@steinmart.com</email>] 

 link:$$http://www.steinmart.com$$[www.steinmart.com] 

 Stop &amp; Shop Supermarket Company, Inc. 

 Customer Service Dept.  1385 Hancock St.  Quincy, MA 02169  Toll free: 1-800-767-7772 

 link:$$http://www.stopandshop.com$$[www.stopandshop.com] 

 StubHub, Inc. 

 199 Fremont St., Suite 300 San Francisco, CA 94105 

 pass:[<email>customerservice@stubhub.com</email>] 

 link:$$http:www.stubhub.com$$[www.stubhub.com] 

 Subway 

 325 Bic Dr. Milford, CT 06461 Toll free: 1-800-888-4848 

 link:$$http://www.subway.com$$[www.subway.com] 

 Suntrust 

 PO Box 85024 Richmond, VA 23285-5024 Toll free: 1-800-786-8787 TTY: 1-800-854-8965 

 link:$$http://www.suntrust.com$$[www.suntrust.com] 

 Symantec Corporation 

 Customer Service 350 Ellis St. Mountain View, CA 94043 Toll free: 1-800-721-3934 

 link:$$http://www.symantec.com$$[www.symantec.com] 


=== T

 Taco Bell 

 Customer Relations One Glen Bell Way Irvine, CA 92618 Toll free: 1-800-822-6235 

 link:$$http://www.tacobell.com$$[www.tacobell.com] 

 Talbots 

 Customer Service Department One Talbots Dr. Hingham, MA 02043 781-741-4028 Toll free: 1-800-992-9010 TTY: 1-800-624-9179 

 pass:[<email>customerservice@talbots.com</email>] 

 link:$$http://www.talbots.com$$[www.talbots.com] 

 Target Stores 

 Guest Relations and Quality Assurance PO Box 9350 Minneapolis, MN 55440 Toll free: 1-800-440-0680 

 pass:[<email>guest.relations@target.com</email>] 

 link:$$http://www.target.com$$[www.target.com] 

 TEAC America, Inc. 

 Customer Service 7733 Telegraph Rd. Montebello, CA 90640 323-726-0303 323-727-7627 (Service) 

 pass:[<email>custser@teac.com</email>] 

 link:$$http://www.teac.com$$[www.teac.com] 

 Teleflora 

 PO Box 60910 Los Angeles, CA 90060-0910 Toll free: 1-800-835-3356 

 pass:[<email>service@teleflora.com</email>] 

 link:$$http://www.teleflora.com$$[www.teleflora.com] 

 Terminix 

 See: Service Master Company Toll free: 1-800-837-6464 

 pass:[<email>terminixcares@terminix.com</email>] 

 link:$$http://www.terminix.com$$[www.terminix.com] 

 Texas Instruments, Inc. 

 Consumer Relations PO Box 660199 Dallas, TX 75266-0199 972-995-2011 Toll free: 1-800-842-2737 

 link:$$http://www.ti.com$$[www.ti.com] 

 T.G.I. Fridays 

 Guest Relations  4201 Marsh Ln.  Carrollton, TX 75007  Toll free: 1-800-374-4297 (Option 1) 

 link:$$http://www.tgifridays.com$$[www.tgifridays.com] 

 3M 

 Customer Relations 3M Center St. Paul, MN 55144-1000 651-737-6501 Toll free: 1-800-364-3577 

 link:$$http://www.3m.com$$[www.3m.com] 

 Thrifty Car Rental 

 PO Box 35250 Tulsa, OK 74153 918-669-2168 Toll free: 1-800-847-4389 TTY: 1-888-332-3677 

 pass:[<email>customercare@thrifty.com</email>] 

 link:$$http://www.thrifty.com$$[www.thrifty.com] 

 TicketMaster 

 Attn: Fan Support 1000 Corporate Landing Charleston, WV 25311 Toll free: 1-800-653-8000 

 link:$$http://www.ticketmaster.com$$[www.ticketmaster.com] 

 Time, Inc. 

 Consumer Affairs 3000 University Center Dr. Tampa, FL 33612-6408 813-979-6625 Toll free: 1-866-550-6934 

 pass:[<email>subsvcs@time.customersvc.com</email>] 

 link:$$http://www.time.com$$[www.time.com] 

 Time Warner, Inc. 

 One Time Warner Center New York, NY 10019 212-484-8000 

 link:$$http://www.timewarner.com$$[www.timewarner.com] 

 Timex Corporation 

 Customer Service 1302 Pike Ave. North Little Rock, AR 72114 501-372-1111 Toll free: 1-800-448-4639 

 pass:[<email>custserv@timex.com</email>] 

 link:$$http://www.timex.com$$[www.timex.com] 

 TJ Maxx 

 See: TJX Companies, Inc. 508-390-3000 Toll free: 1-800-926-6299 

 link:$$http://www.tjmaxx.com$$[www.tjmaxx.com] 

 TJX Companies, Inc. 

 770 Cochituate Rd.  Framingham, MA 01701  508-390-1000  Toll free: 1-800-926-6299 (TJ Maxx)  Toll free: 1-800-888-0776 (Home Goods)  Toll free: 1-888-627-7425 (Marshalls) 

 link:$$http://www.tjx.com$$[www.tjx.com] 

 T-Mobile Wireless 

 Customer Relations PO Box 37380 Albuquerque, NM 87176-7380 Toll free: 1-877-453-1304 (Customer Care) Toll free: 1-800-866-2453 (Product Questions) TTY: 1-877-296-1018 

 link:$$http://www.tmobile.com$$[www.tmobile.com] 

 Top-Flite Professional Golf Company 

 See: Dick&rsquo;s Sporting Goods 

 link:$$http://www.topflite.com$$[www.topflite.com] 

 The Toro Company 

 Consumer Customer Care 8111 Lyndale Ave., S Bloomington, MN 55420 Toll free: 1-888-384-9939 

 pass:[<email>consumer.service@toro.com</email>] 

 link:$$http://www.toro.com$$[www.toro.com] 

 Toshiba America 

 Digital Products Division 9740 Irvine Blvd. Irvine, CA 92618-1697 Toll free: 1-800-631-3811 Toll free: 1-800-457-7777 (Computers) 

 pass:[<email>customer_support@tacp.com</email>] 

 link:$$http://www.tacp.toshiba.com$$[www.tacp.toshiba.com] 

 Totes/Isotoner 

 Customer Service 9655 International Blvd. Cincinnati, OH 45246-5658 513-682-8200 (Warranties) Toll free: 1-800-762-8712 Toll free: 1-800-281-4535 (Online Purchases) 

 pass:[<email>customeraffairs@totes.com</email>] 

 link:$$http://www.totes.com$$[www.totes.com] 

 Toys R Us 

 Guest Relations One Geoffrey Way Wayne, NJ 07470 973-617-3500 Toll free: 1-800-869-7787 

 pass:[<email>contactus@toysrus.com</email>] 

 link:$$http://www.toysrus.com$$[www.toysrus.com] 

 Trader Joe&rsquo;s 

 PO Box 5049 Monrovia, CA 91016 626-599-3817 

 link:$$http://www.traderjoes.com$$[www.traderjoes.com] 

 Trane 

 Residential Customer Relations One Centennial Ave. Piscataway, NJ 08854 903-581-3660 

 link:$$http://www.trane.com$$[www.trane.com] 

 TransUnion, LLC 

 Consumer Solutions PO Box 2000 Chester, PA 19022 Toll free: 1-800-888-4213 (Obtain a Report) Toll free: 1-800-916-8800 (Disputes) Toll free: 1-800-680-7289 (Frauds) 

 pass:[<email>fvad@transunion.com</email>] (Fraud Victims) 

 link:$$http://www.transunion.com$$[www.transunion.com] 

 Travelers Companies, Inc. 

 Consumer Affairs One Tower Square 8MS Hartford, CT 06183 Toll free: 1-866-336-2077 (Customer Advocacy) Toll free: 1-800-252-4633 (Claim Inquiry) 

 link:$$http://www.travelers.com$$[www.travelers.com] 

 Travelocity.com LP 

 Customer Service 11603 Crosswinds Way, Suite 125 San Antonio, TX 78233 Toll free: 1-888-872-8356 TTY: 1-800-555-7585 

 pass:[<email>travelocity@travelocity.com</email>] 

 link:$$http://www.travelocity.com$$[www.travelocity.com] 

 Travelodge 

 See: Wyndham Hotel Group Toll free: 1-800-835-2424 

 link:$$http://www.travelodge.com$$[www.travelodge.com] 

 True Value Company 

 Customer Service 8600 W. Bryn Mawr Ave. Chicago, IL 60631-3505 Toll free: 1-877-502-4641 

 link:$$http://www.truevalue.com$$[www.truevalue.com] 

 TruGreen Lawn Care 

 See: Service Master Company Toll free: 1-877-905-5147 

 pass:[<email>customercare@trugreenmail.com</email>] 

 link:$$http://www.trugreen.com$$[www.trugreen.com] 

 Turtle Wax, Inc. 

 Consumer Affairs PO Box 247 Willowbrook, IL 60559-0247 Toll free: 1-800-887-8539 

 link:$$http://www.turtlewax.com$$[www.turtlewax.com] 

 TV Guide 

 Customer Relations 1800 N. Highland Ave., 7th Floor New York, CA 90028 Toll free: 1-800-866-1400 

 pass:[<email>feedback@tvguide.com</email>] 

 link:$$http://www.tvguide.com$$[www.tvguide.com] 

 Twitter.com 

 1355 Market St., Suite 900 San Francisco, CA 94103 

 link:$$http://www.twitter.com$$[www.twitter.com] 

 Tyson Foods 

 Consumer Relations CP631 2200 Don Tyson Pkwy. Springdale, AR 72762 Toll free: 1-800-643-3410 

 link:$$http://www.tyson.com$$[www.tyson.com] 


=== U

 U-Haul International 

 Customer Service 2727 N. Central Ave. Phoenix, AZ 85004 Toll free: 1-800-789-3638 

 link:$$http://www.uhaul.com$$[www.uhaul.com] 

 Uniden America Corporation 

 Customer Service 4700 Amon Carter Blvd. Fort Worth, TX 76155 817-858-3300 Toll free: 1-800-297-1023 TTY: 1-800-874-9314 

 pass:[<email>cservice@uniden.com</email>] 

 link:$$http://www.uniden.com$$[www.uniden.com] 

 Unilever 

 Consumer Services 920 Sylvan Ave., 2nd Floor Englewood Cliffs, NJ 07632 Toll free: 1-800-298-5018 

 pass:[<email>comments@unilever.com</email>] 

 link:$$http://www.unilever.com$$[www.unilever.com] 

 Uniroyal Tires 

 Consumer Care Department PO Box 19001 Greenville, SC 29602-9001 Toll free: 1-877-458-5878 

 link:$$http://www.uniroyal.com$$[www.uniroyal.com] 

 United Airlines 

 Customer Care 900 Grand Plaza NHCCR Houston, TX 77067-4323 Toll free: 1-800-864-8331 Toll free: 1-800-335-2247 (Baggage) TTY: 1-800-323-0170 

 pass:[<email>customervoice9@united.com</email>] 

 link:$$http://www.ual.com$$[www.ual.com] 

 United Healthcare 

 Customer Service PO Box 740815 Atlanta, GA 30374-0815 Toll free: 1-888-545-5205 

 link:$$http://www.uhc.com$$[www.uhc.com] 

 United Online, Inc. 

 LNR Warner Center 21301 Burbank Blvd. Woodland Hills, CA 91367 

 link:$$http://www.unitedonline.com$$[www.unitedonline.com] 

 United Parcel Service (UPS) 

 Customer Service 55 Glenlake Pkwy., NE Atlanta, GA 30328 Toll free: 1-800-742-5877 TTY: 1-800-833-0056 

 link:$$http://www.ups.com$$[www.ups.com] 

 United Van Lines, Inc. 

 Claim Department One United Dr. St. Louis, MO 63026 Toll free: 1-800-948-4885 

 link:$$http://www.unitedvanlines.com$$[www.unitedvanlines.com] 

 Uno Chicago Grill 

 100 Charles Park Rd. Boston, MA 02132 617-323-9200 Toll free: 1-866-600-8667 

 pass:[<email>mail@unos.com</email>] 

 link:$$http://www.unos.com$$[www.unos.com] 

 US Airways 

 Customer Relations 4000 E. Sky Harbor Blvd. Phoenix, AZ 85034 480-693-0800 Toll free: 1-800-428-4322 TTY: 1-800-245-2966 

 link:$$http://www.usairways.com$$[www.usairways.com] 

 US Bancorp 

 US Bancorp Center 800 Nicollet Mall Minneapolis, MN 55402 Toll free: 1-800-872-2657 TTY: 1-800-685-5065 

 link:$$http://www.usbank.com$$[www.usbank.com] 


=== V

 The Valvoline Company 

 Customer Service PO Box 14000 Lexington, KY 40512 Toll free: 1-800-832-6825 

 link:$$http://www.valvoline.com$$[www.valvoline.com] 

 Verizon Communications, Inc. 

 (Contact the Verizon office in your geographic area) Toll free: 1-800-837-4966 Toll free: 1-800-922-0204 (Wireless Service) TTY: 1-800-974-6006 

 link:$$http://www.verizon.com$$[www.verizon.com] 

 Viacom, Inc. 

 1515 Broadway New York, NY 10036 212-258-6000 

 link:$$http://www.viacom.com$$[www.viacom.com] 

 Victoria&rsquo;s Secret Stores 

 Customer Service North American Office PO Box 16589 Columbus, OH 43216-6589 Toll free: 1-800-411-5116 TTY: 1-800-695-1788 

 pass:[<email>customercare@victoriassecret.com</email>] 

 link:$$http://www.victoriassecret.com$$[www.victoriassecret.com] 

 Virgin Atlantic Airways, Ltd. 

 PO Box 570 Canton, MA 02021 Toll free: 1-800-821-5438 TTY: 1-800-847-4641 

 pass:[<email>customer.relations.us@fly.virgin.com</email>] 

 link:$$http://www.virgin-atlantic.com$$[www.virgin-atlantic.com] 

 Virgin Mobile USA, LLP 

 Customer Resolutions 10 Independence Blvd. Warren, NJ 07059 Toll free: 1-888-322-1122 

 pass:[<email>ourteam@virginmobileusa.com</email>] 

 link:$$http://www.virginmobileusa.com$$[www.virginmobileusa.com] 

 Visa USA, Inc. 

 (Contact your issuing bank first) PO Box 194607 San Francisco, CA 94119-4607 Toll free: 1-800-847-2911 

 pass:[<email>askvisausa@visa.com</email>] 

 link:$$http://www.visa.com$$[www.visa.com] 

 Vonage 

 Customer Care 23 Main St. Holmdel, NJ 07733 Toll free: 1-866-243-4357 

 link:$$http://www.vonage.com$$[www.vonage.com] 

 The Vons Companies, Inc. 

 See: Safeway, Inc.  Toll free: 1-877-723-3929 

 link:$$http://www.vons.com$$[www.vons.com] 


=== W

 Wal-Mart Stores, Inc. 

 Customer Relations 702 S.W. 8th St. Bentonville, AR 72716 Toll free: 1-800-925-6278 Toll free: 1-800-966-6546 (Website Questions) 

 link:$$http://www.wal-mart.com$$[www.wal-mart.com] 

 Walgreens 

 Consumer Relations  200 Wilmot Rd.  Deerfield, IL 60015  Toll free: 1-800-925-4733 (In-store)  Toll free: 1-877-250-5823 (Online) 

 link:$$http://www.walgreens.com$$[www.walgreens.com] 

 Walter Drake, Inc. 

 Customer Service PO Box 3680 Oshkosh, WI 54903-3680 Toll free: 1-855-202-7393 

 link:$$http:wdrake.com$$[wdrake.com] 

 Wegman&rsquo;s Food Markets 

 Consumer Affairs 1500 Brooks Ave. PO Box 30844 Rochester, NY 14603-0844 Toll free: 1-800-934-6267 

 link:$$http://www.wegmans.com$$[www.wegmans.com] 

 Weight Watchers International 

 Corporate Affairs 11 Madison Ave., 17th Floor New York, NY 10010 Toll free: 1-800-651-6000 

 pass:[<email>customerservice@weightwatchers.com</email>] 

 link:$$http://www.weightwatchers.com$$[www.weightwatchers.com] 

 Wells Fargo Company 

 Customer Service PO Box 560948 Charlotte, NC 28256 Toll free: 1-800-869-3557 (General) TTY: 1-800-877-4833 

 link:$$http://www.wellsfargo.com$$[www.wellsfargo.com] 

 Wendy&rsquo;s International, Inc. 

 One Dave Thomas Blvd. Dublin, OH 43017 614-764-3100 ext. 2032 Toll free: 1-800-443-7266 

 link:$$http://www.wendys.com$$[www.wendys.com] 

 Western Union Financial Services, Inc. 

 Customer Advocate Dept. PO Box 6036 Englewood, CO 80112 Toll free: 1-800-222-5598 Toll free: 1-800-448-1492 (Fraud) 

 pass:[<email>customeradvocatedept@westernunion.com</email>] 

 link:$$http://www.westernunion.com$$[www.westernunion.com] 

 Westin 

 See: Startwood Hotels &amp; Resorts Worldwide, Inc. Toll free: 1-800-937-8461 

 link:$$http://www.westin.com$$[www.westin.com] 

 Whirlpool Corporation 

 Customer Service  553 Benson Rd.  Benton Harbor, MI 49022  Toll free: 1-800-688-2002  Toll free: 1-800-344-1274 (Maytag)  Toll free: 1-800-422-1230 (KitchenAid) 

 pass:[<email>whirlpool_customerexperience@whirlpool.com</email>] 

 link:$$http://www.whirlpool.com$$[www.whirlpool.com] 

 Whole Foods Markets, Inc. 

 550 Bowie St. Austin, TX 78703 512-542-0878 

 pass:[<email>customer.questions@wholefoods.com</email>] 

 link:$$http://www.wholefoods.com$$[www.wholefoods.com] 

 W Hotels 

 See: Starwood Hotels &amp; Resorts Worldwide, Inc. 

 link:$$http://www.whotels.com$$[www.whotels.com] 

 Williams-Sonoma, Inc. 

 10000 Covington Cross Dr. Las Vegas, NV 89144 Toll free: 1-877-812-6235 

 pass:[<email>CustomerService@williams-sonoma.com</email>] 

 link:$$http://www.williams-sonoma.com$$[www.williams-sonoma.com] 

 Winn-Dixie Stores, Inc. 

 Customer Service PO Box B Jacksonville, FL 32203-0297 Toll free: 1-866-946-6349 

 pass:[<email>Svc_WDCustResp@winn-dixie.com</email>] 

 link:$$http://www.winn-dixie.com$$[www.winn-dixie.com] 

 Winnebago Industries 

 Owner Relations PO Box 152 Forest City, IA 50436-0152 641-585-3535 Toll free: 1-800-537-1885 

 pass:[<email>info@winnabagoind.com</email>] 

 link:$$http://www.winnebagoind.com$$[www.winnebagoind.com] 

 Wrangler 

 Consumer Relations PO Box 21488 Greensboro, NC 27420-1488 Toll free: 1-888-784-8571 

 pass:[<email>wranglerweb@vfc.com</email>] 

 link:$$http://www.wrangler.com$$[www.wrangler.com] 

 Wyndham Hotel Group 

 Customer Service 1910 8th Ave. NE Aberdeen, SD 57401 Toll free: 1-800-347-7559 

 link:$$http://www.wyndhamworldwide.com$$[www.wyndhamworldwide.com] 


=== X

 Xbox 

 See: Microsoft Corporate Toll free: 1-800-469-9269 TTY: 1-866-740-9269 

 link:$$http://www.xbox.com$$[www.xbox.com] 

 Xerox Corporation 

 Customer Relations PO Box 4505 45 Glover Ave. Norwalk, CT 06856 203-968-3000 Toll free: 1-877-979-8498 (Customer Relations) Toll free: 1-888-339-7887 (Billing) Toll free: 1-800-821-2797 (Customer Technical Support) Toll free: 1-800-275-9376 

 pass:[<email>webmaster@xerox.com</email>] 

 link:$$http://www.xerox.com$$[www.xerox.com] 


=== Y

 Yahoo! Online 

 Customer Care  701 1st Ave.  Sunnyvale, CA 94089  408-349-5070 (Customer Care)  Toll free: 1-866-562-7219 (Customer Care) 

 pass:[<email>cc-advoc@yahoo-inc.com</email>] 

 link:$$http://www.yahoo.com$$[www.yahoo.com] 

 Yamaha Motor Corporation 

 Customer Relations 6555 Katella Ave. Cypress, CA 90630 714-761-7435 Toll free: 1-800-962-7926 (Customer Relations) Toll free: 1-800-252-5265 (Yamaha Card) 

 link:$$http://www.yamaha-motor.com$$[www.yamaha-motor.com] 

 YUM! Brands, Inc. 

 Customer Relations  1900 Colonel Sanders Ln.  Louisville, KY 40213  Toll free: 1-800-225-5532 (KFC)  Toll free: 1-800-948-8488 (Pizza Hut)  Toll free: 1-800-822-6235 (Taco Bell) 

 link:$$http://www.yum.com$$[www.yum.com] 


=== Z

 Zales Jewelers 

 Customer Service PO Box 152771 Irving, TX 75038-1003 Toll free: 1-800-311-5393 

 pass:[<email>customersupport@zales.com</email>] 

 link:$$http://www.zales.com$$[www.zales.com] 

 link:$$http:Zappos.com$$[Zappos.com] 

 Customer Loyalty 2280 Corporate Circle, Suite 100 Henderson, NV 89074 Toll free: 1-800-927-7671 

 pass:[<email>cs@zappos.com</email>] 

 link:$$http://www.zappos.com$$[www.zappos.com] 

 Zenith Electronics Corp. 

 Customer Service 2000 Millbrook Dr. Lincolnshire, IL 60069 Toll free: 1-877-993-6484 

 link:$$http://www.zenith.com$$[www.zenith.com] 

