[[national_consumer_organizations]]

== National Consumer Organizations


.Contacting National Consumer Organizations
****
National Consumer Organizations are committed to  assisting consumers and protecting their rights via  advocacy, research, and outreach efforts. Some  organizations assist individuals with problems, while  others collect consumer complaints and statistics to  better understand consumer trends and direct their  advocacy efforts. 


****


*AARP* 

601 E St., NW Washington, DC 20049 Toll free: 1-888-687-2277 Toll free: 1-800-646-2283 (Fraud Fighter Call Center) TTY: 1-877-434-7598 

pass:[<email>member@aarp.org</email>] 

link:$$http://www.aarp.org$$[www.aarp.org] 

AARP is committed to addressing those consumer problems and issues that especially impact the financial security of people 50 years and older. Through advocacy at the federal and state levels, AARP works to make the marketplace safer for all consumers. AARP also employs a variety of strategies to help AARP members protect themselves from fraud and deceptive practices. 

*American Council on Consumer Interests (ACCI)* 

PO Box 2528 Tarpon Springs, FL 34688 

link:$$http://www.consumerinterests.org$$[www.consumerinterests.org] 

ACCI is a consumer policy research and education organization consisting of a worldwide community of researchers, educators, and related professionals. 

*American Council on Science and Health (ACSH)* 

1995 Broadway, Suite 202 New York, NY 10023-5882 212-362-7044 

pass:[<email>acsh@acsh.org</email>] 

link:$$http://www.acsh.org$$[www.acsh.org] 

ACSH provides consumers with up-to-date scientifically sound information on the relationship between human health and chemicals, foods, lifestyles, and the environment. Booklets and special reports on a variety of topics are available. 

*Center for Auto Safety (CAS)* 

1825 Connecticut Ave., NW, Suite 330 Washington, DC 20009-5708 202-328-7700 

link:$$http://www.autosafety.org$$[www.autosafety.org] 

CAS advocates on behalf of consumers in auto safety and quality, fuel efficiency, emissions, and related issues. 

*Center for Science in the Public Interest (CSPI)* 

1220 L St., NW, Suite 300 Washington, DC 20005 202-332-9110 

pass:[<email>cspi@cspinet.org</email>] 

link:$$http://www.cspinet.org$$[www.cspinet.org] 

CSPI conducts research, education, and advocacy on nutrition, health, food safety, and related issues. It also provides consumers with current information about their health and well being via their monthly _Nutrition Action Healthletter_. 

*Center for the Study of Services (CSS)* 

1625 K St., NW, 8th Floor Washington, DC 20006 Toll free: 1-800-213-7283 

link:$$http://www.checkbook.org$$[www.checkbook.org] 

CSS publishes _Consumers CHECKBOOK_ so that consumers can evaluate the quality and prices of service firms and stores in their local area. 

*Coalition Against Insurance Fraud* 

1012 14th St., NW, Suite 200 Washington, DC 20005 202-393-7330 

pass:[<email>info@insurancefraud.org</email>] 

link:$$http://www.insurancefraud.org$$[www.insurancefraud.org] 

The Coalition is an alliance of consumer groups, government agencies, and insurance companies dedicated to combating all forms of insurance fraud through advocacy and public information. 

*Consumer Action* 

221 Main St., Suite 480 San Francisco, CA 94105 415-777-9635 (Consumer Complaints) TTY: 415-777-9456 

pass:[<email>info@consumer-action.org</email>] 

link:$$http://www.consumer-action.org$$[www.consumer-action.org] 

Consumer Action is an education and advocacy organization specializing in credit, finance, and telecommunications issues. Consumer Action offers a multi-lingual consumer complaint hotline, and consumer education materials in several languages. Community-based organizations can receive these free publications in bulk. 

*Consumer Federation of America (CFA)* 

1620 I St., NW, Suite 200 Washington, DC 20006 202-387-6121 

pass:[<email>cfa@consumerfed.org</email>] 

link:$$http://www.consumerfed.org$$[www.consumerfed.org] 

link:$$http://www.idtheftinfo.org$$[www.idtheftinfo.org] 

CFA is a consumer advocacy and education organization. It represents consumer interests on issues such as, telephone service, insurance and financial services, product safety, indoor air pollution, health care, product liability, and utility rates. It develops and distributes studies of various consumer issues, as well as printed consumer guides. 

*Consumers Reports* 

101 Truman Ave. Yonkers, NY 10703-1057 914-378-2000 914-378-2455 (Consumer Policy Institute)  Toll free: 1-800-879-9848 (__Consumer Reports__ magazine)  Toll free: 1-866-208-9427 (ConsumerReports.org) 

link:$$http://www.consumersunion.org$$[www.consumersunion.org] 

link:$$http://www.consumerreports.org$$[www.consumerreports.org] 

Consumer Reports publishes a magazine of the same name. It is an independent, nonprofit testing and information organization serving only consumers. _Consumer Reports_ is a comprehensive source for unbiased advice about products and services, personal finance, health and nutrition, and other categories based on their independent tests. 

*Families USA* 

1201 New York Ave., NW, Suite 1100 Washington, DC 20005 202-628-3030 

pass:[<email>info@familiesusa.org</email>] 

link:$$http://www.familiesusa.org$$[www.familiesusa.org] 

Families USA is a national, nonprofit membership organization committed to affordable, high quality health and long-term care. Families USA creates materials to educate and mobilize consumers on healthcare issues. 

*Funeral Consumers Alliance (FCA)* 

33 Patchen Rd. South Burlington, VT 05403 802-865-8300 

pass:[<email>fca@funerals.org</email>] 

link:$$http://www.funerals.org$$[www.funerals.org] 

FCA protects a consumer&rsquo;s right to choose a dignified, meaningful, affordable funeral. In addition to informing the public about their available options and rights, FCA will assist in mediating complaints. The local affiliates around the country conduct funeral price surveys, and counsel the general public. 

*Jump$tart Coalition for Personal Financial Literacy* 

919 18th St., NW, Suite 300 Washington, DC 20006 202-466-8604 Toll free: 1-888-453-3822 

pass:[<email>info@jumpstartcoalition.org</email>] 

link:$$http://www.jumpstart.org$$[www.jumpstart.org] 

Jump$tart is a national coalition of organizations dedicated to improving the financial literacy of prekindergarten through college-age youth by providing advocacy, research standards, and educational resources. Jump$tart strives to prepare youth for life-long successful financial decision-making. 

*Kids in Danger (KID)* 

116 W. Illinois St., Suite 4E Chicago, IL 60654 312-595-0649 

pass:[<email>email@kidsindanger.org</email>] 

link:$$http://www.kidsindanger.org$$[www.kidsindanger.org] 

KID is dedicated to educating parents and caregivers about dangerous children&rsquo;s products. 

*The Medicare Rights Center* 

520 8th Ave., North Wing, 3rd Floor New York City, NY 10018 Toll free: 1-800-333-4114 (Consumer Helpline) 

pass:[<email>info@medicarerights.org</email>] 

link:$$http://www.medicarerights.org$$[www.medicarerights.org] 

The Medicare Rights Center works to ensure access to affordable health care for older adults and people with disabilities through counseling, advocacy, and educational programs. It works with clients nationwide through a phone hotline, Internet services, a large volunteer network and community programs. 

*National Community Reinvestment Coalition (NCRC)* 

727 15th St., NW, Suite 900 Washington, DC 20005-2112 202-628-8866 

link:$$http://www.ncrc.org$$[www.ncrc.org] 

NCRC works to end discriminatory banking practices in underserved communities. It also offers a housing counseling network to help prospective and current homeowners. 

*National Consumer Law Center (NCLC)* 

Seven Winthrop Square Boston, MA 02110-1245 617-542-8010 

pass:[<email>consumerlaw@nclc.org</email>] 

link:$$http://www.consumerlaw.org$$[www.consumerlaw.org] 

NCLC is an advocacy and research organization focusing on the needs of low-income and other disadvantaged consumers. The NCLC works for fairness in financial services, ending predatory lending, and stopping consumer fraud. The NCLC doesn&rsquo;t work with individual consumers, but offers consumer brochures on their website. 

*The National Consumer Protection Technical Resource Center* 

Senior Medicare Patrol Resource Center (SMP) PO Box 388 Waterloo, IA 50704-0388 Toll free: 1-877-808-2468 

pass:[<email>info@smpresource.org</email>] 

link:$$http://www.smpresource.org$$[www.smpresource.org] 

The Center is funded by the U.S. Administration on Aging to support community based Senior Medicare Patrol Programs (SMP). The SMP projects help Medicare and Medicaid beneficiaries avoid, detect and prevent healthcare fraud and abuse. 

*National Consumers League (NCL)* 

1701 K St., NW, Suite 1200 Washington, DC 20006 202-835-3323 

link:$$http://www.nclnet.org$$[www.nclnet.org] 

link:$$http://www.fakechecks.org$$[www.fakechecks.org] 

link:$$http://www.fraud.org$$[www.fraud.org] 

link:$$http://www.lifesmarts.org$$[www.lifesmarts.org] 

The NCL provides government, businesses, and other organizations with the consumers perspective on consumer issues and workplace concerns. The League sponsors the LifeSmarts competition, which is designed to develop consumer and marketplace knowledge of teenagers. NCL also works to provide consumers with the information they need to avoid becoming victims of telemarketing and Internet fraud and to help them get their complaints to law enforcement. 

*National Council on the Aging (NCOA)* 

1901 L St., NW, 4th Floor Washington, DC 20036 202-479-1200 Toll free: 1-800-424-9046 TTY: 202-479-6674 

pass:[<email>info@ncoa.org</email>] 

link:$$http://www.ncoa.org$$[www.ncoa.org] 

NCOA is a national voice for older adults — especially those who are vulnerable and disadvantaged — and the community organizations that serve them. 

