[[state_banking_authorities]]

== State Banking Authorities


.Contacting Your Local Banking Authority
****
The officials listed below regulate and supervise  state-chartered banks. Many of them handle or refer problems  and complaints about other types of financial institutions as well.  Some also answer general questions about banking and consumer credit.  If you are dealing with a federally-chartered bank, check Federal  Agencies on page 96. Also see the chart in the Banking section on page 7. 


****



=== Alabama

*State Banking Department* 

PO Box 4600 Montgomery, AL 36103-4600 334-242-3452 Toll free: 1-866-465-2279 

link:$$http://www.banking.alabama.gov$$[www.banking.alabama.gov] 


=== Alaska

*Department of Commerce, Community and Economic Development* 

Division of Banking and Securities PO Box 110807 Juneau, AK 99811-0807 907-465-2521 Toll free: 1-888-925-2521 TTY: 907-465-5437 

pass:[<email>dbsc@commerce.state.ak.us</email>] 

link:$$http://www.commerce.state.ak.us/bsc/home.htm$$[www.commerce.state.ak.us/bsc/home.htm] 


=== Arizona

*Department of Financial Institutions* 

2910 N. 44th St., Suite 310 Phoenix, AZ 85018 602-771-2800 

pass:[<email>consumeraffairs@azdfi.gov</email>] 

link:$$http://www.azdfi.gov$$[www.azdfi.gov] 


=== Arkansas

*State Bank Department* 

400 Hardin Rd., Suite 100 Little Rock, AR 72211 501-324-9019 

pass:[<email>asbd@banking.state.ar.us</email>] 

link:$$http://www.arkansas.gov/bank$$[www.arkansas.gov/bank] 


=== California

*State Department of Financial Institutions* 

45 Fremont St., Suite 1700 San Francisco, CA 94105-2219 415-263-8500 916-322-0622 (Consumer Services) Toll free: 1-800-622-0620 (CA) 

pass:[<email>consumer@dfi.ca.gov</email>] 

link:$$http://www.dfi.ca.gov$$[www.dfi.ca.gov] 

*State Department of Financial Institutions- Los Angeles* 

300 S. Spring St., Suite 15513 Los Angeles, CA 90013-1259 213-897-2085 916-322-0622 (Consumer Services) Toll free: 1-800-622-0620 (CA) 

pass:[<email>consumer@dfi.ca.gov</email>] 

link:$$http://www.dfi.ca.gov$$[www.dfi.ca.gov] 

*State Department of Financial Institutions- Sacramento* 

1810 13th St.  Sacramento, CA 95811  916-322-5966  916-322-0622 (Consumer Services)  Toll free: 1-800-622-0620 (CA) 

pass:[<email>consumer@dfi.ca.gov</email>] 

link:$$http://www.dfi.ca.gov$$[www.dfi.ca.gov] 

*State Department of Financial Institutions- San Diego* 

7575 Metropolitan Dr., Suite 108 San Diego, CA 92108 619-682-7227 916-322-0622 (Consumer Services) Toll free: 1-800-622-0620 (CA) 

pass:[<email>consumer@dfi.ca.gov</email>] 

link:$$http://www.dfi.ca.gov$$[www.dfi.ca.gov] 


=== Colorado

*Department of Regulatory Agencies* 

Division of Banking 1560 Broadway, Suite 975 Denver, CO 80202 303-894-7575 

pass:[<email>banking@dora.state.co.us</email>] 

link:$$http://www.dora.state.co.us/banking$$[www.dora.state.co.us/banking] 


=== Connecticut

*Connecticut Department of Banking* 

Financial Institutions Division 260 Constitution Plaza Hartford, CT 06103 860-240-8180 Toll free: 1-800-831-7225 

link:$$http://www.state.ct.us/dob$$[www.state.ct.us/dob] 


=== Delaware

*Office of the State Bank Commissioner* 

555 E. Loockerman St., Suite 210 Dover, DE 19901 302-739-4235 

link:$$http://www.banking.delaware.gov$$[www.banking.delaware.gov] 


=== District Of Columbia

*Department of Insurance, Securities and Banking* 

Attn: Consumer Protection Advocate 810 1st St., NE, Suite 701 Washington, DC 20002 

pass:[<email>disb@dc.gov</email>] 

link:$$http://www.disb.dc.gov$$[www.disb.dc.gov] 


=== Florida

*Office of Financial Regulation* 

Division of Financial Institutions Consumer Assistance Group 200 E. Gaines St. Tallahassee, FL 32399-0371 850-410-9800 Toll free: 1-800-848-3792 (FL) 

link:$$http://www.flofr.com$$[www.flofr.com] 


=== Georgia

*Department of Banking and Finance* 

2990 Brandywine Rd., Suite 200 Atlanta, GA 30341-5565 770-986-1633 Toll free: 1-888-986-1633 (GA) link:$$http://www.dbf.georgia.gov$$[www.dbf.georgia.gov] 


=== Hawaii

*Department of Commerce and Consumer Affairs* 

Division of Financial Institutions PO Box 2054 Honolulu, HI 96805 808-586-2820 808-274-3141 (Kauai) 808-984-2400, 6-2820# (Maui) 808-974-4000, 6-2820# (Hawaii) Toll free: 1-800-468-4644 

pass:[<email>dfi@dcca.hawaii.gov</email>] 

link:$$http://www.hawaii.gov/dcca/dfi$$[www.hawaii.gov/dcca/dfi] 


=== Idaho

*Department of Finance* 

Financial Institutions Bureau PO Box 83720 Boise, ID 83720-0031 208-332-8005 Toll free: 1-888-346-3378 (ID) 

pass:[<email>finance@finance.idaho.gov</email>] 

link:$$http://www.finance.idaho.gov$$[www.finance.idaho.gov] 


=== Illinois

*Department of Financial and Professional Regulation* 

Division of Banking 320 W. Washington St. Springfield, IL 62786 217-782-3000 Toll free: 1-800-532-8785 TTY: 217-524-6644 

link:$$http://www.idfpr.com$$[www.idfpr.com] 


=== Indiana

*Department of Financial Institutions* 

30 S. Meridian St., Suite 300 Indianapolis, IN 46204 317-232-3955 Toll free: 1-800-382-4880 (IN) 

link:$$http://www.in.gov/dfi$$[www.in.gov/dfi] 


=== Iowa

*Division of Banking* 

200 E. Grand Ave., Suite 300 Des Moines, IA 50309-1827 515-281-4014 

pass:[<email>IDOBcomplaints@idob.state.ia.us</email>] 

link:$$http://www.idob.state.ia.us$$[www.idob.state.ia.us] 


=== Kansas

*Office of the State Bank Commissioner* 

700 S.W. Jackson St., Suite 300 Topeka, KS 66603-3714 785-296-2266 

pass:[<email>complaints@osbckansas.org</email>] 

link:$$http://www.osbckansas.org$$[www.osbckansas.org] 


=== Kentucky

*Department of Financial Institutions* 

1025 Capitol Center Dr., Suite 200 Frankfort, KY 40601 502-573-3390 Toll free: 1-800-223-2579 

pass:[<email>kfi@ky.gov</email>] 

link:$$http://www.kfi.ky.gov$$[www.kfi.ky.gov] 


=== Louisiana

*Office of Financial Institutions* 

PO Box 94095 Baton Rouge, LA 70804-9095 225-925-4660 

pass:[<email>complaints@ofi.la.gov</email>] 

link:$$http://www.ofi.state.la.us$$[www.ofi.state.la.us] 


=== Maine

*Bureau of Financial Institutions* 

Consumer Outreach Program 36 State House Station Augusta, ME 04333-0036 207-624-8570 Toll free: 1-800-965-5235 

pass:[<email>BFI.info@maine.gov</email>] 

link:$$http://www.maine.gov/pfr/financialinstitutions$$[www.maine.gov/pfr/financialinstitutions] 


=== Maryland

*Department of Labor, Licensing and Regulation* 

Commissioner of Financial Regulation 500 N. Calvert St., Suite 402 Baltimore, MD 21202 410-230-6077 (Consumer Services) Toll free: 1-888-784-0136 (MD) 

pass:[<email>CFRComplaints@dllr.state.md.us</email>] 

link:$$http://www.dllr.state.md.us/finance$$[www.dllr.state.md.us/finance] 


=== Massachusetts

*Division of Banks* 

1000 Washington St. 10th Floor Boston, MA 02118-6400 617-956-1500 Toll free: 1-800-495-2265 (MA) TTY: 617-956-1577 

pass:[<email>dobconsumer.assistan@state.ma.us</email>] 

link:$$http://www.mass.gov/dob$$[www.mass.gov/dob] 


=== Michigan

*Office of Financial and Insurance Regulation* 

PO Box 30220 Lansing, MI 48909-7720 517-373-0220 Toll free: 1-877-999-6442 (MI) 

pass:[<email>ofir-fin-info@michigan.gov</email>] 

link:$$http://www.michigan.gov/ofir$$[www.michigan.gov/ofir] 


=== Minnesota

*Department of Commerce* 

Division of Financial Institutions 85 7th Pl. E, Suite 500 St. Paul, MN 55101 651-296-2135 TTY: 651-296-2860 

pass:[<email>general.commerce@state.mn.us</email>] 

link:$$http://mn.gov/commerce/$$[mn.gov/commerce] 


=== Mississippi

*Department of Banking and Consumer Finance* 

901 Woolfolk Building, Suite A 501 N. West St. Jackson, MS 39201 601-359-1031 Toll free: 1-800-844-2499 (MS) 

link:$$http://www.dbcf.state.ms.us$$[www.dbcf.state.ms.us] 


=== Missouri

*Department of Finance* 

Harry S. Truman State Office Building PO Box 716 Room 630 Jefferson City, MO 65102 573-751-3242 

pass:[<email>finance@dof.mo.gov</email>] 

link:$$http://www.finance.mo.gov$$[www.finance.mo.gov] 


=== Montana

*Division of Banking and Financial Institutions* 

PO Box 200546 Helena, MT 59620 406-841-2920 TTY: 406-841-2974 

link:$$http://www.banking.mt.gov$$[www.banking.mt.gov] 


=== Nebraska

*Department of Banking and Finance* 

PO Box 95006 Lincoln, NE 68509-5006 402-471-2171 Toll free: 1-877-471-3445 

link:$$http://www.ndbf.ne.gov$$[www.ndbf.ne.gov] 


=== Nevada

*Department of Business and Industry* 

Financial Institutions Division 2785 E. Desert Inn Rd. Las Vegas, NV 89121 702-486-4120 

link:$$http://www.fid.state.nv.us$$[www.fid.state.nv.us] 


=== New Hampshire

*State Banking Department* 

53 Regional Dr., Suite 200 Concord, NH 03301 603-271-3561 Toll free: 1-800-437-5991 TTY: 1-800-735-2964 

pass:[<email>NHBD@Banking.State.NH.US</email>] 

link:$$http://www.nh.gov/banking$$[www.nh.gov/banking] 


=== New Jersey

*Department of Banking and Insurance* 

Division of Banking PO Box 471 Trenton, NJ 08625-0471 609-292-7272 Toll free: 1-800-446-7467 

link:$$http://www.state.nj.us/dobi$$[www.state.nj.us/dobi] 


=== New Mexico

*Regulation and Licensing Department* 

Financial Institutions Division 2550 Cerrillos Rd., 3rd Floor Santa Fe, NM 87505 505-476-4885 

pass:[<email>rld.fid@state.nm.us</email>] 

link:$$http://www.rld.state.nm.us/financialinstitutions$$[www.rld.state.nm.us/financialinstitutions] 


=== New York

*Banking Department* 

Consumer Help Unit 25 Beaver St. New York, NY 10004-2319 212-709-3530 Toll free: 1-877-226-5697 (NY) 

pass:[<email>consumer@banking.state.ny.us</email>] 

link:$$http://www.banking.state.ny.us$$[www.banking.state.ny.us] 


=== North Carolina

*Commissioner of Banks* 

4309 Mail Service Center Raleigh, NC 27699-4309 Toll free: 1-888-384-3811 

link:$$http://www.nccob.org$$[www.nccob.org] 


=== North Dakota

*Department of Financial Institutions* 

2000 Schafer St., Suite G Bismarck, ND 58501-1204 701-328-9933 TTY: 1-800-366-6888 (ND) 

pass:[<email>dfi@nd.gov</email>] 

link:$$http://www.nd.gov/dfi$$[www.nd.gov/dfi] 


=== Ohio

*Department of Commerce* 

Division of Financial Institutions Consumer Complaints 77 S. High St., 21st Floor Columbus, OH 43215-6120 614-728-8400 Toll free: 1-866-278-0003 TTY: 1-800-750-0750 

pass:[<email>webdfi-cf@com.state.oh.us</email>] 

link:$$http://www.com.ohio.gov/fiin$$[www.com.ohio.gov/fiin] 


=== Oklahoma

*State Banking Department* 

2900 N. Lincoln Blvd. Oklahoma City, OK 73105 405-521-2782 

link:$$http://www.ok.gov/banking$$[www.ok.gov/banking] 


=== Oregon

*Department of Consumer and Business Services* 

Division of Finance and Corporate Securities PO Box 14480 Salem, OR 97309-0405 503-378-4140 Toll free: 1-866-814-9710 (OR) 

pass:[<email>dcbs.dfcsmail@state.or.us</email>] 

link:$$http:dfcs.oregon.gov$$[dfcs.oregon.gov] 


=== Pennsylvania

*Department of Banking* 

Consumer Services 17 N. 2nd St., Suite 1300 Harrisburg, PA 17101-2290 717-787-1854 Toll free: 1-800-722-2657 TTY: 1-800-679-5070 

link:$$http://www.banking.state.pa.us$$[www.banking.state.pa.us] 


=== Puerto Rico

*Oficina del Comisionado de Instituciones Financieras* 

PO Box 11855 San Juan, PR 00910-3855 787-723-3131 

link:$$http://www.ocif.gobierno.pr$$[www.ocif.gobierno.pr] 


=== Rhode Island

*Department of Business Regulation* 

Division of Banking 1511 Pontiac Ave., Bldg. 68-2 Cranston, RI 02920 401-462-9500 

pass:[<email>bankinquiry@dbr.ri.gov</email>] 

link:$$http://www.dbr.state.ri.us$$[www.dbr.state.ri.us] 


=== South Carolina

*Office of the Commissioner of Banking* 

State Board of Financial Institutions 1205 Pendleton St., Suite 305 Columbia, SC 29201 803-734-2001 

link:$$http://www.banking.sc.gov$$[www.banking.sc.gov] 


=== South Dakota

*Department of Labor and Regulation* 

Division of Banking 217 1/2 W. Missouri Ave. Pierre, SD 57501-4590 605-773-3421 

pass:[<email>banking@state.sd.us</email>] 

link:$$http://www.dlr.sd.gov/reg/bank$$[www.dlr.sd.gov/reg/bank] 


=== Tennessee

*Department of Financial Institutions* 

Consumer Resources Division 414 Union St., Suite 1000 Nashville, TN 37219 615-253-2023 Toll free: 1-800-778-4215 (TN) 

pass:[<email>TDFI.ConsumerResources@tn.gov</email>] 

link:$$http://www.tennessee.gov/tdfi$$[www.tennessee.gov/tdfi] 


=== Texas

*Department of Banking* 

2601 N. Lamar Blvd., Suite 201 Austin, TX 78705 512-475-1300 Toll free: 1-877-276-5554 (Consumer Hotline) 

pass:[<email>consumer.complaints@dob.texas.gov</email>] 

link:$$http://www.banking.state.tx.us$$[www.banking.state.tx.us] 


=== Utah

*Department of Financial Institutions* 

PO Box 146800 Salt Lake City, UT 84114-6800 801-538-8830 

link:$$http://www.dfi.utah.gov$$[www.dfi.utah.gov] 


=== Vermont

*Department of Financial Regulation* 

Banking Division 89 Main St. Montpelier, VT 05620-3101 802-828-3307 Toll free: 1-888-568-4547 (VT) 

pass:[<email>dfr.bnkconsumer@state.vt.us</email>] 

link:$$http://www.dfr.vermont.gov$$[www.dfr.vermont.gov] 


=== Virgin Islands

*Office of the Lieutenant Governor* 

Division of Banking and Insurance 5049 Kongens Gade St. Thomas, VI 00802 340-774-7166 

link:$$http://www.ltg.gov.vi$$[www.ltg.gov.vi] 


=== Virginia

*State Corporation Commission* 

Bureau of Financial Institutions PO Box 640 Richmond, VA 23218 804-371-9657 804-371-9705 (Complaints) Toll free: 1-800-552-7945 (VA) TTY: 804-371-9206 

link:$$http://www.scc.virginia.gov$$[www.scc.virginia.gov] 


=== Washington

*Department of Financial Institutions* 

Division of Banks PO Box 41200 Olympia, WA 98504-1200 360-902-8704 Toll free: 1-877-746-4334 TTY: 360-664-8126 

link:$$http://www.dfi.wa.gov$$[www.dfi.wa.gov] 


=== West Virginia

*Division of Banking* 

900 Pennsylvania Ave. Suite 306 Charleston, WV 25302 304-558-2294 

link:$$http://www.wvdob.org$$[www.wvdob.org] 


=== Wisconsin

*Department of Financial Institutions* 

Bureau of Consumer Affairs PO Box 8041 Madison, WI 53708-8041 608-264-7969 TTY: 608-266-8818 

link:$$http://www.wdfi.org$$[www.wdfi.org] 


=== Wyoming

*Division of Banking* 

Herschler Building, 3rd Floor, East 122 W. 25th St. Cheyenne, WY 82002 307-777-7797 

pass:[<email>doa-dob-web@wyo.gov</email>] 

link:$$audit.state.wy.us/banking$$[audit.state.wy.us/banking] 

