[[state_securities_administrators]]

== State Securities Administrators


.Contacting Your Local Securities Administrator
****
State securities regulators protect the investing public.  Each state has its own laws and regulations for securities  brokers and securities, including stocks, mutual funds,  commodities, real estate, and more. The agencies listed  below enforce these laws and regulations. They also license  securities professionals, register securities, and investigate  consumer complaints. While these agencies do not provide  investment advice, many of them offer educational resources  so investors can make informed investment decisions. 

If you have a question or complaint about an investment,  call the company or bank involved. If you are not satisfied  with the response you get, call your state securities agency.  See the Investing section in Part I of this Handbook for  additional advice and sources of assistance (p. 35). 


****



=== Alabama

*Securities Commission* 

PO Box 304700 Montgomery, AL 36130-4700 334-242-2984 Toll free: 1-800-222-1253 (AL) 

pass:[<email>asc@asc.alabama.gov</email>] 

link:$$http://www.asc.state.al.us$$[www.asc.state.al.us] 


=== Alaska

*Department of Commerce, Community and Economic Development* 

Division of Banking and Securities PO Box 110807 Juneau, AK 99811-0807 907-465-2521 Toll free: 1-888-925-2521 (AK) TTY: 907-465-5437 

pass:[<email>dbsc@alaska.gov</email>] 

link:$$http://www.commerce.state.ak.us$$[www.commerce.state.ak.us] 


=== Arizona

*Arizona Corporation Commission* 

Securities Division 1300 W. Washington St., 3rd Floor Phoenix, AZ 85007 602-542-4242 Toll free: 1-866-837-4399 (AZ) 

pass:[<email>info@azinvestor.gov</email>] 

link:$$http://www.azinvestor.gov$$[www.azinvestor.gov] 


=== Arkansas

*Securities Department* 

Heritage West Building 201 E. Markham St., Suite 300 Little Rock, AR 72201-1692 501-324-9260 Toll free: 1-800-981-4429 

pass:[<email>info@securities.arkansas.gov</email>] 

link:$$http://www.securities.arkansas.gov$$[www.securities.arkansas.gov] 


=== California

*Department of Corporations* 

Consumer Services Office 1515 K St., Suite 200 Sacramento, CA 95814 Toll free: 1-866-275-2677 TTY: 1-800-735-2966 

link:$$http://www.corp.ca.gov$$[www.corp.ca.gov] 


=== Colorado

*Department of Regulatory Agencies* 

Division of Securities 1560 Broadway, Suite 900 Denver, CO 80202 303-894-2320 TTY: 1-800-659-2656 

pass:[<email>securities@dora.state.co.us</email>] 

link:$$http://www.dora.state.co.us/securities$$[www.dora.state.co.us/securities] 


=== Connecticut

*Department of Banking* 

Securities and Business Investments Division 260 Constitution Plaza Hartford, CT 06103-1800 860-240-8230 Toll free: 1-800-831-7225 

link:$$http://www.ct.gov/dob$$[www.ct.gov/dob] 


=== Delaware

*Division of Securities* 

Carvel State Office Building 820 N. French St., 5th Floor Wilmington, DE 19801 302-577-8424 TTY: 302-577-5783 

link:$$http://www.state.de.us/securities$$[www.state.de.us/securities] 


=== District Of Columbia

*Department of Insurance, Securities and Banking* 

810 1st St., NE, Suite 701 Attn: Consumer Protection Advocate Washington, DC 20002 202-727-8000 

pass:[<email>disb@dc.gov</email>] 

link:$$http:disb.dc.gov$$[disb.dc.gov] 


=== Florida

*Office of Financial Regulation* 

Division of Securities Consumer Assistance Group 200 E. Gaines St. Tallahassee, FL 32399-0375 850-410-9500 Toll free: 1-800-848-3792 (FL) 

link:$$http://www.flofr.com$$[www.flofr.com] 


=== Georgia

*Office of the Secretary of State* 

Division of Securities and Business Regulation 237 Coliseum Dr. Macon, GA 31217-3858 478-207-2440 

link:$$http://www.sos.ga.gov/securities$$[www.sos.ga.gov/securities] 


=== Hawaii

*Department of Commerce and Consumer Affairs* 

Securities Enforcement Branch Business Registration Division PO Box 40 Honolulu, HI 96810 808-586-2744 Toll free: 1-877-477-2267 

pass:[<email>seb@dcca.hawaii.gov</email>] 

link:$$http://www.hawaii.gov/dcca/sec$$[www.hawaii.gov/dcca/sec] 


=== Idaho

*Department of Finance* 

Securities Bureau PO Box 83720 Boise, ID 83720-0031 208-332-8000 Toll free: 1-888-346-3378 (ID) 

pass:[<email>finance@finance.idaho.gov</email>] 

link:$$http://www.finance.idaho.gov$$[www.finance.idaho.gov] 


=== Illinois

*Secretary of State* 

Securities Department Jefferson Terrace 300 W. Jefferson St., Suite 300A Springfield, IL 62702 217-782-2256 Toll free: 1-800-628-7937 (IL) 

link:$$http://www.cyberdriveillinois.com$$[www.cyberdriveillinois.com] 


=== Indiana

*Office of the Secretary of State* 

Securities Division 302 W. Washington St., Room E111 Indianapolis, IN 46204 317-232-6681 Toll free: 1-800-223-8791 (IN) 

link:$$http://www.in.gov/sos/securities/index.htm$$[www.in.gov/sos/securities/index.htm] 


=== Iowa

*Securities Bureau* 

340 Maple St. Des Moines, IA 50319 515-281-5705 Toll free: 1-877-955-1212 (IA) 

link:$$http://www.iid.state.ia.us/securities$$[www.iid.state.ia.us/securities] 


=== Kansas

*Office of the Securities Commissioner* 

109 S.W. 9th St., Suite 600 Topeka, KS 66612 785-296-3307 Toll free: 1-800-232-9580 (KS) 

link:$$http://www.ksc.ks.gov$$[www.ksc.ks.gov] 


=== Kentucky

*Department of Financial Institutions* 

Division of Securities 1025 Capitol Center Dr., Suite 200 Frankfort, KY 40601-3868 502-573-3390 Toll free: 1-800-223-2579 

pass:[<email>kfi@ky.gov</email>] 

link:$$http://www.kfi.ky.gov$$[www.kfi.ky.gov] 


=== Louisiana

*Office of Financial Institutions* 

Securities Division PO Box 94095 Baton Rouge, LA 70804-9095 225-925-4660 

pass:[<email>ofila@ofi.louisiana.gov</email>] 

link:$$http://www.ofi.state.la.us$$[www.ofi.state.la.us] 


=== Maine

*Department of Professional and Financial Regulation* 

Office of Securities 121 State House Station Augusta, ME 04333-0121 207-624-8551 Toll free: 1-877-624-8551 (ME) 

link:$$http://www.maine.gov/pfr/securities$$[www.maine.gov/pfr/securities] 


=== Maryland

*Office of the Attorney General* 

Securities Division 200 Saint Paul Pl. Baltimore, MD 21202-2020 410-576-6360 Toll free: 1-888-743-0023 (MD) TTY: 410-576-6372 

pass:[<email>securities@oag.state.md.us</email>] 

link:$$http://www.oag.state.md.us$$[www.oag.state.md.us] 


=== Massachusetts

Office of the Secretary of the Commonwealth 

Securities Division One Ashburton Pl., 17th Floor Room 1701 McCormack Building Boston, MA 02108 617-727-3548 Toll free: 1-800-269-5428 (MA) TTY: 617-878-3889 

pass:[<email>securities@sec.state.ma.us</email>] 

link:$$http://www.sec.state.ma.us/sct/sctidx.htm$$[www.sec.state.ma.us/sct/sctidx.htm] 


=== Michigan

*Office of Financial and Insurance Regulation* 

Securities Division Consumer Services Division PO Box 30220 Lansing, MI 48909 517-373-0220 Toll free: 1-877-999-6442 

pass:[<email>ofir-sec-info@michigan.gov</email>] 

link:$$http://www.michigan.gov/ofirsecurities$$[www.michigan.gov/ofirsecurities] 


=== Minnesota

*Department of Commerce* 

Securities Division Consumer Protection and Education 85 7th Pl. E, Suite 500 St. Paul, MN 55101 651-282-5064 Toll free: 1-800-657-3602 (MN) TTY: 651-296-2860 

pass:[<email>securities.commerce@state.mn.us</email>] 

link:$$http://www.mn.gov/commerce$$[www.mn.gov/commerce] 


=== Mississippi

*Secretary of State&rsquo;s Office* 

Securities Division Business Regulation and Enforcement PO Box 136 Jackson, MS 39205-0136 601-359-1048 

link:$$http://www.sos.ms.gov$$[www.sos.ms.gov] 


=== Missouri

Office of the Secretary of State 

Securities Division 600 W. Main St. Jefferson City, MO 65101-1276 573-751-4136 Toll free: 1-800-721-7996 (MO) 

pass:[<email>securities@sos.mo.gov</email>] 

link:$$http://www.sos.mo.gov$$[www.sos.mo.gov] 


=== Montana

*State Auditor&rsquo;s Office* 

Securities Division 840 Helena Ave. Helena, MT 59601 406-444-2040 Toll free: 1-800-332-6148 (MT) 

pass:[<email>stateauditor@mt.gov</email>] 

link:$$http://www.csi.mt.gov/consumers$$[www.csi.mt.gov/consumers] 


=== Nebraska

*Department of Banking and Finance* 

Bureau of Securities PO Box 95006 Lincoln, NE 68509-5006 402-471-3445 Toll free: 1-877-471-3445 

link:$$http://www.ndbf.ne.gov$$[www.ndbf.ne.gov] 


=== Nevada

*Office of the Secretary of State* 

Securities Division 555 E. Washington Ave., Suite 5200 Las Vegas, NV 89101 702-486-2440 

pass:[<email>nvsec@govmail.state.nv.us</email>] 

link:$$http://www.nvsos.gov$$[www.nvsos.gov] 


=== New Hampshire

*Bureau of Securities Regulation* 

107 N. Main St., #204 Concord, NH 03301 603-271-1463 Toll free: 1-800-994-4200 

pass:[<email>securities@sos.nh.gov</email>] 

link:$$sos.nh.gov/sec_reg.aspx$$[sos.nh.gov/sec_reg.aspx] 


=== New Jersey

*Department of Law and Public Safety* 

Bureau of Securities PO Box 47029 Newark, NJ 07101 973-504-3600 Toll free: 1-866-446-8378 (NJ) 

pass:[<email>Askbureauofsecurities@dca.lps.state.nj.us</email>] 

link:$$http://www.njsecurities.gov$$[www.njsecurities.gov] 


=== New Mexico

*Regulation and Licensing Department* 

Securities Division 2550 Cerrillos Rd., 3rd Floor Santa Fe, NM 87505 505-476-4580 Toll free: 1-800-704-5533 (NM) 

link:$$http://www.rld.state.nm.us/securities$$[www.rld.state.nm.us/securities] 


=== New York

*Office of the Attorney General* 

Investor Protection Bureau 120 Broadway, 23rd Floor New York, NY 10271 212-416-8222 

link:$$http://www.oag.state.ny.us$$[www.oag.state.ny.us] 


=== North Carolina

*Secretary of State* 

Securities Division PO Box 29622 Raleigh, NC 27626-0622 919-733-3924 Toll free: 1-800-688-4507 (Investor Hotline) 

pass:[<email>secdiv@sosnc.com</email>] 

link:$$http://www.secretary.state.nc.us/sec$$[www.secretary.state.nc.us/sec] 


=== North Dakota

*Securities Department* 

State Capitol 600 E. Boulevard Ave., 5th Floor Bismarck, ND 58505-0510 701-328-2910 Toll free: 1-800-297-5124 (ND) 

pass:[<email>ndsecurities@nd.gov</email>] 

link:$$http://www.ndsecurities.com$$[www.ndsecurities.com] 


=== Ohio

*Department of Commerce* 

Division of Securities 77 S. High St., 22nd Floor Columbus, OH 43215-6131 Toll free: 1-800-788-1194 (Investor Protection Hotline) 

pass:[<email>securitiesgeneral.questions@com.state.oh.us</email>] 

link:$$http://www.com.ohio.gov/secu$$[www.com.ohio.gov/secu] 


=== Oklahoma

*Department of Securities* 

First National Center 120 N. Robinson Ave., Suite 860 Oklahoma City, OK 73102 405-280-7700 

link:$$http://www.securities.ok.gov$$[www.securities.ok.gov] 


=== Oregon

*Department of Consumer and Business Services* 

Division of Finance and Corporate Securities PO Box 14480 Salem, OR 97309-0405 Toll free: 1-866-814-9710 TTY: 503-378-4100 

pass:[<email>dcbs.dfcsmail@state.or.us</email>] 

link:$$http:dfcs.oregon.gov$$[dfcs.oregon.gov] 


=== Pennsylvania

*Securities Commission* 

Eastgate Office Building, 2nd Floor 1010 N. 7th St. Harrisburg, PA 17102-1410 717-787-8061 Toll free: 1-800-600-0007 (PA) 

pass:[<email>pscwebmaster@pa.gov</email>] 

link:$$http://www.psc.state.pa.us$$[www.psc.state.pa.us] 


=== Puerto Rico

*Office of the Commissioner of Financial Institutions* 

Securities Division PO Box 11855 San Juan, PR 00910-3855 787-723-3131 TTY: 1-800-981-7711 (Consumers) 

pass:[<email>valores@ocif.gobierno.pr</email>] 

link:$$http://www.ocif.gobierno.pr$$[www.ocif.gobierno.pr] 


=== Rhode Island

*Department of Business Regulation* 

Securities Division 1511 Pontiac Ave. Cranston, RI 02920 401-462-9527 

pass:[<email>securitiesinquiry@dbr.ri.gov</email>] 

link:$$http://www.dbr.state.ri.us$$[www.dbr.state.ri.us] 


=== South Carolina

*Office of the Attorney General* 

Securities Division PO Box 11549 Columbia, SC 29211-1549 

link:$$http://www.scag.gov/scsecurities$$[www.scag.gov/scsecurities] 


=== South Dakota

*Department of Labor and Regulation* 

Division of Securities 445 E. Capitol Ave. Pierre, SD 57501-3185 605-773-4823 

pass:[<email>drr.securities@state.sd.us</email>] 

link:$$http://www.dlr.sd.gov/securities$$[www.dlr.sd.gov/securities] 


=== Tennessee

*Department of Commerce and Insurance* 

Securities Division 500 James Robertson Pkwy., Suite 680 Nashville, TN 37243-0575 615-741-2947 Toll free: 1-800-863-9117 (TN) 

pass:[<email>Securities.1@tn.gov</email>] 

link:$$http://www.state.tn.us/commerce/securities$$[www.state.tn.us/commerce/]securities 


=== Texas

*State Securities Board* 

PO Box 13167 Austin, TX 78711-3167 512-305-8300 

link:$$http://www.ssb.state.tx.us$$[www.ssb.state.tx.us] 


=== Utah

*Department of Commerce* 

Division of Securities PO Box 146760 Salt Lake City, UT 84114-6760 801-530-6600 Toll free: 1-800-721-7233 (UT) 

pass:[<email>securities@utah.gov</email>] 

link:$$http://www.securities.utah.gov$$[www.securities.utah.gov] 


=== Vermont

*Department of Financial Regulation* 

Securities Division 89 Main St. Montpelier, VT 05620-3101 802-828-3421 

pass:[<email>DFR.SecuritiesInfo@state.vt.us</email>] 

link:$$http://www.dfr.vermont.gov$$[www.dfr.vermont.gov] 


=== Virginia

*State Corporation Commission* 

Division of Securities and Retail Franchising PO Box 1197 Richmond, VA 23218 Toll free: 1-800-552-7945 (VA) TTY: 804-371-9206 

pass:[<email>SRF_General@scc.virginia.gov</email>] 

link:$$http://www.scc.virginia.gov/srf$$[www.scc.virginia.gov/srf] 


=== Washington

*Department of Financial Institutions* 

Division of Securities PO Box 41200 Olympia, WA 98504-1200 360-902-8760 Toll free: 1-877-746-4334 TTY: 360-664-8126 

link:$$http://www.dfi.wa.gov$$[www.dfi.wa.gov] 


=== West Virginia

*State Auditor&rsquo;s Office* 

Securities Commission 1900 Kanawha Blvd., E Building 1, Room W-100 Charleston, WV 25305 304-558-2251 Toll free: 1-877-982-9148 

pass:[<email>securities@wvsao.gov</email>] 

link:$$http://www.wvsao.gov/securitiescommission$$[www.wvsao.gov/]securitiescommission 


=== Wisconsin

*Department of Financial Institutions* 

Division of Securities PO Box 1768, 4th Floor Madison, WI 53701-1768 608-266-1064 TTY: 608-266-8818 

link:$$http://www.wdfi.org$$[www.wdfi.org] 


=== Wyoming

*Office of the Secretary of State* 

Compliance Division State Capitol Building 200 W. 24th St. Cheyenne, WY 82002-0020 307-777-7370 

pass:[<email>investing@wyo.gov</email>] 

link:$$http://soswy.state.wy.us$$[soswy.state.wy.us] 

