[[trade_and_professional_associations]]

== Trade and Professional Associations


.Contacting Trade and Professional Organizations
****
Companies that manufacture similar products or offer  similar services often belong to an industry association.  These associations help resolve problems between their  member companies and consumers. Most also provide  consumer information through publications and websites. 

If you have a problem with a company and cannot resolve  it by working directly with that firm, ask whether the  company is a member of an association. Then check this  section to see whether the association is listed. If the  association is not included here, your local library has  reference materials to help you find the appropriate contact. 


****


_Advertising Self-Regulation Council (ASRC)_ 

70 W. 36th St., 13th Floor New York, NY 10018 Toll-free: 1-866-334-6272 

link:$$http://www.narcpartners.org$$[www.narcpartners.org] 

link:$$http://www.asrcreviews.org$$[www.asrcreviews.org] 

ASRC fosters truth and accuracy in national advertising through voluntary self-regulation. As an effort between the advertising industry and the Council of Better Business Bureaus, ASRC helps solve disputes over advertising claims. 

_America&rsquo;s Health Insurance Plans (AHIP)_ 

601 Pennsylvania Ave., NW, South Bldg., Suite 500 Washington, DC 20004 202-778-3200 

pass:[<email>ahip@ahip.org</email>] 

link:$$http://www.ahip.org$$[www.ahip.org] 

America&rsquo;s Health Insurance Plans (AHIP) is the national association representing companies that provide health insurance coverage to more than 200 million Americans. Member companies offer medical, long-term care, disability income, dental, supplemental, stop-loss insurance and reinsurance to consumers, employers and public purchasers. 

_American Financial Services Association (AFSA) Education Foundation_ 

919 18th St., NW, Suite 300 Washington, DC 20006-5517 202-466-8611 

pass:[<email>info@afsaef.org</email>] 

link:$$http://www.afsaef.org$$[www.afsaef.org] 

The AFSAEF mission is to educate consumers on personal finance concepts and to help consumers realize the benefits of responsible money management and understand the credit process. Their MoneySKILL^®^program educates young adults on personal finance concepts in the areas of income, expenses, assets, liabilities and risk management. 

_American Arbitration Association_ 

1633 Broadway, 10th Floor New York, NY 10019 Toll-free: 1-800-778-7879 

link:$$http://www.adr.org$$[www.adr.org] 

This association is a not-for-profit public service organization committed to the resolution of disputes through arbitration, mediation, conciliation and other voluntary procedures. 

_American Bankers Association (ABA)_ 

1120 Connecticut Ave., NW Washington, DC 20036 Toll-free: 1-800-226-5377 

link:$$http://www.aba.com$$[www.aba.com] 

ABA represents the concerns of banks and their employees. The ABA&rsquo;s Education Foundation offers personal finance resources to help consumers understand their financial choices. 

_American Bar Association_ 

321 N. Clark St. Chicago, IL 60654 312-988-5000 

pass:[<email>askaba@abanet.org</email>] 

link:$$http://www.americanbar.org$$[www.americanbar.org] 

The Bar Association is an association of lawyers. The ABA accredits law schools, and provides the public with information about the law, courts and guides for legal issues. 

_American Cleaning Institute^®^ (ACI)_ 

1331 L St., NW, Suite 650 Washington, DC 20005 202-347-2900 

pass:[<email>info@cleaninginstitute.org</email>] 

link:$$http://www.cleaninginstitute.org$$[www.cleaninginstitute.org] 

ACI is the consumer source for free/low cost educational materials, designated to help individuals, families and communities stay clean, safe and healthy at home, work and school. 

_American Council of Life Insurers_ 

101 Constitution Ave., NW, Suite 700 Washington, DC 20001-2133 202-624-2000 

pass:[<email>contact@acli.com</email>] 

link:$$http://www.acli.com$$[www.acli.com] 

The American Council of Life Insurers is a trade association of over 500 insurance companies that provide life insurance, pensions and annuities, long-term care, and disability income insurance. 

_American Health Care Association (AHCA)_ 

1201 L St., NW Washington, DC 20005 202-842-4444 

link:$$http://www.ahcancal.org$$[www.ahcancal.org] 

This federation of affiliated state health organizations advocates for quality care and services for frail, elderly and disabled Americans. 

_American Institute of Certified Public Accountants (AICPA)_ 

220 Leigh Farm Rd. Durham, NC 27707 919-402-4500 Toll-free: 1-888-777-7077 (Ethics Hotline) 

link:$$http://www.aicpa.org$$[www.aicpa.org] 

AICPA works to ensures that the public remains confident in the integrity, competence and professionalism of CPAs. 

_American Moving and Storage Association (AMSA)_ 

1611 Duke St. Alexandria, VA 22314 703-683-7410 Toll-free: 1-888-849-2672 

link:$$http://www.moving.org$$[www.moving.org] 

AMSA offers a wealth of information on its consumer website, including a Mover Referral Service. It also sponsors a dispute settlement program to help consumers resolve loss and damage claims on interstate moves. 

_American Pharmacists Association (APhA)_ 

2215 Constitution Ave., NW Washington, DC 20037 202-628-4410 Toll-free: 1-800-237-2742 

link:$$http://www.pharmacist.com$$[www.pharmacist.com] 

The APhA empowers its members to improve medication use and advance patient care through information, education, and advocacy. 

_American Society of Travel Agents, Inc. (ASTA)_ 

1101 King St., Suite 200 Alexandria, VA 22314 703-739-2782 

pass:[<email>consumeraffairs@asta.org</email>] 

link:$$http://www.astanet.com$$[www.astanet.com] 

ASTA is an association of travel industry professionals. It provides training and education to professionals. They offer travel tips for consumers and accept consumer complaints about poor travel service. 

_Assisted Living Federation of America (ALFA)_ 

1650 King St., Suite 602 Alexandria, VA 22314 703-894-1805 

link:$$http://www.alfa.org$$[www.alfa.org] 

ALFA sets best practices for senior living. They also provide a directory of senior living communities and other materials to help consumers determine their assisted living needs. 

_Association of Credit and Collection Professionals (ACA International)_ 

PO Box 390106 Minneapolis, MN 55439 952-926-6547 

pass:[<email>aca@acainternational.org</email>] 

link:$$http://www.askdoctordebt.com$$[www.askdoctordebt.com] 

ACA International&rsquo;s sets ethical standards for companies in the debt collection industry. They also use their website, link:$$http:askdoctordebt.org$$[askdoctordebt.org, to educate consumers about their]rights. 

_Association of Independent Consumer Credit Counseling Agencies (AICCCA)_ 

11350 Random Hills Rd., Suite 800 Fairfax, VA 22030 Toll-free: 1-866-703-8787 

link:$$http://www.aiccca.org$$[www.aiccca.org] 

AICCCA represents non-profit credit counseling companies. AICCCA sets industry standards to ensure that member companies provide quality service to consumers. The organization also provides information directly to consumers (budgeting tips and a searchable database to locate a credit counseling company) on their website. 

_Automotive Recyclers Association (ARA)_ 

9113 Church St. Manassas, VA 20110 571-208-0428 Toll-free: 1-888-385-1005 

link:$$http://www.a-r-a.org$$[www.a-r-a.org] 

ARA member companies are dedicated to the efficient removal and reuse of automotive parts, and the safe disposal of inoperable motor vehicles. 

_Cellular Telecommunications and Internet Association (CTIA)_ 

1400 16th St., NW, Suite 600 Washington, DC 20036 202-736-3200 

link:$$http://www.ctia.org$$[www.ctia.org] 

CTIA oversees certification programs to ensure a high standard of quality for consumers of wireless devices. 

_Certified Financial Planner Board of Standards_ 

1425 K St., NW, Suite 500 Washington, DC 20005 202-379-2200 Toll-free: 1-800-487-1497 

pass:[<email>mail@cfpboard.org</email>] 

link:$$http://www.cfp.net$$[www.cfp.net] 

The CFP Board works to ensure that the public benefits from competent financial planning. The CFP Board certifies financial planners who meet its requirements by granting use of their trademarks. 

_Commission on the Accreditation of Rehabilitation Facilities (CARF)_ 

6951 E. Southpoint Rd. Tucson, AZ 85756 Toll-free: 1-888-281-6531 

link:$$http://www.carf.org$$[www.carf.org] 

CARF is an independent accrediting body of rehabilitation, addiction, substance abuse, and retirement living services. The organization provides an online search tool to find services that match your rehabilitiation needs, as well as links to consumer resources. 

_Consumer Electronics Association (CEA)_ 

1919 S. Eads St. Arlington, VA 22202 703-907-7600 Toll-free: 1-866-858-1555 

pass:[<email>cea@ce.org</email>] 

link:$$http://www.ce.org$$[www.ce.org] 

CEA represents corporations involved in the design, development, manufacture and distribution consumer electronics. They offer free guides for buying electronics to consumers. 

_Credit Union National Association (CUNA)_ 

5710 Mineral Point Rd. Madison, WI 53705-0431 Toll-free: 1-800-356-9655 

link:$$http://www.cuna.org$$[www.cuna.org] 

CUNA serves more than 90% of credit unions through credit union leagues throughout the nation. 

_Direct Marketing Association (DMA)_ 

1120 Avenue of the Americas New York, NY 10036-6700 212-768-7277 ext. 1888 

pass:[<email>consumer@the-dma.org</email>] 

link:$$http://www.dmachoice.org$$[www.dmachoice.org] 

The DMA is the trade association for organizations involved in direct marketing. via direct mail, catalogs, the Internet, telemarketing, magazines, newspaper and TV ads. DMAs consumer website offers consumers options (free of charge) to better manage their mail. 

_Direct Selling Association (DSA)_ 

1667 K St., NW, Suite 1100 Washington, DC 20006 202-452-8866 

pass:[<email>info@dsa.org</email>] 

link:$$http://www.dsa.org$$[www.dsa.org] 

DSA is the trade association of firms that manufacture and distribute goods and services sold directly to consumers. 

_Distance Education and Training Council (DETC)_ 

1601 18th St., NW, Suite 2 Washington, DC 20009 202-234-5100 

link:$$http://www.detc.org$$[www.detc.org] 

The DETC is a voluntary, non-governmental, educational organization that accredits distance education institutions. 

_Financial Industry Regulatory Authority (FINRA)_ 

1736 K St., NW Washington, DC 20006 301-590-6500 (Call Center)  Toll-free: 1-800-289-9999 (Broker Check Hotline) 

link:$$http://www.finra.org$$[www.finra.org] 

FINRA is the largest independent regulator for all securities firms doing business in the US. The organization operates the largest dispute resolution forum in the securities industry for disputes between investors and securities firms. Consumers may check the background of individual investment professionals and firms using the BrokerCheck tool on the FINRA website. 

_Financial Planning Association (FPA)_ 

7535 E. Hampden Ave., Suite 600 Denver, CO 80231 Toll-free: 1-800-322-4237 

pass:[<email>fpa@fpanet.org</email>] 

link:$$http://www.fpanet.org$$[www.fpanet.org] 

The Financial Planning Association is a leadership and advocacy organization connecting those who provide the services with consumers they serve. This organization is a resource for the public to find educational resources and a financial planner who will deliver advice using an ethical, objective, client-centered process. 

_Food Marketing Institute (FMI)_ 

2345 Crystal Dr., Suite 800 Arlington, VA 22202 202-452-8444 

link:$$http://www.fmi.org$$[www.fmi.org] 

FMI conducts programs in research, education, industry relations and public affairs on behalf of grocery retailers and wholesalers. 

_Grocery Manufacturers Association (GMA)_ 

1350 I St. NW, Suite 300 Washington, DC 20005 202-639-5900 Toll-free: 1-800-355-0983 

link:$$http://www.gmaonline.org$$[www.gmaonline.org] 

GMA represents food, beverage, and consumer products companies. The Association helps to ensure the safety and security of consumer packaged goods. 

_Insurance Information Institute (III)_ 

110 William St. New York, NY 10038 212-346-5500 

pass:[<email>info@iii.org</email>] 

link:$$http://www.iii.org$$[www.iii.org] 

The III is a nonprofit, communications organization supported by the property/casualty insurance industry that works to improve public understanding of insurance. 

_International Association of Movers (IAM)_ 

5904 Richmond Hwy., Suite 404 Alexandria, VA 22303 703-317-9950 

pass:[<email>info@iamovers.org</email>] 

link:$$http://www.iamovers.org$$[www.iamovers.org] 

IAM is a global association of movers and forwarders committed to providing customers with the highest level of service available. IAM offers consumer tips for moving, domestically or internationally, on their website. 

_International Cemetery, Cremation and Funeral Association (ICCFA)_ 

107 Carpenter Dr., Suite 100 Sterling, VA 20164 703-391-8400 Toll-free: 1-800-645-7700 

link:$$http://www.iccfa.com$$[www.iccfa.com] 

ICCFA is the trade association dedicated to funerals, and final resting places. They provide management guidance to members and advocate for consumer choice and dispute resolution in circumstances surrounding final arrangements. 

_Joint Commission_ 

One Renaissance Blvd. Oakbrook Terrace, IL 60181 630-792-5000 

link:$$http://www.jointcommission.org$$[www.jointcommission.org] 

The Joint Commission accredits and certifies healthcare organizations and Programs. 

_LeadingAge_ 

2519 Connecticut Ave., NW Washington, DC 20008 202-783-2242 

pass:[<email>info@leadingage.org</email>] 

link:$$http://www.leadingage.org$$[www.leadingage.org] 

LeadingAge represents not-for-profit nursing homes, continuing care retirement communities, assisted living and senior housing facilities, and community service organizations. Consumers may search LeadingAge&rsquo;s online database for providers and facilities that fit their needs. 

_Mortgage Bankers Association of America (MBA)_ 

1717 Rhode Island Ave., NW, Suite 400 Washington, DC 20036 202-557-2700 

link:$$http://www.mortgagebankers.org$$[www.mortgagebankers.org] 

The MBA is the national association representing the real estate finance industry, including mortgage banking firms, commercial banks, life insurance companies, title companies, and savings and loan associations. 

_Mystery Shopping Providers Association (MSPA)_ 

455 S. 4th St., Suite 650 Louisville, KY 40202 

link:$$http://www.mysteryshop.org$$[www.mysteryshop.org] 

The MSPA is dedicated to improving service quality using anonymous shoppers. MSPA does not hire mystery shoppers, but they do provide a voluntary certification program for mystery shoppers. 

_National Association of Attorneys General (NAAG)_ 

2030 M St., NW, 8th Floor Washington, DC 20036 202-326-6000 

link:$$http://www.naag.org$$[www.naag.org] 

NAAG facilitates communication among attorneys general, who are responsible for enforcing civil laws in their respective states. The AG offices often oversee state government regulation agencies and represent the public interest. 

_National Association of Home Builders (NAHB)_ 

1201 15th St., NW Washington, DC 20005 202-266-8200 Toll-free: 1-800-368-5242 

link:$$http://www.nahb.org$$[www.nahb.org] 

NAHB works so that consumers have access to safe, decent, and affordable housing. 

_National Association of Insurance Commissioners (NAIC)_ 

1100 Walnut St., Suite 1500 Kansas City, MO 64106-2197 816-842-3600 Toll-free: 1-866-470-6242 

pass:[<email>webpost@naic.org</email>] 

link:$$http://www.InsureUonline.org$$[www.InsureUonline.org] 

link:$$http://www.naic.org$$[www.naic.org] 

NAIC is a national organization of insurance regulators. The organization helps insurance regulators facilitate the fair and equitable treatment of insurance consumers and promote competitive markets. 

_National Association of Professional Insurance Agents (PIA)_ 

400 N. Washington St. Alexandria, VA 22314 703-836-9340 

pass:[<email>piainfo@pianet.org</email>] 

link:$$http://www.PIANET.com$$[www.pianet.com] 

This association represents the interests and needs of insurance agents. 

_National Association of Realtors (NAR)_ 

430 N. Michigan Ave. Chicago, IL 60611-4087 312-329-8200 Toll-free: 1-800-874-6500 

link:$$http://www.realtor.org$$[www.realtor.org] 

NAR is the organization of real estate agents. It develops standards for effective and ethical real estate business practices. 

_National Foundation for Credit Counseling (NFCC)_ 

2000 M St., NW, Suite 505 Washington, DC 20036 Toll-free: 1-800-388-2227 

link:$$http://www.nfcc.org$$[www.nfcc.org] 

The NFCC promotes the national agenda for financially responsible behavior and builds capacity for its members to deliver the highest quality financial education and counseling services. Contact NFCC to locate an affiliated financial counseling agency in your area. 

_National Funeral Directors Association (NFDA)_ 

13625 Bishops Dr. Brookfield, WI 53005-6607 262-789-1880 Toll-free: 1-800-228-6332 

pass:[<email>nfda@nfda.org</email>] 

link:$$http://www.nfda.org$$[www.nfda.org] 

NFDA helps consumers make informed decisions about funeral services and offers a third party dispute resolution program for complaints regarding funeral homes. 

_National Futures Association (NFA)_ 

300 S. Riverside Plaza, Suite 1800 Chicago, IL 60606-6615 312-781-1300 

pass:[<email>information@nfa.futures.org</email>] 

link:$$http://www.nfa.futures.org$$[www.nfa.futures.org] 

NFA is the industry-wide self-regulatory organization for the U.S. futures industry. NFA provides innovative and efficient regulatory programs and services that safeguard the integrity of the derivatives markets. Consumers should contact NFA regarding any firm or individual who solicits them for investments in futures, options on futures and foreign currency. 

_National Institute for Automotive Service Excellence (ASE)_ 

101 Blue Seal Dr. SE, Suite 101 Leesburg, VA 20175 703-669-6600 Toll-free: 1-888-273-8378 

pass:[<email>webmaster@ase.com</email>] 

link:$$http://www.ase.com$$[www.ase.com] 

ASE is an independent organization that works to improve the quality of automotive service and repair through the voluntary testing and certification of automotive repair professionals. 

_Network Branded Prepaid Card Association (NBPCA)_ 

110 Chestnut Ridge Rd., Suite 111 Montvale, NJ 07645-1706 

link:$$http://www.nbpca.com$$[www.nbpca.com] 

NBPCA represents all companies involved in providing prepaid cards that carry a brand network logo (American Express, Discover, Mastercard, or Visa) that can be used at numerous retailers. You can contact the association to get tips on how to use and maintain your card, or ask experts your questions about your prepaid cards. 

_North American Consumer Protection Investigators_ 

pass:[<email>webmaster@nacpi.org</email>] 

link:$$http://www.nacpi.org$$[www.nacpi.org] 

NACPI provides training and support for consumer protection investigators in government agencies at all levels. NACPI does not investigate individual consumer complaints, but helps investigators share information of mutual concern. 

_North American Securities Administrators Association, Inc. (NASAA)_ 

750 1st St., NE, Suite 1140 Washington, DC 20002 202-737-0900 

pass:[<email>info@nasaa.org</email>] 

link:$$http://www.nasaa.org$$[www.nasaa.org] 

NASAA is an international organization devoted to investor protection. NASAA is the voice of the 50 state securities agencies responsible for grass-roots investor protection, investor education and efficient capital formation. 

_Society of Consumer Affairs Professionals International (SOCAP)_ 

625 N. Washington St., Suite 304 Alexandria, VA 22314 703-519-3700 

pass:[<email>socap@socap.org</email>] 

link:$$http://www.socap.org$$[www.socap.org] 

SOCAP provides training, conferences and publications to encourage and promote effective communication and understanding among business, government and consumers; and to define and advance the consumer affairs profession. 

_Tire Industry Association (TIA)_ 

1532 Pointer Ridge Pl., Suite G Bowie, MD 20716-1883 301-430-7280 Toll-free: 1-800-876-8372 

pass:[<email>info@tireindustry.org</email>] 

link:$$http://www.tireindustry.org$$[www.tireindustry.org] 

TIA represents all members of the tire industry, including companies that manufacture, sell, recycle, retread tires, along with their suppliers. 

_Toy Industry Association, Inc. (TIA)_ 

1115 Broadway, Suite 400 New York, NY 10010 212-675-1141 

pass:[<email>info@toyassociation.org</email>] 

link:$$http://www.toyinfo.org$$[www.toyinfo.org] 

link:$$http://www.toy-tia.org$$[www.toy-tia.org] 

TIA is the not-for-profit trade association for producers and importers of toys and youth entertainment products sold in North America. 

_United States Tour Operators Association (USTOA)_ 

345 7th Ave., Suite 1801 New York, NY 10001 212-599-6599 

pass:[<email>information@ustoa.com</email>] 

link:$$http://www.ustoa.com$$[www.ustoa.com] 

USTOA is composed of companies whose tours and packages encompass the entire globe and who conduct business in the U.S. 

